### ISSUE TITLE
engine_pkcs11-0.4.0-2.fc24 can't read private key from pkcs token

### ISSUE THREAD

**Issue by kostousov-ds** [OpenSC/libp11#104]
Description of problem:
I use rutoken-csp. With engine_pkcs11-0.2.0-2.fc24.x86_64 openssl can read private key from the token.

Command:
echo "engine -t dynamic -pre SO_PATH:/usr/lib64/openssl/engines/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib64/opensc-pkcs11.so
rsautl -engine pkcs11 -keyform engine -inkey slot_1-id_123456 -sign -in ./cs_pkcs11_in -out ./cs_pkcs11_out" |openssl

With engine_pkcs11-0.2.0-2.fc24.x86_64 openssl requests a pin. After upgrading to engine_pkcs11-0.4.0-2.fc24.x86_64 openssl reports about error:
OpenSSL> (dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib64/openssl/engines/libpkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/usr/lib64/opensc-pkcs11.so
Loaded: (pkcs11) pkcs11 engine
     [ available ]
OpenSSL> engine "pkcs11" set.
Invalid slot number: 1
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140337634576248:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
error in rsautl

Version-Release number of selected component (if applicable):
0.4.0-2.fc24

How reproducible:

Steps to Reproduce:
1. create a rsa:2048 keypair on a token (with  engine_pkcs11-0.2.0)
2. upgrade to engine_pkcs11-0.4.0
3. sign some data with above command

Actual results:
unable to load Private Key
error in rsautl

Expected results:
openssl requests a pin

Additional info:
downgrading to engine_pkcs11-0.2.0-2.fc24.x86_64 solves the problem

**Comment by dwmw2** [comment]
Hm, this works if I use a standard [PKCS#11 URI](http://tools.ietf.org/html/rfc7512) to identify the object:
```
$ openssl rsautl -engine pkcs11 -keyform engine -inkey 'pkcs11:manufacturer=piv_II;id=%01' \
                 -sign -in foo -out bar
engine "pkcs11" set.
PKCS#11 token PIN: 
```
*(It then fails, but that's because I haven't constructed something sane in `foo` for it to sign.)*

Using the modern way of loading the engine as shown above, it actually loads `p11-kit-proxy.so` to make the system-configured tokens available by default, so the slot numbers are likely to be different. But even if I copy your example of doing things the old way, it doesn't seem to work for me (with `slot_1-id_01` as the ID for my test case, of course).

So it looks like we might have broken the legacy ID format handling, when we added RFC7512 support. That isn't intentional, and isn't acceptable — I'll take a look. In the meantime, a suitable workaround is to forget all you ever knew about that horrible old method of loading the engine and its special format for identifiers. Instead just invoke it by name `-engine pkcs11` and refer to the object by its PKCS#11 URI, as in my example above. You can list the objects in your own token with something like `p11tool --list-all pkcs11:model=PKCS%2315`.

The [OpenConnect documentation](http://www.infradead.org/openconnect/pkcs11.html) has primer on using PKCS#11 URIs. You seem to be using Fedora — please remember that if you find *any* application packaged for Fedora which doesn't automatically accept a PKCS#11 URI in place of a filename for a certificate, it is violating the [Fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:SSLCertificateHandling); please file a bug and Cc me.

**Comment by kostousov-ds** [comment]
```
% p11tool --list-all
warning: no token URL was provided for this operation; the available tokens are:

pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
pkcs11:model=PKCS%2315;manufacturer=Aktiv%20Co.;serial=00000000303E60D0;token=Rutoken%20ECP%20%28User%20PIN%29

% p11tool --list-all pkcs11:model=PKCS%2315
Object 0:
        URL: pkcs11:model=PKCS%2315;manufacturer=Aktiv%20Co.;serial=00000000303E60D0;token=Rutoken%20ECP%20%28User%20PIN%29;id=%6e%65%77%6b%65%79%73%65%74;object=username-ra;type=public
        Type: Public key
        Label: username-ra
        Flags: CKA_WRAP/UNWRAP; CKA_SENSITIVE; 
        ID: 6e:65:77:6b:65:79:73:65:74

Object 1:
        URL: pkcs11:model=PKCS%2315;manufacturer=Aktiv%20Co.;serial=00000000303E60D0;token=Rutoken%20ECP%20%28User%20PIN%29;id=%6e%65%77%6b%65%79%73%65%74;object=Certificate;type=cert
        Type: X.509 Certificate
        Label: Certificate
        ID: 6e:65:77:6b:65:79:73:65:74

% pkcs15-tool -D
Using reader with a card: Aktiv Rutoken ECP 00 00
PKCS#15 Card [Rutoken ECP]:
        Version        : 0
        Serial number  : 00000000303E60D0
        Manufacturer ID: Aktiv Co.
        Last update    : 20141006101238Z
        Flags          : EID compliant

PIN [Security Officer PIN]
        Object Flags   : [0x3], private, modifiable
        ID             : 01
        Flags          : [0x99], case-sensitive, unblock-disabled, initialized, soPin
        Length         : min_len:8, max_len:32, stored_len:32
        Pad char       : 0x00
        Reference      : 1 (0x01)
        Type           : ascii-numeric

PIN [User PIN]
        Object Flags   : [0x3], private, modifiable
        ID             : 02
        Flags          : [0x19], case-sensitive, unblock-disabled, initialized
        Length         : min_len:4, max_len:32, stored_len:32
        Pad char       : 0x00
        Reference      : 2 (0x02)
        Type           : ascii-numeric

Private RSA Key [Certificate]
        Object Flags   : [0x3], private, modifiable
        Usage          : [0x2E], decrypt, sign, signRecover, unwrap
        Access Flags   : [0x0]
        ModLength      : 2048
        Key ref        : 1 (0x1)
        Native         : yes
        Path           : 3f001000100060020001
        Auth ID        : 02
        ID             : 6e65776b6579736574
        MD:guid        : {---deleted guid---}
          :cmap flags  : 0x0
          :sign        : 0
          :key-exchange: 0

Public RSA Key [username-ra]
        Object Flags   : [0x2], modifiable
        Usage          : [0xD1], encrypt, wrap, verify, verifyRecover
        Access Flags   : [0x0]
        ModLength      : 2048
        Key ref        : 0 (0x0)
        Native         : no
        Path           : 3f0050000200
        ID             : 6e65776b6579736574

X.509 Certificate [Certificate]
        Object Flags   : [0x2], modifiable
        Authority      : no
        Path           : 3f0050000300
        ID             : 6e65776b6579736574
        Encoded serial : 02 08 33EF71EA26635FE2


% openssl rsautl -engine pkcs11 -keyform engine -inkey 'pkcs11:serial=00000000303E60D0;id=6e65776b6579736574' -sign -in ./cs_pkcs11_in -out ./cs_pkcs11_out
engine "pkcs11" set.
PKCS#11 token PIN: 
Key not found.
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140109514778488:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
```

**Comment by dwmw2** [comment]
Try `pkcs11:serial=00000000303E60D0;id=%6e%65%77%6b%65%79%73%65%74`

Or actually, given that your ID appears to be printable characters, you don't need to hex-escape it. This should work: `pkcs11:serial=00000000303E60D0;id=newkeyset`

**Comment by kostousov-ds** [comment]
Ok. This is works fine. Thanks.

**Comment by dwmw2** [comment]
I think the problem here isn't ID parsing; it's that we are still loading the default module (in your case `p11-kit-proxy.so`) instead of the one you asked for.

In your initial example there is a call to `engine_finish()` after the first line (`engine -t dynamic...`) and before the second (`rsautl -engine pkcs11...`). Since @mtrojnar's commit 32feafd257728c0edf4e6e016e0be06c1376e547 this results in us throwing away the `MODULE_PATH` information that was provided, and starting afresh (with the default module) when the engine is reinvoked for the second command.

**Comment by mtrojnar** [comment]
I possibly misunderstood the purpose of the callback registered by `ENGINE_set_finish_function()`.
What is this callback supposed to do if not cleaning the configured state of the engine?

**Comment by dwmw2** [comment]
There are two types of reference count on engines. One is a *'functional reference'*, when something is actually *using* the engine. The other is a *'structural reference'*, when it is simply loaded and present. See the [ENGINE(3) man page](https://wiki.openssl.org/index.php/Manual:Engine(3)#Reference_counting_and_handles) for details.

I think much of what you're clearing out in `engine_finish()` wants to survive until `engine_destroy()`.

**Comment by mtrojnar** [comment]
Good point.  Thank you.

**Comment by dwmw2** [comment]
Note: *"much of"* but not all. Conceptually, I think you were actually right. When `engine_finish()` happens, we are done with the ENGINE. It is now dormant, as if it had never been invoked. It's still *there*, an a structural reference exists, and someone *else* can use it. But it's done unless someone else invokes it later.

So I think it's correct to call `PKCS11_release_all_slots()` and `PKCS11_CTX_unload()` and `PKCS11_CTX_free()` from `engine_finish()`.

All you really need to *keep* are the long-term configuration items like the module path and maybe the PIN, which we do need to survive for backward compatibility with legacy usage.

**Comment by dwmw2** [comment]
We should probably ship a 0.4.2 ASAP with this fixed. I'm all for pushing people to adopt the new methods and leave the baroque legacy crap behind, but I don't think we should just *break* it... 

Not *quite* yet, at least :)

**Comment by mtrojnar** [comment]
It is a pity we didn't find this regression a few days earlier.

Yes, I intend to release 0.4.2 after this fix gets some testing.

**Comment by mtrojnar** [comment]
Can you confirm that https://github.com/OpenSC/libp11/commit/249e09ff476478c84ddc4fcd192ff57caeddb54d fixes this issue?

**Comment by dwmw2** [comment]
Yes, it works for the test case above; thanks.

**Comment by kostousov-ds** [comment]
```
% rpm -qa engine_pkcs11\*
engine_pkcs11-0.4.0-2.fc24.x86_64
% openssl req -engine pkcs11 -keyform engine -key pkcs11:id=newkeyset -new -out req.csr -subj "/C=RU/CN=testkey"
Failed to enumerate slots
can't use that engine
140467745634168:error:80002005:Vendor defined:PKCS11_enum_slots:General Error:p11_slot.c:398:
140467745634168:error:260B806D:engine routines:ENGINE_TABLE_REGISTER:init failed:eng_table.c:175:
no engine specified
unable to load Private Key
```

What I do wrong?

**Comment by dwmw2** [comment]
That suggests that a `C_GetSlotInfo()` call failed. Is there anything in the logs? Can you add `log-calls:yes` to the `/usr/share/p11-kit/modules/opensc.module` file?

What does `p11tool --list-tokens` say?

**Comment by kostousov-ds** [comment]
```
% p11tool --list-tokens
Token 0:
        URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
        Label: System Trust
        Type: Trust module
        Manufacturer: PKCS#11 Kit
        Model: p11-kit-trust
        Serial: 1
        Module: p11-kit-trust.so


Token 1:
        URL: pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
        Label: Default Trust
        Type: Trust module
        Manufacturer: PKCS#11 Kit
        Model: p11-kit-trust
        Serial: 1
        Module: p11-kit-trust.so


Token 2:
        URL: pkcs11:model=PKCS%2315;manufacturer=Aktiv%20Co.;serial=0000000031296E36;token=Rutoken%20ECP%20%28User%20PIN%29
        Label: Rutoken ECP (User PIN)
        Type: Hardware token
        Manufacturer: Aktiv Co.
        Model: PKCS#15
        Serial: 0000000031296E36
        Module: opensc-pkcs11.so
```

**Comment by kostousov-ds** [comment]
```
% openssl req -engine pkcs11 -new -key 'pkcs11:id=newkeyset' -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
C_Initialize
  IN: pInitArgs = NULL
C_Initialize = CKR_OK
C_GetSlotList
  IN: tokenPresent = CK_FALSE
  IN: pulCount = 0x7FFCC75CED90 = 0
 OUT: pSlotList = (2) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
  IN: tokenPresent = CK_FALSE
  IN: pulCount = 0x7FFCC75CED90 = 2
 OUT: pSlotList = (2) [ SL18446744073709551615, SL1 ]
C_GetSlotList = CKR_OK
C_GetSlotInfo
  IN: slotID = SL18446744073709551615
 OUT: pInfo = {
        slotDescription: "Virtual hotplug slot"
        manufacturerID: "OpenSC (www.opensc-project.org)"
        flags: 6 = CKF_REMOVABLE_DEVICE | CKF_HW_SLOT
        hardwareVersion: 0.0
        firmwareVersion: 0.0
      }
C_GetSlotInfo = CKR_OK
C_GetSlotInfo
  IN: slotID = SL1
C_GetSlotInfo = CKR_GENERAL_ERROR
Failed to enumerate slots
C_Finalize
  IN: pReserved = NULL
C_Finalize = CKR_OK
can't use that engine
140659437213560:error:80002005:Vendor defined:PKCS11_enum_slots:General Error:p11_slot.c:398:
140659437213560:error:260B806D:engine routines:ENGINE_TABLE_REGISTER:init failed:eng_table.c:175:
no engine specified
unable to load Private Key
```

**Comment by dwmw2** [comment]
Err... that looks like OpenSC suddenly started misbehaving. Did you change it? If you invoke it directly from the engine (by setting `$PKCS11_MODULE_PATH` to point to `opensc-pkcs11.so`) does that make a difference?

**Comment by kostousov-ds** [comment]
```
[kostousov-ds@kostousov-ds 12:56:17]token(0)% export PKCS11_MODULE_PATH=/usr/lib64/pkcs11/opensc-pkcs11.so
[kostousov-ds@kostousov-ds 12:56:39]token(0)% openssl req -engine pkcs11 -new -key 'pkcs11:id=newkeyset' -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
engine "pkcs11" set.
Specified object not found
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
139884786886520:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
[kostousov-ds@kostousov-ds 12:56:47]token(1)% echo $PKCS11_MODULE_PATH
/usr/lib64/pkcs11/opensc-pkcs11.so
[kostousov-ds@kostousov-ds 12:56:55]token(0)% unset PKCS11_MODULE_PATH
[kostousov-ds@kostousov-ds 12:57:17]token(0)% openssl req -engine pkcs11 -new -key 'pkcs11:id=newkeyset' -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
C_Initialize
  IN: pInitArgs = NULL
C_Initialize = CKR_OK
C_GetSlotList
  IN: tokenPresent = CK_FALSE
  IN: pulCount = 0x7FFFF78CEFD0 = 0
 OUT: pSlotList = (1) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
  IN: tokenPresent = CK_FALSE
  IN: pulCount = 0x7FFFF78CEFD0 = 1
 OUT: pSlotList = (1) [ SL18446744073709551615 ]
C_GetSlotList = CKR_OK
C_GetSlotInfo
  IN: slotID = SL18446744073709551615
 OUT: pInfo = {
        slotDescription: "Virtual hotplug slot"
        manufacturerID: "OpenSC (www.opensc-project.org)"
        flags: 6 = CKF_REMOVABLE_DEVICE | CKF_HW_SLOT
        hardwareVersion: 0.0
        firmwareVersion: 0.0
      }
C_GetSlotInfo = CKR_OK
engine "pkcs11" set.
No private keys found.
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140639482107768:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
C_Finalize
  IN: pReserved = NULL
C_Finalize = CKR_OK
[kostousov-ds@kostousov-ds 12:57:23]token(1)% rpm -qa opensc\*                                                                                                                   
opensc-0.15.0-6.fc24.x86_64
```

**Comment by dwmw2** [comment]
Wait, that second one is the *same* as your previous test, isn't it? Yet the failure mode is different.

The failure mode is entirely comprehensible, in fact — your identifier `pkcs11:id=newkeyset` didn't say *which* token the key is found in. And we typically can't see keys until we log in. Rather than logging in to *every* token in the system just to see if we can find it, we bail out.

Try `pkcs11:manufacturer=Aktiv%20Co.;id=newkeyset`

**Comment by kostousov-ds** [comment]
I wrote a shell command with output. You can compare test. [Comment](https://github.com/OpenSC/libp11/issues/104#issuecomment-251892983) contains 2 tests: with PKCS11_MODULE_PATH and without it.

With `pkcs11:manufacturer=Aktiv%20Co.;id=newkeyset` openssl works correctly.

**Comment by dwmw2** [comment]
My observation was that the second test in https://github.com/OpenSC/libp11/issues/104#issuecomment-251892983 was identical to your earlier test in https://github.com/OpenSC/libp11/issues/104#issuecomment-251887204 in which OpenSC was misbehaving. But the outcome was different.

**Comment by kostousov-ds** [comment]
There both tests are the same. But the first one runs with PKCS11_MODULE_PATH set, second without.

**Comment by dwmw2** [comment]
Yes. My point was that the second one, with `PKCS11_MODULE_PATH` unset, was the same as a test in your *earlier* comment.

**Comment by kostousov-ds** [comment]
Yes, usually PKCS11_MODULE_PATH is unset

**Comment by kostousov-ds** [comment]
Can you help with another problem?
https://bugzilla.redhat.com/show_bug.cgi?id=1393751
