### ISSUE TITLE
Stop caching PIN values entirely

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#114]
(forked from discussion in PR #101)

The change in commit 7573c6e moved to using the UI_METHOD* specified on the PKCS11 key to grab the CKA_ALWAYS_AUTHENTICATE PIN rather than using the cached value.

I may be wrong, but I thought that was the only place that the PIN ever needs to be re-used *post* the `C_Login` call. It would give libp11 a better security posture if it never copied PINs at all in memory, or else always `OPENSSL_cleanse` the values it copies (inherent in the UI_METHOD interface, I think) as soon as it calls `C_Login`. 

The only PIN that may need to be long-lived (probably) would be those specified by the `PIN` engine_ctrl command since that would indicate a global PIN used for future slots (except for when a key URI has a pin-value set on it, I suppose).

**Comment by mtrojnar** [comment]
We only never cache CKU_CONTEXT_SPECIFIC login PINs.

Caching slot PINs is required for atfork to work implemented by @nmav in https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1 with later changes.
