### ISSUE TITLE
Lazily request CKA_ALWAYS_AUTHENTICATE PIN?

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#115]
It was suggested in PR #101 that requesting the PIN from the UI eagerly when `CKA_ALWAYS_AUTHENTICATE` as is done at present can result in unnecessary PIN requests when the underlying PKCS11 module did not really require it quite yet. 

In this scheme, libp11 could perhaps just charge forward in performing operations w/o re-authentication and then re-prompt for auth only if `CKR_USER_NOT_LOGGED_IN` is returned. 

I am not necessarily advocating for this, and am not sure if it is a good idea or if it is properly adhering to the spec. Just wanted to make sure it got singled out as a separate issue from #101 and received separate attention.

**Comment by dwmw2** [comment]
Cf. https://lists.oasis-open.org/archives/pkcs11-comment/201609/msg00000.html

**Comment by mtrojnar** [comment]
https://github.com/OpenSC/libp11/commit/5394c2c55ac49ffb6c7d360f7b78b6764bdef7c9 implements it.
