### ISSUE TITLE
`make check` failure

### ISSUE THREAD

**Issue by dwmw2** [OpenSC/libp11#116]
On Fedora 23, the `rsa-listtestkeys.softhsm` test is failing because SoftHSMv2 seems to set `CKA_PRIVATE` on public keys, and then they don't show up when we enumerate keys without logging in.

Also, the `ec-testfork` test fails when built against OpenSSL HEAD.

**Comment by mtrojnar** [comment]
I confirm the tests fail with old versions of SoftHSM.  I don't care.

**Comment by dwmw2** [comment]
FWIW for OpenConnect I actually import the SoftHSM database files into git too, to protect against changes in the way that the import tools work. But then I'm *explicitly* testing variants with and without `CKA_PRIVATE`, and really do care.

**Comment by dwmw2** [comment]
It's the same version of SoftHSM, btw.

**Comment by mtrojnar** [comment]
The point of testing libp11 is *not* to find old (already fixed) bugs in its dependencies.
Feel free to fork a version of libp11 that would pass `make check` on Fedora 23.

**Comment by dwmw2** [comment]
This isn't a bug in its dependencies. It's a false assumption in the test case. We *assume* that the token doesn't set `CKA_PRIVATE` on the keys by default. It works in Fedora 24 only because `pkcs11-tool` explicitly sets `CKA_PRIVATE` to `CK_FALSE`.

**Comment by mtrojnar** [comment]
Feel free to submit a PR.

**Comment by dwmw2** [comment]
I was working on one —  to do proper lifetime checking of keys used via the engine. It'll get a key from the engine, `ENGINE_finish()`, `EVP_PKEY_get1_RSA()`, `EVP_PKEY_free()` then use the `RSA` it has left and see what blows up :)

Both my initial runs of `make check` failed though...

**Comment by mouse07410** [comment]
> This isn't a bug in its dependencies. It's a false assumption in the test case.

Respectfully disagree. The correct assumption based on the current PKCS#11 standard is that `CKA_PRIVATE` is set on *private* keys, and is *not* set on public ones.

> We assume that the token doesn't set `CKA_PRIVATE` on the keys by default. 

And this is the correct assumption based on the current standard. The older publications weren't as explicit on it, but the common sense should have suggested this anyway.

Originally SoftHSMv2 was setting this parameter to `CK_TRUE` by default. But after [discussing](https://github.com/opendnssec/SoftHSMv2/issues/223) and reviewing the latest PKCS#11 v2.40 document, they agreed that it should be set to `CK_FALSE` by default, and changed/fixed their code.

> It works in Fedora 24 only because pkcs11-tool explicitly sets `CKA_PRIVATE` to `CK_FALSE`.

Are you saying that `pkcs11-tool` by default would set `CKA_PRIVATE` to `CK_TRUE`?! I thought that `pkcs11-tool` did not specify anything, and the default of the old SoftHSMv2 was `CK_TRUE`, which is no longer true (no pun intended :) ).

In any case, upgrading SoftHSMv2 to its latest version is recommended. ;-)

**Comment by dwmw2** [comment]
> The correct assumption based on the current PKCS#11 standard is that CKA_PRIVATE is set on private keys, and is not set on public ones.

Gr, I thought we had dealt with that misunderstanding on your part? That assumption is not based on the PKCS#11 standard. It's perfectly valid for a `CKO_PRIVATE_KEY` object not to have the orthogonal `CKA_PRIVATE` flag set, The PIV token even *has* such a key; the CARD AUTH key is designed to be used without authentication.IT's also perfectly valid for `CKO_CERTIFICATE` and `CKO_PUBLIC_KEY` objects (and others) to have `CKA_PRIVATE` set. 

Sure, SoftHSMv2 has changed its default for public keys because it's better that way, and `pkcs11-tool` has started explicitly setting it to `CK_FALSE` when importing public keys because it's better that way. But it was never *wrong* and never violated the standard; it was just not the ideal setup.

> Are you saying that pkcs11-tool by default would set CKA_PRIVATE to CK_TRUE?! I thought that pkcs11-tool did not specify anything, and the default of the old SoftHSMv2 was CK_TRUE, which is no longer true (no pun intended :) ).

Both changed. `pkcs11-tool` merely didn't specify the value of `CKA_PRIVATE`, leaving it to the token's default. Now it explicitly sets `CKA_PRIVATE` to `CK_FALSE` for public keys and certificates. And meanwhile, SoftHSMv2 changed its default for those types too.

It's not that hard to make the test case agnostic to those changes in the environment. You can import with `p11tool` or `softhsm2-util` which have explicit controls over the `CKA_PRIVATE` attribute. And/or you can just import the SoftHSM token database directly into the git tree so everyone tests with precisely the *same* contents. That way you aren't subject to variations in the environment, like this.

**Comment by mouse07410** [comment]
>> The correct assumption based on the current PKCS#11 standard is that CKA_PRIVATE is set on private keys, and is not set on public ones.
>
> Gr, I thought we had dealt with that misunderstanding on your part? That assumption is not based on the PKCS#11 standard. 

It appears that it is - see how v2.40 phrases its description of these flags. But it is more of a suggestion than a requirement. 

> It's perfectly valid for a `CKO_PRIVATE_KEY` object not to have the orthogonal `CKA_PRIVATE` flag set, The PIV token even has such a key; the CARD AUTH key is designed to be used without authentication.

Yes, this is correct. The way I read PKCS#11 v2.40, it says that `CKA_PRIVATE` shouldn't be set for *public* objects. Your example demonstrates that sometimes it makes sense to *not* set `CKA_PRIVATE` even for *private* objects.

**Comment by dwmw2** [comment]
> It appears that it is - see how v2.40 phrases its description of these flags. But it is more of a suggestion than a requirement. 

Haven't we been round this one before? No, the "public objects" and "private objects" in relation to `CKA_PRIVATE` in §4.4 are **ENTIRELY ORTHOGONAL** to the object type. Otherwise the `CKA_PRIVATE` attribute would have been entirely redundant in the first place. As would the note that the default setting is token-specific.

Anyway, that part of the discussion is pointless. As @mtrojnar said, *"The point of testing libp11 is not to find old (already fixed) bugs in its dependencies."*. I'll even let him call it a "bug"; it *was* suboptimal even though it wasn't violating the spec. 

But if the point is not to test the dependencies, then this test case is Doing It Wrong™ because it almost looks like it's deliberately *written* to exercise the dependencies and depend on their precise behaviour!  There are various ways that the test case could avoid being so fragile, and avoid testing the dependencies...
- Importing with `p11tool` or `softhsm2-util` which allow you to explicitly set the `CKA_PRIVATE` state
- Making the test case log in before enumerating public keys
- Keeping the actual SoftHSM2 database in git and referencing it there, instead of creating it afresh for each test run.

Any of those would *stop* this from depending on the surrounding environment, and would actually make it test libp11 alone.

**Comment by mtrojnar** [comment]
What about providing --no-mark-private to `p11tool` when importing public objects?

**Comment by dwmw2** [comment]
Absolutely. That comes under *"• Importing with `p11tool` or `softhsm2-util` which allow you to explicitly set the `CKA_PRIVATE` state."*

In OpenConnect for the simplest unit test I ended up importing the certificate with `p11tool --no-mark-private` and the key with `softhsm2-util`.

I also have test cases where I import the key with `p11tool` and end up without a corresponding EC public key, which crashed OpenSSL for a while (qv). And where I deliberately *do* have `CKA_PRIVATE==CK_TRUE` on the certificate, for testing *that* works nicely in the client too.

And I *also* don't ever run those during the tests; those commands get run locally by *me* and the resulting SoftHSM database files are committed to git, so I really am not depending on the behaviour of any of those tools "in the wild" as they change over time.

Finally, it's trivially fixed just by logging in *before* the call to `PKCS11_enumerate_public_keys()` instead of after it, as I do in https://github.com/dwmw2/libp11/commit/fe1082b7f8ac36196079b4bbafbf42ab79db1d6e

**Comment by mtrojnar** [comment]
> Finally, it's trivially fixed just by logging in before the call to PKCS11_enumerate_public_keys() instead of after it

No.  The test is specifically designed to make sure libp11 can access public keys without logging in.  Your change defeats this purpose.

**Comment by dwmw2** [comment]
Well that *isn't* testing libp11 then. That's *token* behaviour that you're testing.

Right you, you are testing:
- whether `pkcs11-tool` explicitly sets CKA_PRIVATE==CK_FALSE` on imported public keys, and/or
- whether the SoftHSM token sets `CKA_PRIVATE` by default if it isn't explicitly specified.

And *both* of those behaviours have changed recently.

Now, it's OK to test the environment in `make check`. I do it *deliberately* in OpenConnect's tests. I deliberately make it fail if you're using a version of OpenSSL which has broken Cisco DTLS support. I deliberately make it fail if you're using crypto libraries that fail to support certain key types. Because I want the user/packager/builder to *know* that they need to go off and fix those other bugs in the environment, not just ship my application in a form that doesn't work correctly.

And it's also OK, as you suggest, to want to test *only* your own code for regressions. I currently have a *conflict* in my own test suite between these two modes of testing, and I end up deliberately *disabling* certain tests in the CI builds, because they are *known* to fail in, say, CentOS 7, and I don't want that to show up as a regression.

But we really do need to *know* what it is that we want to test, and test that.

As it stands, this test is testing very *little* in libp11 itself, and a *lot* of the behaviour of external tools.

**Comment by mtrojnar** [comment]
Yes, this is precisely why I suggested `--no-mark-private`.

**Comment by dwmw2** [comment]
Right. That's why I suggested it too :)

**Comment by dwmw2** [comment]
Beware I think `pkcs11-tool` doesn't import private keys at all in some cases. That's why I had EC crashes. Maybe `softhsm2-util` is a better choice?

**Comment by mtrojnar** [comment]
Sounds like a good idea.  Please submit a PR.

**Comment by mtrojnar** [comment]
Would you submit a PR to replace `pkcs11-tool` with `softhsm2-util`?

**Comment by dengert** [comment]
Replace??? They can be exist. I have always considered pkcs11-tool
    as a developer test tool, not as a utility for users.  
    
    On 10/5/2016 7:11 AM, Michał Trojnara
      wrote:
    
    
      Would you submit a PR to replace pkcs11-tool with
        softhsm2-util?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/libp11","title":"OpenSC/libp11","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/libp11"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mtrojnar in #116: Would you submit a PR to replace `pkcs11-tool` with `softhsm2-util`?"}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/libp11/issues/116#issuecomment-251656724"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mtrojnar** [comment]
@dengert This discussion is about the tool used in the libp11 testing suite.

**Comment by dengert** [comment]
Sorry.
    
    
    On 10/5/2016 7:43 AM, Michał Trojnara
      wrote:
    
    
      @dengert This discussion is about the
        tool used in the libp11 testing suite.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenSC/libp11","title":"OpenSC/libp11","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenSC/libp11"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mtrojnar in #116: @dengert This discussion is about the tool used in the libp11 testing suite."}],"action":{"name":"View Issue","url":"https://github.com/OpenSC/libp11/issues/116#issuecomment-251663406"}}}
    
    
    -- 

 Douglas E. Engert  <DEEngert@gmail.com>

**Comment by mtrojnar** [comment]
Apparently, nobody is interested in fixing this issue.  I'm closing it.
