### ISSUE TITLE
Current github master fails to load keys

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#118]
Downloaded and configured defaults, see config.log: 
[config.log.txt](https://github.com/OpenSC/libp11/files/509782/config.log.txt)

Builds fine, and `make check` shows all the 5 tests PASSED.

Attempts to use it however fails with "load_private_key:not initialized":
```
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:object=SIGN%20key;object-type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
cannot load key file from engine
140735271227472:error:26096075:engine routines:ENGINE_load_private_key:not initialised:eng_pkey.c:112:
unable to load key file
$ 
```

Notice no prompt for the PIN. I tried to backtrack to the older master - and then I was prompted for the PIN, but still got "unable to load private key".

What changed was the newer release of `p11-kit`. With the older master, the above works if I prefix the command with `PKCS11_MODULE_PATH=/Library/OpenSC/lib/opensc-pkcs11.so`. With the current master it does not help:
```
$ PKCS11_MODULE_PATH=/Library/OpenSC/lib/opensc-pkcs11.dylib openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:object=SIGN%20key;object-type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
cannot load key file from engine
140735271227472:error:26096075:engine routines:ENGINE_load_private_key:not initialised:eng_pkey.c:112:
unable to load key file
$ ll /Library/OpenSC/lib/opensc-pkcs11.dylib
lrwxr-xr-x  1 root  wheel  16 Oct 17  2015 /Library/OpenSC/lib/opensc-pkcs11.dylib@ -> opensc-pkcs11.so
$ ll /Library/OpenSC/lib/opensc-pkcs11.so
-rwxr-xr-x  1 root  wheel  181796 Sep 23 17:31 /Library/OpenSC/lib/opensc-pkcs11.so*
$
```

**Comment by dwmw2** [comment]
I think the 'not initialized' bit is my fault. @mtrojnar should I revert b9b7941765b now that you've worked around it with f160e2f? 

In fact, I can *partially* revert it. All we need to do is provide a default for *something*, and that something can be RSA. You don't need to do the "passthrough" for EC keys too; we don't *need* to register a default method for those.

@mouse07410 I don't expect `pkcs11:object=SIGN%20key;object-type=private` to work when there's more than one token available (which there will be when you're using p11-kit, but not when you're using opensc directly). It needs to know which token to log in to, and you haven't specified.

I'm surprised you say you got a PIN prompt though; I thought we bailed out without trying at all, if we didn't know which token to look harder at. Maybe we choose the *wrong* one?

Try `pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private`

**Comment by mouse07410** [comment]
> I don't expect `pkcs11:object=SIGN%20key;object-type=private` to work when there's more than one token available (which there will be when you're using p11-kit, but not when you're using opensc directly)

I'm not sure I understand. Do you mean "when there's more than one *module* that can handle the token"? Because I (as such is my workflow) never have more than one *token* plugged in.

> I'm surprised you say you got a PIN prompt though; I thought we bailed out without trying at all, if we didn't know which token to look harder at. 

It probably means that whichever module was picked, appears to communicate reasonably successfully with the token?

> Maybe we choose the *wrong* one?

I don't know. I don't think that between the two (OpenSC and YKCS11) there *can* be a "wrong" one because the token is NEO, and both seemed to work with it OK, at least until the recent changes (and that silly MODULUS = 270 bytes thing).

**Comment by mouse07410** [comment]
After reverting b9b7941, I'm getting "incorrect PIN":
```
$ yubico-piv-tool  -a verify-pin -a status
Enter PIN: 
Successfully verified PIN.
CHUID:	3019d4. . . . .
CCC:	f015a0. . . . .
Slot 9a:	
	Algorithm:	RSA2048
. . . . .
Slot 9c:	
	Algorithm:	RSA2048
. . . . .
Slot 9d:	
	Algorithm:	RSA2048
. . . . .
Slot 9e:	
	Algorithm:	RSA2048
. . . . .
PIN tries left:	5
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private;pin-value=xxxxxxxx" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
Error Signing Data
140735271227472:error:800090A0:Vendor defined:PKCS11_rsa_encrypt:PIN incorrect:p11_rsa.c:120:
$ 
```

Here's what PKCS11SPY reveals (my PIN is *not* 5 characters!):
```
84: C_GetAttributeValue
2016-10-05 07:24:23.760
[in] hSession = 0x7f9a58c0b480
[in] hObject = 0x7f9a58c08350
[in] pTemplate[1]: 
    CKA_ALWAYS_AUTHENTICATE  00007f9a58f13eb0 / 1
[out] pTemplate[1]: 
    CKA_ALWAYS_AUTHENTICATE  True
Returned:  0 CKR_OK

85: C_SignInit
2016-10-05 07:24:23.761
[in] hSession = 0x7f9a58c0b480
pMechanism->type=CKM_RSA_X_509                
[in] hKey = 0x7f9a58c08350
Returned:  0 CKR_OK

86: C_Login
2016-10-05 07:24:23.761
[in] hSession = 0x7f9a58c0b480
[in] userType = CKU_CONTEXT_SPECIFIC
[in] pPin[ulPinLen] 00007fff51dd0560 / 5
    00000000  XX XX XX XX XX                                  `....           
Returned:  160 CKR_PIN_INCORRECT
Error Signing Data
140735271227472:error:800090A0:Vendor defined:PKCS11_rsa_encrypt:PIN incorrect:p11_rsa.c:120:

87: C_CloseAllSessions
2016-10-05 07:24:23.784
[in] slotID = 0x0
Returned:  0 CKR_OK

88: C_Finalize
2016-10-05 07:24:23.784
Returned:  0 CKR_OK
```

**Comment by dwmw2** [comment]
I mean that `p11tool --list-tokens` shows more than one. It doesn't matter that some are pure software trust tokens, and the two the *are* real hardware are actually the *same* hardware through two different providers. There's more than one possibility, and we aren't about to go logging into them *all* to see which one has what we want.

**Comment by dwmw2** [comment]
Hm.... do we blame recent PIN handling changes? What happens if you leave out the `pin-value=` and let it prompt you?

**Comment by mouse07410** [comment]
> do we blame recent PIN handling changes?

I certainly do.

> What happens if you leave out the `pin-value=` and let it prompt you?

Same thing, of course:
```
$ PKCS11_MODULE_PATH=/Library/OpenSC/lib/pkcs11-spy.dylib openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
. . . . .
86: C_Login
2016-10-05 07:34:35.176
[in] hSession = 0x7fa191501fb0
[in] userType = CKU_CONTEXT_SPECIFIC
[in] pPin[ulPinLen] 00007fff5aeb8570 / 5
    00000000  60 CB FD 04 01                                   `....       [note: this appears to be random data]   
Returned:  160 CKR_PIN_INCORRECT
Error Signing Data
140735271227472:error:800090A0:Vendor defined:PKCS11_rsa_encrypt:PIN incorrect:p11_rsa.c:120:

87: C_CloseAllSessions
2016-10-05 07:34:35.201
[in] slotID = 0x0
Returned:  0 CKR_OK

88: C_Finalize
2016-10-05 07:34:35.201
Returned:  0 CKR_OK
```

More invocations of the same command:
```
[in] pPin[ulPinLen] 00007fff5a386570 / 5
    00000000  60 BB B0 05 01 
. . . . .
[in] pPin[ulPinLen] 00007fff5f9ab570 / 3
    00000000  60 5B 4E                                         `[N 
. . . . .
[in] pPin[ulPinLen] 00007fff5101b570 / 5
    00000000  60 9B E7 0E 01                                   `....           
Returned:  160 CKR_PIN_INCORRECT
. . . . .
```

I guess I don't need to state that I do type in my PIN correctly?

**Comment by mtrojnar** [comment]
@dwmw2 Yes, please revert https://github.com/OpenSC/libp11/commit/b9b7941765b7d6cd4c0d003b53b9d44801179ebe.  This seems to be what OpenSSL expects from its engines.

**Comment by mouse07410** [comment]
Reverting b9b7941 seems necessary but insufficient, as the above logs show.

**Comment by dwmw2** [comment]
The PIN thing is a separate issue to the default-method thing.
