### ISSUE TITLE
Different names for the keys

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#120]
To my (very unpleasant) surprise, I found that listing keys with different providers "provide" totally different names, making it impossible to use the same `object=` clause to address them meaningfully. OpenSC lists them as `SIGN%20key`, `SIGN%20pubkey`, and such. YKCS11 lists them as `Private%20key%20for%20Digital%20Signature%00`, etc...

```
$ p11tool --provider /usr/local/lib/libykcs11.dylib --list-privkeys --login
Token 'YubiKey PIV' with URL 'pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%00;object=Private%20key%20for%20PIV%20Authentication%00;type=private
	Type: Private key
	Label: Private key for PIV Authentication
	Flags: CKA_PRIVATE; 
	ID: 00

Object 1:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%01;object=Private%20key%20for%20Card%20Authentication%00;type=private
	Type: Private key
	Label: Private key for Card Authentication
	ID: 01

Object 2:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%02;object=Private%20key%20for%20Digital%20Signature%00;type=private
	Type: Private key
	Label: Private key for Digital Signature
	Flags: CKA_PRIVATE; 
	ID: 02

Object 3:
	URL: pkcs11:model=YubiKey%20NEO;manufacturer=Yubico;serial=1234;token=YubiKey%20PIV;id=%03;object=Private%20key%20for%20Key%20Management%00;type=private
	Type: Private key
	Label: Private key for Key Management
	Flags: CKA_PRIVATE; CKA_ALWAYS_AUTH; 
	ID: 03

$ p11tool --provider /Library/OpenSC/lib/opensc-pkcs11.dylib --list-privkeys --login
Token 'PIV Card Holder pin (PIV_II)' with URL 'pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29' requires user PIN
Enter PIN: 
Object 0:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%01;object=PIV%20AUTH%20key;type=private
	Type: Private key
	Label: PIV AUTH key
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 01

Object 1:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%02;object=SIGN%20key;type=private
	Type: Private key
	Label: SIGN key
	Flags: CKA_PRIVATE; CKA_ALWAYS_AUTH; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 02

Object 2:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%03;object=KEY%20MAN%20key;type=private
	Type: Private key
	Label: KEY MAN key
	Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 03

Object 3:
	URL: pkcs11:model=PKCS%2315%20emulated;manufacturer=piv_II;serial=4ffxxxxx;token=PIV%20Card%20Holder%20pin%20%28PIV_II%29;id=%04;object=CARD%20AUTH%20key;type=private
	Type: Private key
	Label: CARD AUTH key
	Flags: CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
	ID: 04

$
```

Who is in position to reduce these two naming styles to one?  *I'm aware of the workaround - like using* `id=%02`, *but would prefer to be able to use a more "visual" name, like* `SIGN%20key`.

I reported this here as well: https://github.com/Yubico/yubico-piv-tool/issues/100

*Wonder if there's any reward for reporting issue number 100.* :-)

**Comment by mtrojnar** [comment]
Shouldn't this issue be opened in https://github.com/OpenSC/OpenSC rather than https://github.com/OpenSC/libp11 ?

**Comment by dwmw2** [comment]
Yes. And in fact since OpenSC's use of ID and labels is long-established and YKCS11 doesn't even work yet, better just to file on that side anyway.

**Comment by dengert** [comment]
As you are referring to using a PIV applet, NIST does not talk about PKCS#11 at all.  The closest thing to a label is in Table 2 in 800-73-3_part1 and this is for the objects, which do not include private keys.
And many CAC cards also have a PIV applet. 

OpenSC and YKCS11 are not the only PKCS#11. There is at least coolkey, ActivCard and Thursby. 
So the PKCS#11 label values are left up to the vendor of the PKCS#11 module.

**Comment by mouse07410** [comment]
You are correct. However, the point is - it is desirable to be able to access keys in a consistent interoperable way across different PKCS#11 libraries, so that, for example, scripts don't have to be re-written or excessively parametrized for every library possibly in use.

Yes there are other players/libraries besides OpenSC and YKCS11. Few of them are cross-platform, AFAIK. Coolkey hasn't been maintained or updated for a long time. Same with CACKey. ActivCard (as far as I know) is Windows-only. Thursby is current, but Mac-only. Etc...

So while the label values are left up to the vendor - the community can (and should) at least try to get some consistency there.

**Comment by dengert** [comment]
Good luck. You might have a chance with OpenSC an YPKCS11.

**Comment by mouse07410** [comment]
> You might have a chance with OpenSC and YPKCS11.

Thank you. Right now OpenSC is (mostly) production-ready, and YKCS11 being so young might be willing to adopt. 

I don't think any others that you mentioned actually satisfy these two conditions: (a) are current, and (b) provide a working PKCS#11 library (let alone cross-platform PKCS#11 library).
