### ISSUE TITLE
Issue trying to retrieve private key with libp11 (but works with engine module)

### ISSUE THREAD

**Issue by filip-andrei** [OpenSC/libp11#124]
I'm trying to retrieve a certificate and private key from a smartcard to use with an ssl connection but the  connection seems to work only when retrieving the private key with the engine module and fails when using p11.

I've posted my problem in further detail on stackoverflow at http://stackoverflow.com/questions/40083317/differences-in-reading-private-key-with-libp11-and-pkcs11-engine

**Comment by mtrojnar** [comment]
Please submit a small application that reproduces this issue.

**Comment by filip-andrei** [comment]
Oops, forgot to close this. I figured out the issue in the mean time. The problem was that i was initializing the engine with our own dll implementing pkcs11 (which probably does some extra magic with company smartcards) and then libp11 using the opensc dll (because i copy paste code without looking like that :(  )
