### ISSUE TITLE
Current master broke key access

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#143]
Now it again requests PIN for **public** keys:

```
Signing file /tmp/derive.62637.text...
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out /tmp/derive.62637.text.sig /tmp/derive.62637.text
engine "pkcs11" set.
PKCS#11 token PIN: 
Signature is stored in /tmp/derive.62637.text.sig

Verifying signature:
openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=public" -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature /tmp/derive.62637.text.sig  /tmp/derive.62637.text
engine "pkcs11" set.
PKCS#11 token PIN: 
Verified OK

$ 
```

@mtrojnar I'd **greatly** appreciate if you could revert the key access functionality to what it was before (PIN required for private key operations, **no** PIN required for public key access).

I suspect 7a70969, though 4303db5 could have contributed too.

**Comment by mtrojnar** [comment]
So we currently **never** login to access a public key, an **always** login to access a certificate (also generally public).  I think this decision (for both certificates and public keys) should somehow be based on their CKA_PRIVATE attribute.

I think the proper approach should be:
1. Try finding the required object (a certificate or a public key) without login.
2. If it fails, login and try again.

What do you think?  This would actually be very simple to implement.

**Comment by mouse07410** [comment]
> So we currently **never** require login to access a public key,

**Good!**

>  and always require login to access a certificate (also generally public).

**Bad!**  I think we've been through this discussion already. And a similar one - with SoftHSMv2 folks, who agreed that certificates must be public unless explicitly marked otherwise (which occasionally does happen - but is very rare).

> I think this decision (for both certificates and public keys) should somehow be based on their `CKA_PRIVATE` attribute.

Absolutely. That's the purpose of that attribute, after all - to tell whether the object requires authorization to be accessed, or not.

> I propose the following solution:
> 
> 1. Try finding the required object (a certificate or a public key) without login.
> 2. If it fails, login and try again.
>
> What do you think? This would actually be very simple to implement.

I think it makes perfect sense. And the sooner - the better.

I also must say that until this is done/fixed (because I consider forcing login to access certificates as a bug), I am unable to use `libp11` past commit b514cdfcd7025ec902292393e675573170d7fc9b.

**Comment by mtrojnar** [comment]
I'm pretty sure
`$ openssl cms -engine pkcs11 -verify -in random_msg.out -signer "pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert" -out random_msg.ver -CAfile ~/Documents/Certs/forest_ca_rsa_4.pem -text`
simply verifies the signature with a certificate specified in `-CAfile`. :smile:

In fact, OpenSSL commandline tools never really access PKCS#11 certificate, as AFAIK there is no standard way for OpenSSL to retrieve a certificate (except for TLS client certificates) from an engine.
Third party apps download a certificate with the non-standard `LOAD_CERT_CTRL` engine ctrl.  OpenSSL commandline tools don't support it.

**Comment by mtrojnar** [comment]
> > So we currently never require login to access a public key,

> Good!

Not really good.  Some people *may* (for whichever strange reason) use public keys with the CKA_PRIVATE attribute.

**Comment by mouse07410** [comment]
> ...simply verifies the signature with a certificate specified in `-CAfile`. 😄

You're right! :-(
```
$ openssl cms -verify -in random_msg.out -out random_msg.ver -CAfile ~/Documents/Certs/forest_ca_rsa_4.pem -text 
Verification successful
$ 
```

> Some people _may_ (for whichever strange reason) use public keys with the CKA_PRIVATE attribute.

Yes, you're correct. But there's more to it: some **private** keys require **PIN-less** access (i.e., without logging in to the token first). One example that's in the standard is `CARD Auth key`, which is supposed to be used in applications like badge-reader, physical access to premises, etc. This escaped me because all of **my** applications use only the other three keys...

I think we need to accommodate both cases: public keys and certs labeled `CKA_PRIVATE`, and private keys that do not require login for operations. And I think the solution you proposed should work for both cases.

Comments?

**Comment by mouse07410** [comment]
@mtrojnar I'd also like your help on a related issue (which probably is not a `libp11` bug, but I don't know what to do).

I'm putting all this smartcard-related stuff on a new MacBook Pro running macOS Sierra 10.12.2. So far so good - OpenSC seems to work, tokens seems to work... But OpenSSL with `libp11` is unable to access keys (any keys) on the smart card. Here's an example:
```
$ openssl dgst -engine pkcs11 -keyform engine -sign id_02 -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
No private keys found.
PKCS11_get_private_key returned NULL
cannot load key file from engine
140736401261576:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load key file
$ openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=public" -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature t256.dat.sig  t256.dat
engine "pkcs11" set.
Specified object not found
PKCS11_load_public_key returned NULL
unable to load key file
$ 
```

My attempts to set `PKCS11LIB=/Library/OpenSC/lib/pkcs11-spy.so` and `PKCS11SPY=/Library/OpenSC/lib/opensc-pkcs11.so` and do
```
$ export PKCS11LIB=/Library/OpenSC/lib/pkcs11-spy.so
$ echo $PKCS11SPY
/Library/OpenSC/lib/opensc-pkcs11.dylib
$ OPENSC_DEBUG=9 openssl dgst -d -engine pkcs11 -keyform engine -sign id_02 -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
No private keys found.
PKCS11_get_private_key returned NULL
cannot load key file from engine
140736401261576:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load key file
BIO[0x7febcbf003a0]: Free - FILE pointer
$ 
```
failed to produce any usable (or even extensive) trace...

OpenSC seems to work:
```
$ opensc-tool -ani
OpenSC 0.16.0 [gcc  4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Enabled features: locking zlib readline openssl pcsc(/System/Library/Frameworks/PCSC.framework/PCSC)
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
3b:f8:13:00:00: . . . . .
PIV-II card
$ $ pkcs11-tool -sign -d 02 -m SHA256-RSA-PKCS -i t256.dat -o t256.dat.sig
Using slot 0 with a present token (0x0)
Logging in to "PIV Card Holder pin (PIV_II)".
Please enter User PIN: 
Using signature algorithm SHA256-RSA-PKCS
$ pkcs15-tool --read-public-key 02 > signer.pem
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
$ less signer.pem 
$ openssl dgst -verify signer.pem -signature t256.dat.sig t256.dat
Verified OK
$ 
```

**Comment by mtrojnar** [comment]
Try reading certificates without login (if possible): https://github.com/OpenSC/libp11/commit/c6f74273b751b745eb25466e5c4c184e8bc5533f

**Comment by mouse07410** [comment]
Not sure:
```
$ openssl rand -out t256.dat 32
$ openssl pkeyutl -engine pkcs11 -keyform engine -sign -inkey "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -in t256.dat -out t256.dat.sig
engine "pkcs11" set.
PKCS#11 token PIN: 
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -certin -inkey "pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert" -sigfile t256.dat.sig -in t256.dat
engine "pkcs11" set.
Error opening Certificate pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert
140736234779656:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert','r')
140736234779656:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load certificate
Error initializing context
$ echo $PKCS11LIB

$ export PKCS11LIB=/opt/local/lib/p11-kit-proxy.
p11-kit-proxy.dylib  p11-kit-proxy.so     
$ export PKCS11LIB=/opt/local/lib/p11-kit-proxy.dylib 
$ openssl pkeyutl -engine pkcs11 -keyform engine -verify -certin -inkey "pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert" -sigfile t256.dat.sig -in t256.dat
engine "pkcs11" set.
Error opening Certificate pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert
140736234779656:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('pkcs11:manufacturer=piv_II;object=Certificate%20for%20Digital%20Signature;type=cert','r')
140736234779656:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load certificate
Error initializing context
$ $ pkcs15-tool -c
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
X.509 Certificate [Certificate for PIV Authentication]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 
	ID             : 01
	Encoded serial : 02 . . . . .

X.509 Certificate [Certificate for Digital Signature]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 
	ID             : 02
	Encoded serial : 02 . . . . .

X.509 Certificate [Certificate for Key Management]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 
	ID             : 03
	Encoded serial : 02 . . . . .

X.509 Certificate [Certificate for Card Authentication]
	Object Flags   : [0x0]
	Authority      : no
	Path           : 
	ID             : 04
	Encoded serial : 02 . . . . .

$
```

1. Would you have a recommendation how to test certificate access? Maybe even a command line example?
2. Would you have any advice for me how to debug and get OpenSSL/libp11 working on that new machine? I have an older Mac that also runs Sierra 10.12.2, and libp11 seems to work perfectly OK there. The new system is pristine - not much installed on it yet...

**Comment by dengert** [comment]
What version of OpenSSL are you using?  

Was there any version of pkeyutl that worked for you?

Based on the error message, fopen is failing to find a file. 

In 1.0.2 apps/pkeyutl.c, calls load_cert in apps.c, and passes in the engine, but load_cert does not use the engine parameter at all and just uses BIO_read_filename(cert, file) that calls fopen to look for a file.
 
Looks like 1.1.0c is worse. pkeyutl.c does not passin the engine parameter when calling load_cert, and load_cert does not accept an engine parameter.  
You may have to read the cert using some OpenSC tool and save as file first.

**Comment by dengert** [comment]
But in the other hand, if you can use the -pubin parameter, rather then the -certin, and change the URI as needed, it looks like that will call the engine.  (The OpenSC PIV driver presents the pubkey from the certificate to PKCS\#11)

**Comment by mouse07410** [comment]
> What version of OpenSSL are you using?

OpenSSL-1.0.2j on both machines.

> Was there any version of pkeyutl that worked for you?

Not for certificates. 

Maybe I need to look at the OpenSSL source and prepare a patch, like I did for the private and public keys...?

> But in the other hand, if you can use the -pubin parameter, rather then the -certin, and change the URI as needed, it looks like that will call the engine.

Yeah, that would work, thanks.

By the way, would you have any recommendation for this https://github.com/OpenSC/libp11/issues/143#issuecomment-272530530 problem? I'm provisioning a brand new MacBook Pro running MacOS Sierra 10.12.2, and OpenSSL/libp11 just refuse to access the hardware token no matter what (no pubkey, no private key, nothing). This same code works fine on my older Mac that also runs MacOS Sierra 10.12.2... I don't know what to do, or where to look...

**Comment by mtrojnar** [comment]
> Would you have a recommendation how to test certificate access? Maybe even a command line example?

My recommendation is quite obviously stunnel.

stunnel.conf needs to be something like:

    engine = pkcs11
    engineCtrl = MODULE_PATH:opensc-pkcs11.so

    [service]
    engineId = pkcs11
    cert = pkcs11:<...>
    accept = <port>
    connect = <host>:<port>

  I need to update the pkcs11 example in the manual...

**Comment by dwmw2** [comment]
Slight digression...

> engine = pkcs11 
> engineCtrl = MODULE_PATH:opensc-pkcs11.so

That shouldn't be necessary in a well-behaved system (at least Linux) because it should be using p11-kit-proxy.so by default and thus using the system-configured providers automatically.

> [service]
> engineId = pkcs11

And in an ideal world, that shouldn't be necessary either. If the cert field starts 'pkcs11:' then the engine could be used automatically.

> cert = pkcs11:<...>
> accept = <port>
> connect = <host
>:<port>

Ideally, *all* you should need to do (in any application) is replace the cert filename with a PKCS#11 URI.

**Comment by mtrojnar** [comment]
> That shouldn't be necessary in a well-behaved system (at least Linux)

In an ideal world — yes.  My points are:
1. The world is not ideal and stunnel is not limited to well-behaved systems: https://www.stunnel.org/ports.html
2. It would be a very bad idea to implement this in stunnel (vide: KISS principle).  Instead, automagic handling of engines with URI paths should be added to OpenSSL.

Feel free to submit a PR to https://github.com/openssl/openssl

**Comment by mtrojnar** [comment]
@mouse07410 Could you check whether https://github.com/OpenSC/libp11/commit/c7faf10cde39d31f16fb69985cbfaed20e4b81d1 works for you?

**Comment by dwmw2** [comment]
> 1. The world is not ideal and stunnel is not limited to well-behaved systems: https://www.stunnel.org/ports.html

True. But even without being system-specific, the engine does now have support for being used with a 'default' PKCS#11 module. So anything which can use the engine should now ensure that the 'MODULE_PATH' option is *optional* in its own configuration, not required. That's already true in stunnel anyway, right?

> 2. It would be a very bad idea to implement this in stunnel (vide: KISS principle). Instead, automagic handling of engines with URI paths should be added to OpenSSL.

That would indeed be nice. However, we're a long way from that. OpenSSL even forces apps to jump through insane hoops just to support different types of *files*. I *am* tilting at that windmill, but it's going to take some time — and my new job means that I've got a bit less time to spend on it. In the meantime, it seems reasonable for apps *just* to spot a cert/key "filename" starting with `pkcs11:` and have a special-case to load engine_pkcs11. 

But again, this is a digression; we should take it elsewhere perhaps.

**Comment by mouse07410** [comment]
> My recommendation is quite obviously stunnel.

My problem with that is I don't have stunnel currently deployed anywhere...

I think that until OpenSSL is smart enough to do the URI stuff, the engine got to pick up the slack.

I will try to patch OpenSSL to add cert loading support, and/or add cert retrieval to one of my test-apps (that already exists, already works with the engine, and does not need anything extra deployed or configured).

**Comment by mtrojnar** [comment]
Sure.  stunnel's code is quite simple:
```C
NOEXPORT int load_cert_engine(SERVICE_OPTIONS *section) {
    struct {
        const char *id;
        X509 *cert;
    } parms;

    s_log(LOG_INFO, "Loading certificate from engine ID: %s", section->cert);
    parms.id=section->cert;
    parms.cert=NULL;
    ENGINE_ctrl_cmd(section->engine, "LOAD_CERT_CTRL", 0, &parms, NULL, 1);
    if(!parms.cert) {
        sslerror("ENGINE_ctrl_cmd");
        return 1; /* FAILED */
    }
    if(!SSL_CTX_use_certificate(section->ctx, parms.cert)) {
        sslerror("SSL_CTX_use_certificate");
        return 1; /* FAILED */
    }
    s_log(LOG_INFO, "Certificate loaded from engine ID: %s", section->cert);
    return 0; /* OK */
}
```

**Comment by mouse07410** [comment]
Thank you! Might I ask you to look at "Key not found" message - I think it's printed inappropriately (yes, the requested key was not found *without* the PIN, which was/should-be expected by user - so no need to scare him with that), and I will try to add your code sample to my app and report later today or early tomorrow. 

Question: what is `section->cert`? An URI pointing at the requested cert, or...?

**Comment by mtrojnar** [comment]
> Question: what is section->cert? An URI pointing at the requested cert, or...?

Yes, either URI or the the obsolete object ID format (for example "id_45").

**Comment by mtrojnar** [comment]
> I don't have stunnel currently deployed anywhere

It is actually not very hard...
```sh
sudo apt-get install stunnel4
sudo pacman -S stunnel
sudo port install stunnel
```
Maybe a little bit harder on systems without a package manager (like Windows).

**Comment by mouse07410** [comment]
I currently have no application for `stunnel`, and don't even know how to use it. Installing `stunnel` is not difficult, but keeping a tool I've no clue about doesn't seem productive - I won't be able to test it (or with it) very well.

Certificate loaded fine, but of course I have no SSL_CTX to actually `SSL_CTX_use_certificate(ssl_ctx, parms.cert);` so I was unable to properly test that part.

**Summary:** keys and certificates appear to be loading fine. Message "Key not found" seems misplaced, and should be either conditional (cannot find the key that URI asked for even after promping for the PIN), or removed from there (IMHO).

**Comment by mtrojnar** [comment]
> Message "Key not found" seems misplaced

Confirmed.  I is also not needed.  I'll remove it entirely.

**Comment by mouse07410** [comment]
> Confirmed. I is also not needed. I'll remove it entirely.

Thanks!  

Or maybe:
```
diff --git a/src/eng_back.c b/src/eng_back.c
index a88b90c..4e1f81a 100644
--- a/src/eng_back.c
+++ b/src/eng_back.c
@@ -807,7 +807,8 @@ static EVP_PKEY *ctx_load_key(ENGINE_CTX *ctx, const char *s_slot_key_id,
                        PKCS11_get_private_key(selected_key) :
                        PKCS11_get_public_key(selected_key);
        } else {
-               fprintf(stderr, "Key not found.\n");
+               if (login)
+                       fprintf(stderr, "Key not found.\n");
                pk = NULL;
        }
        if (key_label != NULL)
```

**Comment by mouse07410** [comment]
@mtrojnar does the above suggestion make sense? Inform the user if the key he wants cannot be found even when the token is logged in, but otherwise don't tell him that key is not there?

**Comment by mtrojnar** [comment]
> does the above suggestion make sense?

Yes, it does.  In fact, this is what I committed ~2 hours before your post. https://github.com/OpenSC/libp11/commit/8ac8657710370e3e838d2ef2ff09ef0e787b6c0f

**Comment by mouse07410** [comment]
Thank you! ;-)
