### ISSUE TITLE
Support loading keys generated out-of-band from libp11 for long-running process

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#144]
Situation: using libp11 in a long-running server process, into which we want to add support for key rotation at some kind of regular interval. This could mean either (1) the HSM admin generates a new key themselves out of band, or (2) the server programmatically generates a new key. (Note: since libp11 does not generate keys on the token (see #53), we have to call out to the pkcs11 api directly to do this, which is what makes this also out-of-band; in addition, the key generation functions appear to be marked deprecated in libp11, otherwise I might submit a PR for #53...).

Looking at `pkcs11_enumerate_keys`, it appears that it only ever caches the list of keys _once_ per token, and the only way to flush / repopulate that cache is by `pkcs11_destroy_keys`, which would seem to invalidate key objects already present in memory and in use. 

Having a cache seems like a good idea but there needs to be a fallback, in my opinion, on a cache miss that either (1) adds all newly found keys to the cache (probably leaving the old ones as-is), or else (2) just appends the one newly-found key to the cache.

**Comment by mtrojnar** [comment]
I think the proper solution would be to update `PKCS11_enumerate_keys()`, `PKCS11_enumerate_public_keys()`, and `PKCS11_enumerate_certs()` so that they only add newly discovered keys/certs without invalidating the existing `PKCS11_KEY`/`PKCS11_CERT` objects.  What do you think?

The engine would also benefit from such change.

**Comment by matthauck** [comment]
That would work, but always updating them to look for new keys would miss out on some the benefits of caching, no?

**Comment by mtrojnar** [comment]
As far as I understand, the idea was to keep track of and to reuse previously allocated objects.  Reducing the number of object list retrievals was a side affect rather than the intended goal.

**Comment by matthauck** [comment]
Ah, that makes sense -- more for memory management than for actual caching.

**Comment by mtrojnar** [comment]
Implemented: https://github.com/OpenSC/libp11/commit/9bbdd805fc8a8aef902bdf376504cb0a7472ac3f

**Comment by matthauck** [comment]
Great, thanks! 👍
