### ISSUE TITLE
Expose a way to set the UI_METHOD for a engine-loaded private key

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#146]
See discussion: https://github.com/OpenSC/libp11/commit/be22da7#commitcomment-20772428

**Comment by mtrojnar** [comment]
Implemented: https://github.com/OpenSC/libp11/commit/ef756be48e7b920eb2d809ba23a6bb06c1571bf9

**Comment by matthauck** [comment]
This can probably be closed now, right?

**Comment by mtrojnar** [comment]
You requested this feature, so I presume you can confirm that it works as you expected.  I would appreciate your test results.

**Comment by matthauck** [comment]
Sorry, been tied up with other things. Getting around to testing this shortly.

**Comment by matthauck** [comment]
Hmm. Sadly there does not appear to be enough information in the UI prompt to decide which PIN to use: [p11_key.c#L365-L369](https://github.com/OpenSC/libp11/blob/ef756be48e7b920eb2d809ba23a6bb06c1571bf9/src/p11_key.c#L365-L369)

We need to be able to support keys from different slots, which may each have different PINs. Ideally, the prompt would print out the key URI or something so that the consumer would know which PIN to provide.

**Comment by mtrojnar** [comment]
Doesn't the user already know the selected key from the calling application?

Otherwise, it would be nice to have some form of key identifier in the UI prompt.

**Comment by matthauck** [comment]
well, the engine interface only allows specifying one UI method, whereas the ENGINE_load_private_key openssl calls allows for different pins for different keys (i.e slots).

**Comment by mtrojnar** [comment]
Does this issue affect your deployment?

**Comment by matthauck** [comment]
Yes. We have multiple keys that we load from different slots.

**Comment by mtrojnar** [comment]
What does your application do?  Couldn't it display a message to the user before a private key is used?

**Comment by matthauck** [comment]
I think there's a bit of misunderstanding here. When libp11 needs the `CKU_CONTEXT_SPECIFIC` pin for a particular key (when there are, say, 2 keys in use), it calls out to the singleton UI_METHOD I've specified via the engine api, how do I as the application know which key/slot this pin is for? The application can know both pins, and which pin is for which key, but the UI* is not passing enough information for the application to know which pin is being requested. 

Does that make sense?

**Comment by mtrojnar** [comment]
Yes, it does.  I'm trying to understand the specific application that randomly makes signatures with two separate private keys on two separate tokens that both use `CKU_CONTEXT_SPECIFIC` PINs.

**Comment by matthauck** [comment]
not so much "randomly" as in different contexts / threads. Even if they were synchronized, are you suggesting we could re-run the engine control commands to set the UI_METHOD to the one we wanted to use at that moment and then unset afterwards or something?

**Comment by mtrojnar** [comment]
Maybe something simpler, like loading a separate instance of the pkcs11 engine for each thread?

**Comment by matthauck** [comment]
Revisiting this discussion. I put up a PR suggesting a possible change to the UI that prints out more information to allow the user to decide which PIN to provide without spitting out a big ugly pkcs11 key URI. Hopefully this is a good middle ground, and I think is probably sufficient data for my use case as well.
