### ISSUE TITLE
Segfault using keys via engine API after having re-enumerated keys 

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#150]
Consider the following scenario:
1. Generate a key in one's pkcs11 module
2. Load the key via the openssl engine api and keep a reference around
3. Generate a new key in your pkcs11 module
4. Load that new key via the openssl engine api
5. Try to use the first key to do something with openssl 
--> 💣  _segfault_. 

It turns out the bug is due to the `OPENSSL_realloc` in p11_key.c and p11_cert.c and the fact that the `PKC11_KEY*` pointer is stored on the `EVP_PKEY`'s ex_data. Because the "enumerate_keys" and "enumerate_certs" APIs depend on returning a contiguous array of keys/certs (instead of a linked list), it has to realloc the memory, and thus shift the location of the object in memory. 

The best solution to this seems to me to use a linked list instead of an array, but that ship has probably sailed. The next best thing would perhaps to be to try to update all the ex_data's on all known `EVP_PKEY`s whenever we have to realloc?

Note: This behavior was introduced in 9bbdd805fc8a8aef902bdf376504cb0a7472ac3f, which (thankfully!) added support for adding new keys to the list of keys *post* initial search. Since it previously wouldn't search after any keys were loaded, this behavior wouldn't be seen. Next step to finish up that commit is to fix the implications of this realloc.

**Comment by matthauck** [comment]
Actually, I'm not sure this affects p11_cert.c or not. Can't seem to find any places those pointers are stored off anywhere.

**Comment by matthauck** [comment]
Put up a proposed fix: #151.

**Comment by matthauck** [comment]
Cool, thanks for pulling that in. Is it correct that there are no places where cert pointers get cached like these key ones were?

**Comment by mtrojnar** [comment]
Yes, we just keep the certs themselves, and not their engine references.
