### ISSUE TITLE
Fails to produce X9.31 signature?

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#158]
Console:
```
$ PKCS11_MODULE_PATH=/Library/OpenSC/lib/pkcs11-spy.so PKCS11SPY_OUTPUT=~/libp11-x931-spy1.txt openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha1 -sigopt rsa_padding_mode:x931 -sigopt digest:sha1 -out t256.dat.sig t256.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for PIV Card Holder pin (PIV_II):
Enter PKCS#11 key PIN for SIGN key:
Error Signing Data
140736466609160:error:80009091:Vendor defined:PKCS11_rsa_encrypt:Operation not initialized:p11_rsa.c:120:
$ 
```

SPY:
```
. . . . .
100: C_GetAttributeValue
2017-05-01 19:29:36.067
[in] hSession = 0x7fb951e0c4b0
[in] hObject = 0x7fb951e08de0
[in] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  00007fb951d13820 / 1
[out] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  True
Returned:  0 CKR_OK

101: C_SignInit
2017-05-01 19:29:36.067
[in] hSession = 0x7fb951e0c4b0
pMechanism->type=CKM_RSA_X9_31
[in] hKey = 0x7fb951e08de0
Returned:  112 CKR_MECHANISM_INVALID
. . . . .
```

The problem is either with `libp11` trying to offload the padding to the card, or with OpenSSL-1.0.2k trying to do the same. The expected result would be OpenSSL applying the padding and passing the (raw) RSA operation to the token.

P.S. PKCS1 and PSS paddings work fine:
```
$ openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha1 -sigopt rsa_padding_mode:pss -out t256.dat.sig t256.dat
engine "pkcs11" set.
Enter PKCS#11 token PIN for PIV Card Holder pin (PIV_II):
Enter PKCS#11 key PIN for SIGN key:
$
```

**Comment by dengert** [comment]
@mouse07410 
OpenSC does not support CKM_RSA_X9_31 and does not support PSS. So somewhere the PSS padding is being added. A spy traces requesting PSS  and PKCS1 would be helpful to determine where the padding is being done. 

Also a debug stack trace showing how to C_SignInit was called with CKM_RSA_X9_31 would also be helpful to see where the engine could have done the padding.


But you also said: "The expected result would be OpenSSL applying the padding and passing the (raw) RSA operation to the token." But many tokens do not support (raw) RSA, so there would need to be a lot more logic in libp11 and the engine to determine if the PKCS\#11 module supports CKM_RSA_X9_31 or CKM_RSA_X_509. 

Do you really plan to use X9.31 padding?

The ASNI X9.31  padding could be added to OpenSC, and source code modifications are welcome.

**Comment by mouse07410** [comment]
> OpenSC does not support CKM_RSA_X9_31 and does not support PSS. 

Yep. And it doesn't support OAEP. All of which would be nice to have there, but as long as OpenSSL and libp11 are around, it's no big deal.

> So somewhere the PSS padding is being added.

Yep. That somewhere is OpenSSL. Same for PSS, same for OAEP.

> But you also said: "The expected result would be OpenSSL applying the padding and passing the (raw) RSA operation to the token." But many tokens do not support (raw) RSA, so there would need to be a lot more logic in libp11 and the engine to determine if the PKCS#11 module supports CKM_RSA_X9_31 or CKM_RSA_X_509.

I think I see your point. It looks like Yubikey supports `CKM_RSA_X_509` and `CKM_RSA_PKCS`. I think I recall that `CKM_RSA_X_509` is essentially the raw RSA, which enables OpenSSL to correctly add the required padding (RSASSA-PSS in this case).

> Do you really plan to use X9.31 padding?

Well... frankly, honestly? I don't think so. Been using PKCS1, and we've practically moved to PSS. I run PSS without a hitch, thanks to OpenSC, libp11, and OpenSSL.

But if it's a small bug of omission - something somewhere in libp11 is not set that should've told OpenSSL "you do this padding", then it might be a good idea to fix. Especially since OpenSSL by itself does X9.31 padding just fine:
```
$ openssl dgst -keyform DER -sign rsa2048priv.der -sha256 -sigopt rsa_padding_mode:x931 -out t256.dat.sig t256.dat
$ openssl dgst -keyform DER -sha256 -verify rsa2048pub.der -sigopt rsa_padding_mode:x931 -signature t256.dat.sig t256.dat
Verified OK
$ 
```

> A spy traces requesting PSS and PKCS1 would be helpful to determine where the padding is being done.

In case of PSS, spy trace shows that libp11/OpenSSL combination is smart enough not to bug the token with something it 99.9999% likely won't be able to do:  
[pss-spy1.txt](https://github.com/OpenSC/libp11/files/972234/pss-spy1.txt)


So it merely asks for `CKM_RSA_X_509`, which it gets:
```
101: C_SignInit
2017-05-02 20:04:22.330
[in] hSession = 0x7f7f60614450
pMechanism->type=CKM_RSA_X_509
[in] hKey = 0x7f7f60426a60
Returned:  0 CKR_OK
```

In case of X9.31 it asks for `CKM_RSA_X9_31`, which it certainly doesn't get:
```
101: C_SignInit
2017-05-02 20:10:38.999
[in] hSession = 0x7fdbf6f13e20
pMechanism->type=CKM_RSA_X9_31
[in] hKey = 0x7fdbf6c21830
Returned:  112 CKR_MECHANISM_INVALID

102: C_Login
2017-05-02 20:10:40.917
[in] hSession = 0x7fdbf6f13e20
[in] userType = CKU_CONTEXT_SPECIFIC
[in] pPin[ulPinLen] 00007fff5f9794e0 / 8
    00000000  31 32 33 34 35 36 37 38                          12345678
Returned:  0 CKR_OK

103: C_Sign
2017-05-02 20:10:40.949
[in] hSession = 0x7fdbf6f13e20
[in] pData[ulDataLen] 00007fdbf6e03eb0 / 33
    00000000  27 AC 0C BB D6 C1 17 AC 30 4C B3 9D D6 3F 1D 10  '.......0L...?..
    00000010  61 7C 67 3A 02 CF 7C 56 D3 31 E7 59 00 B8 12 A5  a|g:..|V.1.Y....
    00000020  34                                               4
Returned:  145 CKR_OPERATION_NOT_INITIALIZED

104: C_CloseAllSessions
2017-05-02 20:10:40.950
[in] slotID = 0x0
Returned:  0 CKR_OK
```

In case of PKCS1 padding, it asks for `CKM_RSA_PKCS` and gets it:
```
100: C_GetAttributeValue
2017-05-02 20:13:06.620
[in] hSession = 0x7ff01ae03c60
[in] hObject = 0x7ff01ac263f0
[in] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  00007ff01ac29800 / 1
[out] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  True
Returned:  0 CKR_OK

101: C_SignInit
2017-05-02 20:13:06.620
[in] hSession = 0x7ff01ae03c60
pMechanism->type=CKM_RSA_PKCS
[in] hKey = 0x7ff01ac263f0
Returned:  0 CKR_OK

102: C_Login
2017-05-02 20:13:08.494
[in] hSession = 0x7ff01ae03c60
[in] userType = CKU_CONTEXT_SPECIFIC
[in] pPin[ulPinLen] 00007fff53e78420 / 8
    00000000  31 32 33 34 35 36 37 38                          12345678
Returned:  0 CKR_OK

103: C_Sign
2017-05-02 20:13:08.526
[in] hSession = 0x7ff01ae03c60
[in] pData[ulDataLen] 00007ff01ac29e20 / 51
    00000000  30 31 30 0D 06 09 60 86 48 01 65 03 04 02 01 05  010...`.H.e.....
    00000010  00 04 20 27 AC 0C BB D6 C1 17 AC 30 4C B3 9D D6  .. '.......0L...
    00000020  3F 1D 10 61 7C 67 3A 02 CF 7C 56 D3 31 E7 59 00  ?..a|g:..|V.1.Y.
    00000030  B8 12 A5                                         ...
[out] pSignature[*pulSignatureLen] 00007ff01b003000 / 256
    00000000  6F 3D 67 42 1E B6 D6 40 9C 14 E7 E8 F7 9F 69 2B  o=gB...@......i+
    . . . . .
    000000F0  17 BD 9D 86 FC AE D6 63 2D 9E 9A B5 9F 9A B3 2A  .......c-......*
Returned:  0 CKR_OK

104: C_CloseAllSessions
2017-05-02 20:13:09.194
[in] slotID = 0x0
Returned:  0 CKR_OK
```

**Comment by mtrojnar** [comment]
This issue has been moved to OpenSSL, as there is nothing we can do in libp11 to fix it.  I am closing this issue for libp11.
