### ISSUE TITLE
Tests fail (4 out of 5) against OpenSSL-1.1.0-stable

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#163]
@mtrojnar Building against OpenSSL-1.1.0-stable produces the same result:
```
. . . . .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
FAIL: rsa-testpkcs11.softhsm
FAIL: rsa-testfork.softhsm
FAIL: rsa-testlistkeys.softhsm
PASS: rsa-evp-sign.softhsm
FAIL: ec-testfork.softhsm
```

Obtaining a stack backtrace is hard because of the amount of shell script parametrization involved in the tests. I'd be happy to follow your instructions to obtain and post the backtrace.

And since all of the OpenSSL tests pass OK - I rather doubt the root cause is in OpenSSL itself. I suspect it's with the incompatibility of the API that the tests aren't fully adjusted to. Might be something with SoftHSMv2 as well...

[test-suite.log.txt](https://github.com/OpenSC/libp11/files/1106221/test-suite.log.txt)

**Comment by mouse07410** [comment]
@mtrojnar ???

**Comment by mtrojnar** [comment]
Doesn't look as something different from #162, does it?

**Comment by mouse07410** [comment]
No, it's the same - just wasn't sure if you're OK continuing the discussion in a closed issue. But you re-opened it since. ;-)

All cool. ;-)
