### ISSUE TITLE
"openssl_conf = openssl_init" requirement

### ISSUE THREAD

**Issue by bmomjian** [OpenSC/libp11#165]
For the OpenSSL engine definition docs at:

    https://github.com/OpenSC/libp11

to work, you must add this to your OpenSSL config file:

    openssl_conf = openssl_init

and it must be placed before any sections are defined.

**Comment by mtrojnar** [comment]
Thank you.  Please submit a PR.

**Comment by mtrojnar** [comment]
Merged #166
