### ISSUE TITLE
Docs for "without p11-kit"

### ISSUE THREAD

**Issue by bmomjian** [OpenSC/libp11#167]
This URL:

     https://github.com/OpenSC/libp11

explains how to configure the OpenSSL config file to know about the libraries under the heading "Using in systems without p11-kit,", but at the bottom it explains that you have to "provide the engine configuration explicitly." I think the second part is unnecessary if the first part is done properly.

**Comment by bmomjian** [comment]
Moved to a pull request.

**Comment by mtrojnar** [comment]
OpenSSL commandline tools allow for configuring engines via configuration file or cli parameters. They are both valid methods.

**Comment by bmomjian** [comment]
Yes, agreed.  I think the docs should point out the cli parameters are unnecessary _if_ you have already configured the config file.  I have closed this and opened a pull request with a patch that just moves the section and mentions this.  It does not remove it.
