### ISSUE TITLE
Build issues with MSVC 2012 and OpenSSL 1.1.0

### ISSUE THREAD

**Issue by beamer159** [OpenSC/libp11#169]
MSVC 2012 expects .c files to declare all variables at the top of a function block. 2 functions don't follow this rule:

p11_rsa.c has the following function:

    static void pkcs11_update_ex_data_rsa(PKCS11_KEY* key)
    {
        EVP_PKEY* evp = key->evp_key;
    
        if (evp == NULL)
            return;
        if (EVP_PKEY_base_id(evp) != EVP_PKEY_RSA)
        return;

        RSA* rsa = EVP_PKEY_get1_RSA(evp);
        pkcs11_set_ex_data_rsa(rsa, key);
        RSA_free(rsa);
    }

It had to be changed to the following (moving the RSA* declaration up)

    static void pkcs11_update_ex_data_rsa(PKCS11_KEY* key)
    {
        EVP_PKEY* evp = key->evp_key;
        RSA* rsa;
    
        if (evp == NULL)
            return;
        if (EVP_PKEY_base_id(evp) != EVP_PKEY_RSA)
        return;

        rsa = EVP_PKEY_get1_RSA(evp);
        pkcs11_set_ex_data_rsa(rsa, key);
        RSA_free(rsa);
    }

p11_ec.c had the identical issue and needed the same fix.

---
OpenSSL 1.1.0 changed their primary lib/dll file name from libeay32 to libcrypto. Therefore, make.rules.mak had to change the line

    OPENSSL_LIB = $(OPENSSL_DIR)\lib\libeay32.lib

to the line

    OPENSSL_LIB = $(OPENSSL_DIR)\lib\libcrypto.lib

With these changes, I could build successfully.

**Comment by mtrojnar** [comment]
Please submit 2 separate pull requests with your proposed fixes.  Make sure the code can still be built with newer versions of MSVC and against older versions of OpenSSL.

**Comment by mtrojnar** [comment]
Fixed with https://github.com/OpenSC/libp11/commit/82837b4e4aabf925ca5065ed1e9511549ec7a084 and https://github.com/OpenSC/libp11/commit/e5559b35a6e76b3e1e09214ea3df9dee29321ea3 respectively.
