### ISSUE TITLE
p11tool --list-all not documented in manual page

### ISSUE THREAD

**Issue by bmomjian** [OpenSC/libp11#174]
The p11tool "--list-all" option is listed in --help, and is shown as an example at the bottom of the p11tool manual page, but it does not appear as a listed option in the manual page.

Is this the right place to report the failure?  How do I report what version of p11tool has this issue?

**Comment by mtrojnar** [comment]
Wrong project:
```
$ dpkg -S /usr/bin/p11tool
gnutls-bin: /usr/bin/p11tool
```
Try submitting the bug to gnutls.
