### ISSUE TITLE
Enhancement: add support for digests

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#179]
Many tokens (including PIV and HSM) can do SHA-1 and SHA-2 digests on-board. While using them this way is suboptimal, it may be necessary to be able to use `EVP_DigestSignInit()`. 

The way OpenSSL currently implemented `EVP_DigestSignInit()` is "all-or-nothing": either *all* the functionality **including data digesting** is performed on the token, or *none* is performed on the token. Therefore there is no way to request, e.g., RSA-PSS with padding done on the token, but the data digested in software. 

One solution is to modify OpenSSL to correct for this (IMHO) oversight. It is unclear whether the OpenSSL dev team agrees.

Another solution is to enhance the pkcs11 engine to advertise digests as well (`SHA-1`, `SHA256`, `SHA384`, `SHA512`, and if you feel charitable - `MD5`, `RIPEMD160`, `GOSTR3411`).

I think that the ability to request data digest done on-board would be beneficial, so I'm asking for this enhancement.

**Comment by dengert** [comment]
PIV actually only does RAW RSA and EC on the card. The PKCS\#11 module may advertise mechanisms that are done partially in software within the PKCS\#11 module.  The CHF_HW  flag of a mechanism can say if it is done in hardware or software, but for compound operations there is no flag to say part is done in  hardware and part in software.

**Comment by mouse07410** [comment]
> ...for compound operations there is no flag to say part is done in hardware and part in software

Yes, but I'm talking about OpenSSL-type compound operation. *Data* hashing is one operation, and PSS padding (that includes its own hashing) is another. OpenSSL current implementation of `EVP_DigestSignInit()` forces *both* data hashing *and* PSS padding to be done in one place - either by the engine, or by the OpenSSL software. 

What I'm trying to achieve with OpenSSL team is doing data hashing in software, but PSS padding by the engine.

What I'm trying to achieve here is getting the engine to support data hashing, both as a good mechanism to have, and as a backup in case OpenSSL team doesn't change the current behavior of `EVP_DigestSignInit()`.

**Comment by mtrojnar** [comment]
@mouse07410 I'm not sure I understood the goal of this enhancement.  Can you describe some scenarios that require this feature?

**Comment by mouse07410** [comment]
> Can you describe some scenarios that require this feature?

Unfortunately,  yes I can. Imagine that I want to sign a reasonably large (or at least not equal to the digest size) blob of data on an HSM device. One natural mechanism to do that would be
```
   EVP_DigestSignInit();
   EVP_DigestSignUpdate();
   EVP_DigestSignFinal();
```
to combine digesting the data and signing the result into as few function calls as practical.

Current OpenSSL implementation of `EVP_DigestSignInit()` accepts input parameter `ENGINE *`, so in theory it allows to offload the padding to the hardware token (like PIV or HSM). The problem is - it does not allow passing signing context *to* this operation. Instead it creates one for you. One consequence of that is - if you do pass the engine pointer, `EVP_DigestSignInit()` will think that *everything* *including the data digest* is done by the engine. So it will seek engine method for the specified digest, and fail with "not implemented". 

What if you *don't* pass the engine pointer to it? Then it will do everything in software, and since the private key had the engine reference in it, request `RSA-X-509` from the token to perform the final step of this chain.

It was OK when all the tokens supported raw RSA, but it fails now when there are tokens that refuse to do raw RSA. 

So the goal of this enhancement is for the engine to advertise support for digests, and when asked to perform, say, `SHA384(some-data)` either do it in software, or gracefully fall back onto something that OpenSSL does. I'm trying to avoid `unimplemented digest` error message caused by OpenSSL trying to push data digest onto the engine and borking when finding that the engine only advertises asymmetric crypto.

**Comment by mtrojnar** [comment]
Could you post some test commands (preferably with SoftHSM2) that fail because of this issue?

**Comment by mouse07410** [comment]
Something like

```
    privkey = ENGINE_load_private_key(e, SignPrivKey, NULL, &cb_data);
    md_ctx = EVP_MD_CTX_create();
 
    rv = EVP_DigestSignInit(md_ctx, &ctx, md, engine, privkey);
    rv = EVP_DigestSignUpdate(md_ctx, in, inlen);
    // set_signature_md() has been done internally in DigestSignInit()
    rv = EVP_PKEY_CTX_set_rsa_padding(ctx, padding);
    rv = EVP_PKEY_CTX_set_rsa_mgf1_md(ctx, md);
    rv =  EVP_PKEY_CTX_set_rsa_pss_saltlen(ctx, saltlen);
    *olen = 0;
    rv = EVP_DigestSignFinal(md_ctx, NULL, olen);
    *out = OPENSSL_malloc(*olen);
    rv = EVP_DigestSignFinal(md_ctx, *out, olen);    

    return rv;
```

results in `EVP_DigestSignInit()` failing with something like
```
140736337826752:error:260BA093:engine routines:ENGINE_get_digest:unimplemented digest:crypto/engine/tb_digest.c:74:
140736337826752:error:06080086:digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:95:
```

**Comment by dengert** [comment]
The main problem is EVP_DigestSignUpdate may be called multiple times. 
The application may be reading from a file for example. So  the 
```
 EVP_DigestSignInit();
   EVP_DigestSignUpdate();
   EVP_DigestSignFinal();
```
need to be broken up into multiple calls from the application. And a C_Sign may need to be added too. 
This will greatly complicate the code. 

To fully support this, there are or were smart cards that could do the final hash operation on the card. So a full solution would allow for that too. (I have never seen one.)

**Comment by mouse07410** [comment]
> The main problem is EVP_DigestSignUpdate may be called multiple times. The application may be reading from a file for example.

Yes, certainly. Almost for sure. But I don't see how it can impact anything.

>
>
```  
   EVP_DigestSignInit();
   EVP_DigestSignUpdate();
   EVP_DigestSignFinal();
```
> need to be broken up into multiple calls from the application. 

I don't understand. The above are three calls. The call that actually involves digesting data (e.g., file) is `EVP_DigestSignUpdate()`. I'd expect the engine to just redirect it or fallback onto the "real" digest-doing part of OpenSSL. (Almost) certainly not trying to use the hardware token for that (e.g., Yubico HSM does *not* do data digests on-board).

> And a C_Sign may need to be added too.

Where? What for? That method can *only* be called from `EVP_DigestSignFinal()`, and at that point there cannot be any more reference to the input data (that all was finished with the series of `EVP_DigestSignUpdate()`).

> This will greatly complicate the code.

If it were necessary to do - yes. But I don't see why it would be needed at all.

> To fully support this, there are or were smart cards that could do the final hash operation on the card. 

I know of tokens that could do hash as part of a complex padding (like OAEP or PSS). I am not aware of tokens that do data hashing on-board.

> So a full solution would allow for that too. (I have never seen one.)

:-)  In that case I'd settle for a solution that just does what I need/want. ;-)

**Comment by mouse07410** [comment]
If OpenSSL goes through with https://github.com/openssl/openssl/pull/4503 reasonably quickly, criticality of this enhancement is not high. I'd vote to prioritize OAEP implementation.

**Comment by dengert** [comment]
What I was trying to say is if you want to be able to implement something like `CKM_SHA256`
You will need to have 
```
   EVP_DigestInit();         call C_DigestInit
   EVP_DigestUpdate();  call C_Digestupdate    May be multiple times.
   EVP_DigestFinal();      call C_DigestFinal 
```

Or to implement something like `CKM_SHA256_RSA_PKCS`
```
   EVP_DigestSignInit();        call C_SignInit
   EVP_DigestSignUpdate(); call C_SignUpdate    May be multiple times.
   EVP_DigestSignFinal();      call C_SignFianal
```
Depending on how OpenSSL was written this might not be easy. Only selected structures can have 
ex_data. It is not clear if the EVP_MD_meth can be hooked to make it work and how to store the state as you process blocks of date in the *_Update loop.  Only selected structures can have ex_data.

This maybe not worth the effort if the hardware token does not do the digest in hardware. 
All you would be doing is moving the digest function from OpenSSL to the PKCS\#11 module that would  do it in software, most likely by calling the same OpenSSL functions to do the digest.

**Comment by mouse07410** [comment]
> ... if you want to be able to implement something like `CKM_SHA256`...

Yes, totally agree.

> ...Or to implement something like `CKM_SHA256_RSA_PKCS`...

Respectfully disagree. Based on how `EVP_DigestSignXXX()` set of functions work, I expect it to do:
```
   EVP_DigestSignInit();        call C_DigestInit
   EVP_DigestSignUpdate();      call C_DigestUpdate    May be multiple times.
   EVP_DigestSignFinal();       call C_DigestFinal then call C_SignInit then call C_Sign (note that there's no _C_SignFinal)
```

But regardless...

> This maybe not worth the effort if the hardware token does not do the digest in hardware.

I'm afraid you're 100% right on this. And considering that we have a solution that at least one respected member of the OpenSSL team likes, messing with data digests is probably very low priority. Probably lower than supporting key generation on the token...

**Comment by mouse07410** [comment]
@mtrojnar do you *really* want *me* messing with this? I don't even know where to start!

**Comment by mtrojnar** [comment]
> I don't even know where to start!

You wrote:
```
140736337826752:error:260BA093:engine routines:ENGINE_get_digest:unimplemented digest:crypto/engine/tb_digest.c:74:
```
so I guess `ENGINE_get_digest()` may be a good starting point to find out which methods need to be implemented.

Most likely our `eng_front.c` needs an `ENGINE_set_digests()` call.

**Comment by mtrojnar** [comment]
> @mtrojnar do you really want me messing with this?

It looks like a good learning opportunity.  This is nothing urgent.  Take your time.  Bear in mind the KISS principle.  Submit a PR when your code is ready.

**Comment by mtrojnar** [comment]
> Something like
> 
> ```c
>     privkey = ENGINE_load_private_key(e, SignPrivKey, NULL, &cb_data);
>     md_ctx = EVP_MD_CTX_create();
>  
>     rv = EVP_DigestSignInit(md_ctx, &ctx, md, engine, privkey);
>     rv = EVP_DigestSignUpdate(md_ctx, in, inlen);
>     // set_signature_md() has been done internally in DigestSignInit()
>     rv = EVP_PKEY_CTX_set_rsa_padding(ctx, RSA_PKCS1_PSS_PADDING);
>     rv = EVP_PKEY_CTX_set_rsa_mgf1_md(ctx, md);
>     rv =  EVP_PKEY_CTX_set_rsa_pss_saltlen(ctx, -2);
>     *olen = 0;
>     rv = EVP_DigestSignFinal(md_ctx, NULL, olen);
>     *out = OPENSSL_malloc(*olen);
>     rv = EVP_DigestSignFinal(md_ctx, *out, olen);    
> 
>     return rv;
> ```
> 
> results in `EVP_DigestSignInit()` failing with something like
> 
> ```
> 140736337826752:error:260BA093:engine routines:ENGINE_get_digest:unimplemented digest:crypto/engine/tb_digest.c:74:
> 140736337826752:error:06080086:digital envelope routines:EVP_DigestInit_ex:initialization error:crypto/evp/digest.c:95:
> ```

I'm not sure I understand why someone might use this code instead of our example provided in https://github.com/OpenSC/libp11/blob/master/tests/rsa-pss-sign.c.  It seems far more complex.

**Comment by mouse07410** [comment]
> I'm not sure I understand why someone might use this code instead of our example...

Because the cited code predates your example by almost a year...?  ;-)

Also, I don't find your example to be much simpler that the cited code (no offense meant). 

The cited code explicitly sets several parameters that your example doesn't - but that's up to the person who employs the PSS: if he needs to be specific about, e.g., MGF1, then there's no way around setting it explicitly. And if the defaults are OK for that person - then there's no need to explicitly mess with them.

**Comment by mtrojnar** [comment]
> > I'm not sure I understand why someone might use this code instead of our example...
> 
> Because the cited code predates your example by almost a year...? ;-)

Oh, the example is not mine: https://github.com/OpenSC/libp11/pull/225

> Also, I don't find your example to be much simpler that the cited code (no offense meant).

None taken (not only because I didn't write it).

The equivalent code appears to be (with redacted error handling) roughly:
```c
	pkey_ctx = EVP_PKEY_CTX_new(private_key, e);
 	EVP_PKEY_sign_init(pkey_ctx);
 	EVP_PKEY_CTX_set_rsa_padding(pkey_ctx, RSA_PKCS1_PSS_PADDING);
 	EVP_PKEY_CTX_set_signature_md(pkey_ctx, digest_algo);
 	sig_len = sizeof(sig);
 	EVP_PKEY_sign(pkey_ctx, sig, &sig_len, md, EVP_MD_size(digest_algo));
 	EVP_PKEY_CTX_free(pkey_ctx);
```

> The cited code explicitly sets several parameters that your example doesn't - but that's up to the person who employs the PSS: if he needs to be specific about, e.g., MGF1, then there's no way around setting it explicitly. And if the defaults are OK for that person - then there's no need to explicitly mess with them.

There seem to be more differences that just MGF1.

Is it possible that this issue has been fixed during the last year?

**Comment by mouse07410** [comment]
> > Is it possible that this issue has been fixed during the last year?
>
> Sure it's possible. Let me try and report.

Can't remember if it's my personal patch or the mainstream/upstream - but `EVP_DigestSignInit()` etc. seem to be working with the HSM just fine... The issue was separating data digest from the digest that's part of the signature method - apparently they're separated correctly now (again, don't remember whether I had to modify OpenSSL code for that, or not)...

**Comment by mouse07410** [comment]
> Did I correctly understand that this issue can be closed now?

I guess we can do that. If I'm missing something, we can always re-open this one or open a new one.

Thanks!
