### ISSUE TITLE
Error storing private key on bit4id smartcard

### ISSUE THREAD

**Issue by n3wtron** [OpenSC/libp11#184]
I've got a "Vendor General Error" storing a private key on a smartcard (vendor:bit4id) calling PKCS11_store_private_key.

The pkcs11-tool (from terminal) works so I've tried to compare the libp11 code to pkcs11-tool.
With this modification https://github.com/n3wtron/libp11/tree/feature/import_priv_key_exponents it works, but I'm not so expert to say that is the correct solution.

I'll really appreciate if someone has some time to check it and give me some feedback

Thank you

**Comment by dengert** [comment]
A minor comment is the choice of variables names. For readability, I would suggest
rsa_exp1, rsa_exp2 and rsa_coef be renamed  rsa_dmp1, rsa_dmq1 and rsa_iqmp. 

(I have no way to test this.)

**Comment by dengert** [comment]
Based on looking at the OpenSSL code, I would also replace `if (rsa_exp1 && rsa_exp2 && rsa_coef)` with 3 separate tests and only add the attributes for the ones present.

**Comment by mtrojnar** [comment]
@n3wtron Makes sense.  Please apply the changes suggested by @dengert and submit a PR.

**Comment by n3wtron** [comment]
@mtrojnar, I will modify the code and submit a merge request. Thank you

**Comment by mtrojnar** [comment]
#186 has been merged.
