### ISSUE TITLE
PKCS11_find_key_from_key method is undefined

### ISSUE THREAD

**Issue by kiranpradeep** [OpenSC/libp11#189]
The method `PKCS11_find_key_from_key` in libp11.h([1](https://github.com/OpenSC/libp11/blob/f5274ad23db292978e9346c95e245682d91463ba/src/libp11.h#L283)) is not implemented and so undefined. Is this intentional?

**Comment by mtrojnar** [comment]
Apparently this function got defined in https://github.com/OpenSC/libp11/commit/ff1b48cc803e2ea76a82a62c7172e3dbe6123895, but it was never exported.  I later removed the definition but I forgot to also remove the declaration.
