### ISSUE TITLE
getting all slots which has token present

### ISSUE THREAD

**Issue by kiranpradeep** [OpenSC/libp11#191]
The use of `PKCS11_enumerate_slots` followed by `PKCS11_find_token` will give the first slot which has token. Example([1](https://github.com/OpenSC/libp11/blob/18138e807b9583a83a1246bdd049b64272efd474/examples/listkeys.c#L67)) is already provided. Assuming we have a case with multiple slots and token, how do we get to the next slot with a token? `PKCS11_find_token` will always give the first token only.

**Comment by mtrojnar** [comment]
You don't **have** to use `PKCS11_find_token()`.  You can check each `PKCS11_SLOT` structure returned by `PKCS11_enumerate_slots()` for non-NULL `token` values.
``` C
/** PKCS11 slot: card reader */
typedef struct PKCS11_slot_st {
    char *manufacturer;
    char *description;
    unsigned char removable;
    PKCS11_TOKEN *token;    /**< NULL if no token present */
    void *_private;
} PKCS11_SLOT;
```
