### ISSUE TITLE
API for changing SO pin

### ISSUE THREAD

**Issue by kiranpradeep** [OpenSC/libp11#192]
`PKCS11_change_pin` is provided for changing user pins. But there is no API for changing SO pin. Is this intentionally not provided(_readonly-login_ comment)?

Sorry for posting queries as issues. Please point to the mailing list if that is appropriate. I am not able to find one.

**Comment by dengert** [comment]
http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.pdf
"C_InitToken" says:
"If the SO PIN is lost, then the card MUST be reinitialized using a
mechanism outside the scope of this standard."

https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=pkcs11
has a "Send A Comment" button

**Comment by kiranpradeep** [comment]
The query was about changing SO pin provided we know the current SO pin. It was not for the case when the SO PIN is lost. Since libp11 had an API for changing USER PIN, I expected similar one for SO PIN. Currently, I do it with below command. But no libp11 API exists.
`pkcs11-tool --login --login-type so --so-pin XXXX --change-pin --new-pin XXXX`

**Comment by dengert** [comment]
OK. looking closer it looks like calling PKCS11_login with SO then calling PKCS_11_change_pin should change the SO pin. Maybe the libp11 documentation should say user or SO pin.?

**Comment by mtrojnar** [comment]
Could you submit a PR to clarify the documentation?

**Comment by kiranpradeep** [comment]
@mtrojnar I want to, but limited by (2) below. Also, I am not familiar with PKCS11 basic concepts. Three queries.
1. I assume we need to do login(PKCS11_login) if we need to access private keys. But I am not sure when to open a session(PKCS11_open_session)? I also couldn't find a corresponding PKCS11_close_session.
2. API PKCS11_change_pin doesn't feel right. Does it forces user( both SO and USER ) to be logged in before changing status? The documentation might not look clean.
3. Is there a mailing list with archives people can search for, before posting queries on libp11 in GitHub as issues.
