### ISSUE TITLE
Update libp11 Homebrew package for MAC 

### ISSUE THREAD

**Issue by Vad1mo** [OpenSC/libp11#193]
Hello, 

I am trying to create a Homebrew formula update of libp11 from 0.2.8 to 0.4.7 however I have some difficulties doing so. The issue is more  Homebrew related, but maybe someone here could also help out on resolving this issue. Maybe even http://linuxbrew.sh/ can be used.

Issue describing the problem: https://github.com/Homebrew/homebrew-core/issues/20419

It is very easy to reproduce the issue. 

```bash
brew pull https://github.com/Homebrew/homebrew-core/pull/20409
brew install --interactive libp11
# in the new shell 
./configure
make
make install
```

**Comment by mtrojnar** [comment]
This is definitely **not** a problem with libp11.  See https://github.com/Homebrew/homebrew-core/issues/20419#issuecomment-347107427 for details.
