### ISSUE TITLE
MacOS "Failed to enumerate slots"

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#196]
MacOS Sierra 10.12.6, Xcode-9.1, current master.

I haven't done much with tokens for a couple of weeks on this machine, and with OpenSSL/libp11 - on all machines for a couple of weeks (or for a few weeks?).

Today I needed to do some OpenSSL stuff, and it failed miserably on me:
```
openssl s_client -engine pkcs11 -keyform engine -connect sso:443 -key "pkcs11:token=Uri%20the%20Great;id=%01;type=private" -cert uri_lab_id.pem -showcerts -msg


*************** OpenSC PKCS#11 spy *****************
Loaded: "/Library/OpenSC/lib/opensc-pkcs11.dylib"

0: C_GetFunctionList
2017-11-16 10:29:08.096
Returned:  0 CKR_OK

1: C_Initialize
2017-11-16 10:29:08.098
[in] pInitArgs = 0x7fcb09d1f3e0
     flags: 2
       CKF_OS_LOCKING_OK
Returned:  0 CKR_OK

2: C_GetSlotList
2017-11-16 10:29:08.288
[in] tokenPresent = 0x0
[out] pSlotList: 
Count is 2
[out] *pulCount = 0x2
Returned:  0 CKR_OK

3: C_GetSlotList
2017-11-16 10:29:08.289
[in] tokenPresent = 0x0
[out] pSlotList: 
Slot 0
Slot 4
[out] *pulCount = 0x2
Returned:  0 CKR_OK

4: C_GetSlotInfo
2017-11-16 10:29:08.290
[in] slotID = 0x0
[out] pInfo: 
      slotDescription:        'SCM Microsystems Inc. SCR 3310  '
                              '                                '
      manufacturerID:         'SCM Microsystems Inc.           '
      hardwareVersion:         2.4
      firmwareVersion:         0.0
      flags:                   6
        CKF_REMOVABLE_DEVICE             
        CKF_HW_SLOT                      
Returned:  0 CKR_OK

5: C_GetSlotInfo
2017-11-16 10:29:08.291
[in] slotID = 0x4
[out] pInfo: 
      slotDescription:        'Yubico Yubikey 4 OTP+U2F+CCID   '
                              '                                '
      manufacturerID:         'Yubico                          '
      hardwareVersion:         4.39
      firmwareVersion:         0.0
      flags:                   7
        CKF_TOKEN_PRESENT                
        CKF_REMOVABLE_DEVICE             
        CKF_HW_SLOT                      
Returned:  0 CKR_OK

6: C_GetTokenInfo
2017-11-16 10:29:08.293
[in] slotID = 0x4
[out] pInfo: 
      label:                  'who cares                   '
      manufacturerID:         'piv_II                          '
      model:                  'PKCS#15 emulated'
      serialNumber:           'irrelevant'
      ulMaxSessionCount:       0
      ulSessionCount:          0
      ulMaxRwSessionCount:     0
      ulRwSessionCount:        0
      ulMaxPinLen:             8
      ulMinPinLen:             4
      ulTotalPublicMemory:     -1
      ulFreePublicMemory:      -1
      ulTotalPrivateMemory:    -1
      ulFreePrivateMemory:     -1
      hardwareVersion:         0.0
      firmwareVersion:         0.0
      time:                   '                '
      flags:                   40d
        CKF_RNG                          
        CKF_LOGIN_REQUIRED               
        CKF_USER_PIN_INITIALIZED         
        CKF_TOKEN_INITIALIZED            
Returned:  0 CKR_OK
Failed to enumerate slots

7: C_Finalize
2017-11-16 10:29:08.303
Returned:  0 CKR_OK
can't use that engine
140736904975368:error:82065030:PKCS#11 module:pkcs11_check_token:Device error:p11_slot.c:467:
140736904975368:error:260B806D:engine routines:ENGINE_TABLE_REGISTER:init failed:eng_table.c:175:
no engine specified
unable to load client certificate private key file
$ 
```

Note that while the logs are with Yubikey, I've tested it on real PIV and CAC, with exactly the same failure.

Needless to say, this used to work perfectly, and it's quite important for me to get it working again.
Here's the `OPENSC_DEBUG-9` log: 
[opensc-libp11.log.txt](https://github.com/OpenSC/libp11/files/1479160/opensc-libp11.log.txt)

It appears that it treats the token as logged in while it isn't - and it doesn't prompt for a PIN.
@dengert could you take a look at this too, please?

With OpenSC itself the token works perfectly (therefore I think it's not related to the screwed-up Notification Proxy of OpenSC that I disable during build because it never worked):
```
$ pkcs11-tool -s --id 01 --type privkey -m SHA384-RSA-PKCS -i t6400.dat -o t6400.dat.sigpkcs
Using slot 1 with a present token (0x4)
Logging in to "Uri the Great".
Please enter User PIN: 
Using signature algorithm SHA384-RSA-PKCS
$ openssl dgst -verify yubi-pub-9a.pem -sha384 -signature t6400.dat.sigpkcs t6400.dat
Verified OK
$ 
```

This is when I try to verify the above signature using the key on the token (which again, worked consistently for the last year at least):
```
$ ~/openssl-1.1/bin/openssl dgst -engine pkcs11 -keyform engine -verify "pkcs11:object=%01;type=public" -sha384 -signature t6400.dat.sigpkcs t6400.dat
engine "pkcs11" set.
Failed to enumerate slots
Failed to enumerate slots
PKCS11_load_public_key returned NULL
cannot load key file from engine
140736904975296:error:82065030:PKCS#11 module:pkcs11_check_token:Device error:p11_slot.c:467:
140736904975296:error:26097081:engine routines:ENGINE_load_public_key:failed loading public key:crypto/engine/eng_pkey.c:108:
unable to load key file
$
```

Needless to add - if there's any info I can provide to help debugging this, I'd be happy to oblige.

**Comment by mouse07410** [comment]
Also, how do I pass `CMD_VERBOSE` to the engine? First, when using OpenSSL CLI, and second - using the following code:
```
ENGINE* load_engine(const char *engine_name) {
    ENGINE *e = NULL;
    
    e = ENGINE_by_id(engine_name);
    if ( e == NULL ) {
        fprintf(stderr,"ENGINE_by_id(\"%s\") returned %lu\n",
                engine_name, ERR_get_error());
        ERR_print_errors_fp(stderr);
        return NULL;
    }
    
    if ( ! ENGINE_init(e) ) {
        fprintf(stderr,"ENGINE_init returned %lu\n",ERR_get_error());
        ERR_print_errors_fp(stderr);
        return NULL;
    }
    if (ENGINE_set_default(e, ENGINE_METHOD_RSA) <= 0) {
        fprintf(stderr,"ENGINE_set_default() returned %lu\n",ERR_get_error());
        ERR_print_errors_fp(stderr);
    }
    return e;
}
```
and
```
  privkey = ENGINE_load_private_key(e, SignPrivKey, NULL, &cb_data);
  md_ctx = EVP_MD_CTX_create();
  rv = EVP_DigestSignInit(md_ctx, &ctx, md, NULL, privkey);
  rv = EVP_PKEY_CTX_set_rsa_padding(ctx, padding);
  rv = EVP_DigestSignUpdate(md_ctx, in, inlen);
  . . . . .
  rv = EVP_DigestSignFinal(md_ctx, *out, olen);
```

**Comment by dengert** [comment]
In your SPY trace, there are 2 slots. Slot 0 does not have a token and slot 4 has the Yubikey. 

Maybe in the past you only had  a single slot.  In this case you have 2. 
 
I would step a through this loop in p11_slot.c and look at what pkcs11_init_slot returns. 


```62   for (n = 0; n < nslots; n++) {
 63                 if (pkcs11_init_slot(ctx, &slots[n], slotid[n])) {
 64                         while (n--)
 65                                 pkcs11_release_slot(ctx, slots + n);
 66                         OPENSSL_free(slotid);
 67                         OPENSSL_free(slots);
 68                         return -1;
 69                 }
```

**Comment by mouse07410** [comment]
Changed the code to
```
	for (n = 0; n < nslots; n++) {
        rv = pkcs11_init_slot(ctx, &slots[n], slotid[n]);
//        if (ctx->verbose)
            fprintf(stderr, "%s:%d rv=%d  n=%lu\n", __FILE__, __LINE__, rv, n);
		if (rv) {
			while (n--)
				pkcs11_release_slot(ctx, slots + n);
			OPENSSL_free(slotid);
			OPENSSL_free(slots);
			return -1;
		}
	}
```

and here's the output of the test-program:
```
p11_slot.c:65 rv=0  n=0
p11_slot.c:65 rv=0  n=1
p11_slot.c:65 rv=0  n=2
p11_slot.c:65 rv=0  n=3
p11_slot.c:65 rv=0  n=4
p11_slot.c:65 rv=0  n=5
p11_slot.c:65 rv=-1  n=6
Failed to enumerate slots
2017-11-16 14:26:30.057015-0500 OSSL-Tst6[31352:1480696] Configuration.cpp(122): Missing slots.removable in configuration. Using default value: false
p11_slot.c:65 rv=0  n=0
p11_slot.c:65 rv=0  n=1
p11_slot.c:65 rv=0  n=2
p11_slot.c:65 rv=0  n=3
p11_slot.c:65 rv=0  n=4
p11_slot.c:65 rv=0  n=5
p11_slot.c:65 rv=-1  n=6
Failed to enumerate slots
PKCS11_get_private_key returned NULL
/Users/ur20980/src/OSSL-Tst6/OSSL-Tst6/main.c:557 sign: failed to get handle to pkcs11:manufacturer=piv_II;id=%02;type=private
4318192576:error:82065030:PKCS#11 module:pkcs11_check_token:Device error:p11_slot.c:470:
4318192576:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:78:
Signing failed! (rv=-1 olen=0)

```

**Comment by dengert** [comment]
How did it get n=6  if there are only 2 slots? In the SPY trace it said there were only 2 slots.

**Comment by dengert** [comment]
Are you using p11-kit? How many drivers are loaded?  If you debug that loop, what is the value of nslots? Based on the SPY output it should be 2. So why is n=6 when it fails?

**Comment by mouse07410** [comment]
> Are you using p11-kit?

Yes.

> How many drivers are loaded?

Here's what I get when no physical token is inserted:
```
$ p11tool --list-token-urls
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=89ffbc6e32f52c3f;token=Botan%20PKCS%2311%20tests
$
```

The tests above had one or two physical tokens inserted. Note that this setup hasn't changed for a few months (i.e., p11-kit has been on all of my machines).

**Comment by mouse07410** [comment]
Should I combine debugging and running SPY?

**Comment by mouse07410** [comment]
A more typical setup:
```
$ p11tool --list-token-urls
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=Default%20Trust
pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=89ffbc6e32f52c3f;token=Botan%20PKCS%2311%20tests
pkcs11:model=YubiHSM;manufacturer=Yubico%20%28www.yubico.com%29;serial=xxxxxxxx;token=YubiHSM
$
```

**Comment by mtrojnar** [comment]
> Also, how do I ensure `CMD_VERBOSE` is passed to the engine?

The same way `CMD_PIN` is passed to the engine.  With OpenSSL engine control commands.

**Comment by dengert** [comment]
Well the libp11 code is failing with n=6 which does not match any known
slot from OpenSC.

Debug or add printf to show slotid as well as nslots.

**Comment by dengert** [comment]
Your first debug log had OpenSC. The above does not have OpenSC at all! 

What code is really failing?
I would start be stripping out p11-kit modules and see which one is failing.

**Comment by dengert** [comment]
This might help to debug p11-kit https://p11-glue.freedesktop.org/doc/p11-kit/sharing-managed.html

**Comment by mouse07410** [comment]
> Your first debug log had OpenSC. The above does not have OpenSC at all!

Not sure what you mean. The failure appeared to be in libp11 invoked by OpenSSL. "Pure" OpenSC (like `pkcs11-tool --sign ...` worked fine. I showed both failure of libp11 and success of pure OpenSC.

Then using `p11-kit` I showed what soft tokens my system had. p11-kit doesn't fail. `opensc-tool` only shows hardware tokens. So, in total: 3 soft tokens, one YubiHSM device (also available via PKCS#11), and one or two physical tokens inserted - making the total number 5 or 6, depending.

And thanks for the p11-kit debug URL - I'll use it.

**Comment by dengert** [comment]
opensc-tool does not use PKCS#11 or p11-kit. It only uses libopensc. 

What I would like to see is you take p11-kit and the other PKCS\#11 modules when used with libp11. 

In the original opensc-debug log starting at 3256:
```
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] card-piv.c:3340:piv_pin_cmd: piv_pin_cmd tries_left=3, logged_in=0
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] card-piv.c:3341:piv_pin_cmd: returning with: 0 (Success)
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] sec.c:217:sc_pin_cmd: returning with: 0 (Success)
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] card.c:459:sc_unlock: called
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] reader-pcsc.c:662:pcsc_unlock: called
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] pkcs15-pin.c:717:sc_pkcs15_get_pin_info: returning with: 0 (Success)
0x7fffdd3a53c0 10:38:00.614 [opensc-pkcs11] framework-pkcs15.c:580:C_GetTokenInfo: C_GetTokenInfo(4) returns 0x0
0x7fffdd3a53c0 10:38:00.622 [opensc-pkcs11] pkcs11-global.c:310:C_Finalize: C_Finalize()
```
This shows the card is not logged_in, and has 3 retries. The C_GetTokenInfo(slot 4) returns 0. 
(It looks like p11-kit is returning all the slots, from all the modules, so the last 2 may be what OpenSC thinks are 0 and 4.  but are mapped to 5 and 6.)

Then the next call to OpenSC is to C_Finalize. So either the information in the tokeninfo is bad, or the code in libp11 between the call to C_GetTokenInfo in `p11_slot.c:pkcs11_check_token`  and `p11_slot.c:65 rv=-1  n=6` determined that it did not like something. 

pkcs11_init_slot is called and it does:
```
408         if ((info.flags & CKF_TOKEN_PRESENT) && pkcs11_check_token(ctx, slot    ))
409                 return -1;
```
So I would look at `pkcs11_check_token` My version from master as of yesterday looks like it should return 0, not -1.

As a side note I would also like to know where  `serialNumber:           'irrelevant' ` came from. 
This does not look valid to me. It should be padded with blanks to 16 characters. I don't see it in OpenSC or libp11.

**Comment by dengert** [comment]
In your original comment it says:
`140736904975368:error:82065030:PKCS#11 module:pkcs11_check_token:Device error:p11_slot.c:467:`
This would have been the return code from C_GetTokenInfo. 

```
461         rv = CRYPTOKI_call(ctx, C_GetTokenInfo(spriv->id, &info));
462         if (rv == CKR_TOKEN_NOT_PRESENT || rv == CKR_TOKEN_NOT_RECOGNIZED) {
463                 OPENSSL_free(slot->token);
464                 slot->token = NULL;
465                 return 0;
466         }
467         CRYPTOKI_checkerr(CKR_F_PKCS11_CHECK_TOKEN, rv);
```
OpenSC never returns CKR_DEVICE_ERROR. But the Yubico does. 
```
./yubico-piv-tool-git-my/yubico-piv-tool/ykcs11/pkcs11.h
    return CKR_DEVICE_ERROR;
    return CKR_DEVICE_ERROR;
    return CKR_DEVICE_ERROR;
    return CKR_DEVICE_ERROR;
./yubico-piv-tool-git-my/yubico-piv-tool/ykcs11/token_vendors.c
```
So I suspect the failure is in ykcs11/token_vendors.c or p11-kit. 
If you wanted to see what is going on, run the Yubico module under SPY, not the OpenSC module. 

Personally I don't think you want to have p11-kit load the OpenSC and the Yubico PKCS#11 modules at the same time. Both drivers will be fighting over the Yubico device.

**Comment by dengert** [comment]
If you need to use the Yubico driver for Yubico devices and OpenSC for real PIV cards, I could provide a mod to have the PIV driver not handle Yubico devices.

**Comment by mouse07410** [comment]
I'm still investigating this **weird** problem.

> So I suspect the failure is in ykcs11/token_vendors.c or p11-kit. If you wanted to see what is going on, run the Yubico module under SPY, not the OpenSC module.

Ha! Silly me, I did not realize that. :-(
Remedying it now.

> Personally I don't think you want to have p11-kit load the OpenSC and the Yubico PKCS#11 modules at the same time. Both drivers will be fighting over the Yubico device.

You have a good point here. And since Yubico PKCS#11 module is in general vastly inferior to the OpenSC one, I probably should remove the Yubico module from the p11-kit module-base. I kept it there because I hoped they would co-exist "peacefully", being selected by `pkcs11:token=XXX;` attribute in the key URI. Maybe this case proves me wrong... The main value of the Yubico module is that it can do initialization (like request-to-touch in addition to entering the correct PIN to allow an operation), but that can be done via `yubico-piv-tool` CLI as well, I don't have to be able to do it programmatically.

> If you need to use the Yubico driver for Yubico devices and OpenSC for real PIV cards, I could provide a mod to have the PIV driver not handle Yubico devices.

Thanks. I'll probably keep/use OpenSC for accessing all the PIVs, including Yubico. It would be interested to know how to tell the OpenSC PIV driver to ignore Yubico devices, but I don't think I'd actually deploy it.

**Comment by mtrojnar** [comment]
@mouse07410 Is there anything we can do in libp11 to deal with this issue?  Can we close it?

**Comment by mouse07410** [comment]
> Is there anything we can do in libp11 to deal with this issue? Can we close it?

I don't know, but suspect that we can't do much with it in libp11. If I learn otherwise (or if you learn otherwise) let's re-open. In the meanwhile, closing it sounds fine.
