### ISSUE TITLE
changes in 0.4.7 breaks api compability

### ISSUE THREAD

**Issue by yousong** [OpenSC/libp11#197]
openconnect now fails to build against libp11 0.4.7, complaining undefined macros previously present.  http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/openssl-pkcs11.c#l253

In e4c641b ("PKCS11 errors separated into P11 and CKR"), `ERR_LIB_PKCS11` was renamed to `ERR_LIB_CKR` which was later removed in e4c641b ("PKCS11 errors separated into P11 and CKR")

Should downstream project just drop support for libp11 older than 0.4.7?

**Comment by mtrojnar** [comment]
It is a macro, so an ifdef could be used to work around it.  I will investigate whether it is possible to restore the header file compatibility before the next libp11 release.
