### ISSUE TITLE
null pointer exception in libpkcs11.c

### ISSUE THREAD

**Issue by pencotts** [OpenSC/libp11#2]
In C_UnloadModule mod->handle is used assuming it is valid.
If the dlopen() in C_LoadModule fails, C_UnloadModule is called with mod->handle == NULL

suggest library unload code at line 123 in libpkcs11.c becomes:

   if (mod->handle)
  #ifdef WIN32
        FreeLibrary(mod->handle);
  #else
        dlclose(mod->handle);
   #endif

**Comment by nmav** [comment]
That should already be fixed. Please reopen if not.
