### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by nmav** [OpenSC/libp11#20]
Hello,
 Would it make sense to have a new release with the available fixes since 2.8?

**Comment by dengert** [comment]
+1, and release the engine too.

On 6/22/2015 6:55 AM, Nikos Mavrogiannopoulos wrote:
> Hello,
> Would it make sense to have a new release with the available fixes since 2.8?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/libp11/issues/20>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by nmav** [comment]
@martinpaljak would you be interested in making a release of that library? (with at least #27 merged)

**Comment by dengert** [comment]
Github lists a tag for libp11-0.3.0

The tag for libp11-0.3.0 does not show up when using git tag -l
or git tag shows tags for  previous versions but not libp11-0.3.0
The last one is tag-0.2.8

I see commit 6f71240991aa831f6fc2cc5431faf6ebec627ed2
released 0.3.0

Github lists a tag for libp11-0.3.0

Was the tag created as anotated? 
Was the tag pushed to  github?

**Comment by nmav** [comment]
If you see the tag in github it has been pushed to github :) I have no issue seeing the tag in new cloned copy.

**Comment by dengert** [comment]
Looks like tags are not fetched automaticly. 
 git -t fetch upstream 

I can see the tag now.
