### ISSUE TITLE
libp11 fails tests when SoftHSMv2 is built with Botan-2

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#218]
Build SoftHSMv2 with `--with-crypto-backend=botan`, and observe four out of six tests in libp11 fail consistently, regardless of whether you're building libp11 for OpenSSL-1.0.2 or 1.1.x. Try it if you don't believe me. ;-)

*Logs will be posted later.*

**Comment by mtrojnar** [comment]
No details were provided.  I'm closing this issue.
