### ISSUE TITLE
Enhancement: Allow reading attributes (wrapper for C_GetAttributeValue)

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/libp11#219]
The initial problem is that I'd like to know whether a private key on a PKCS#11 token is able to decrypt/sign. In PKCS#11 there is `C_GetAttributeValue` to request `CKA_DECRYPT` or `CKA_SIGN`, but this isn't available via `libp11.h`. Currently I only have the choice to *try* signing/decrypting with the resulting `EVP_PKEY` object and see if I get an error.

I see two possibilities to resolve this:
1. It should be easy to implement a new library function to request virtually any possible attribute. This can, however, be a lot to implement.
2. Request the attributes when calling `PKCS11_enumerate_keys()` and add the result to a new property of `PKCS11_KEY`.

**Comment by mtrojnar** [comment]
It was never one of the libp11 goals to expose complete flexibility (and thus complexity) of PCKS#11.  A tool for managing/exploring tokens should use PKCS#11 directly rather than libp11.
