### ISSUE TITLE
Allow changing the PIN with OpenSC

### ISSUE THREAD

**Issue by frankmorgner** [OpenSC/libp11#221]
There is [an old thread]( http://opensc.1086184.n5.nabble.com/Unblocking-PIN-via-PKCS-11-td7212i20.html) that explaines [how OpenSC is using C_Login and C_SetPIN](https://github.com/OpenSC/OpenSC/blob/master/src/pkcs11/framework-pkcs15.c#L1773-L1789). The problem is that PKCS#11 doesn't have the notion of a PUK so it was decided that:
- C_SetPIN sets a new value for the PIN by unblocking it with the PUK in R/W or R/O public sessions
- C_SetPIN changes the PIN from an old to a new value in R/W or R/O user/SO sessions

This forces me to change the PIN as follows:
1. C_Login (i.e. PKCS11_login) to get into the user session
2. C_SetPIN (i.e. PKCS11_change_pin) to change the PIN

Unfortunately this verifies the old PIN twice, which is especially disturbing with a PIN pad reader.

Now my questions:
- Do you have any experience how other PKCS#11 providers are implementing unblocking/changing the PIN?
- Do you see an alternative approach that OpenSC should do? (I can think of checking the PIN status and verifying the PUK if and only if the PIN is blocked; otherwise the standard PIN change is used)

**Comment by mtrojnar** [comment]
I think the current behavior is consistent with other similar PKCS#11 features: Users enter the PIN once to acquire a (supposedly long-term) session, and once more for each additional highly sensitive operation.  While I agree the PKCS#11 security assumptions may be inconvenient, I don't think libp11 should be actively bypassing them.
