### ISSUE TITLE
Does libp11 work with libressl?

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#227]
MacOS 10.13.5 comes with libressl-2.2.7 (current LibreSSL release is 2.7.4):
```
$ /usr/bin/openssl version
LibreSSL 2.2.7
$ 
```

I wonder if one can build `libp11` engine to work with it, and if so - what would the default locations for `enginesdir` and such. Also, whether it is feasible to have it work with `p11-kit` installed by Macports in `/opt/local`, aka `--with-pkcs11-module=/opt/local/lib/p11-kit-proxy.dylib`.

Does it even make sense to try to work with it, or is it best treated like OpenSSL-0.9.8 that MacOS prior to High Sierra came with?

Guidance would be appreciated!

**Comment by dengert** [comment]
Look at [OpenSC-libressl-2.7-PR](https://github.com/OpenSC/OpenSC/pull/1406) this might give you some clues as to what needs to be changed. Too bad lib11 and OpenSC used two different approaches to working with OpenSSL-1.1 and libresssl.

**Comment by mtrojnar** [comment]
I might accept clean LibreSSL patches.  Otherwise, I wouldn't waste my time on LibreSSL support.

**Comment by mouse07410** [comment]
That's what I wanted to learn. I'm not crazy about LibreSSL either.
