### ISSUE TITLE
Build instructions for Debian/Ubuntu incomplete?

### ISSUE THREAD

**Issue by smuehlst** [OpenSC/libp11#231]
I'm trying to build libp11-0.4.7 from the release tar file libp11-0.4.7.tar.gz. The build instructions seem to be outdated or incomplete. In INSTALL.md it says:

```
Unix Build
Install the OpenSSL development package. On Debian/Ubuntu use:

sudo apt-get install libssl-dev

Build and install libp11:

./configure && make && sudo make install
```

It starts with the fact that a `configure` script does not exist.

I tried the `bootstrap` script, and it exits with an error:

```
$ ./bootstrap 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Remember to add 'LT_INIT' to configure.ac.
autoreconf: running: /usr/bin/autoconf --force
configure.ac:185: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

I'm trying this on an Ubuntu 16.04.4 LTS system, after installing `libssl-dev` and also the `libtool` package.

What do I need to do to build `libp11-0.4.7` from source?

**Comment by dengert** [comment]
There should have been a configure file in a in a tar.gz distribution. 
Building from git source with tag libp11-0.4.7 on Ubuntu 16.04.4 LTS works after running ./bootstrap:

```
$ ./bootstrap
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Remember to add 'LT_INIT' to configure.ac.
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:27: installing './compile'
configure.ac:15: installing './missing'
examples/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
```

I would look at the versions of these two Ubuntu packages on your system.
On mine they are libtool 2.4.6-0.1 and autoconf 2.69-9

Also try Google search for: error: possibly undefined macro: AC_MSG_ERROR
This appears to be common problem, but not many good answers, other then 
to avoid the error. 

Based on what I see in configure.ac line 185, it is looking for doxygen. You could install it which might get around the problem id teh AC_MEG_ERROR . (Its not installed on my system.)

**Comment by smuehlst** [comment]
> There should have been a configure file in a in a tar.gz distribution.

@dengert: Thanks for pointing that out. I re-checked the release download, and it looks that I made a mistake by choosing the [Source code (tar.gz)](https://github.com/OpenSC/libp11/archive/libp11-0.4.7.tar.gz) link instead of the [libp11-0.4.7.tar.gz](https://github.com/OpenSC/libp11/releases/download/libp11-0.4.7/libp11-0.4.7.tar.gz) link on the [Releases page](https://github.com/OpenSC/libp11/releases).

I downloaded the file from the [libp11-0.4.7.tar.gz](https://github.com/OpenSC/libp11/releases/download/libp11-0.4.7/libp11-0.4.7.tar.gz) link, and this package indeed contains the configure script. I will retry the build with this package.

Thanks!
