### ISSUE TITLE
Re-license files under a known license

### ISSUE THREAD

**Issue by ansasaki** [OpenSC/libp11#233]
Some files are not licensed under a known permissive license, making it difficult to be used and distributed. For instance, the following files:

https://github.com/OpenSC/libp11/blob/master/examples/auth.c
https://github.com/OpenSC/libp11/blob/master/examples/listkeys.c
https://github.com/OpenSC/libp11/blob/master/examples/decrypt.c
https://github.com/OpenSC/libp11/blob/master/examples/getrandom.c
https://github.com/OpenSC/libp11/blob/master/tests/fork-test.c
https://github.com/OpenSC/libp11/blob/master/tests/list-tokens.c
https://github.com/OpenSC/libp11/blob/master/tests/openssl_version.c

Please, re-license the files using a known license. This would require the original authors to agree with the new licensing. One good licensing option would be the BSD 2-Clause, which is already used in some files.

**Comment by mtrojnar** [comment]
Please note the listed files are tests and examples that probably won't be included in binary distributions.  Source distributions may however be affected.  I hereby agree to re-license my contributions in those 7 files as BSD 2-Clause.

**Comment by ansasaki** [comment]
I would like to invite the original authors to please agree in this re-licensing:
@nmav 
@frankmorgner 
@szikora 

I could not find a github for Andreas Jellinghaus. Maybe someone could please contact him?

**Comment by nmav** [comment]
I'm fine with using BSD-2 clause license for my contributions.

**Comment by szikora** [comment]
Hi,

It’s fine for me to modify the licensing terms to any BSD type licence!

Cheers,

Jean-Pierre

**Comment by mtrojnar** [comment]
@ansasaki It seems that you have collected permissions from from all the identified authors.  Please feel free to submit a PR with license updates.

**Comment by nased0** [comment]
I am fine with BSD license too!

**Comment by mtrojnar** [comment]
No PR has been submitted for months.  Apparently nobody is interested in re-licensing the code anymore.
