### ISSUE TITLE
PIN login doesn't work. Stumped.

### ISSUE THREAD

**Issue by asmjmisc** [OpenSC/libp11#238]
Hi,

I've embarked on writing a piece of signing software using PKCS#11 smart cards. I haven't gotten far, because, for some reason unknown to me, I cannot log into the card with a PIN.

For comparison, I've tried different cards and different software (for the cards, I have a Gemalto chip card and a Nitrokey Pro) and the software is 1) custom software that works with the Gemalto cards I have, 2) Nitrokey's application and 3) the example auth.c program under examples in the repository.

I can log into the Gemalto card using the custom application and into the Nitrokey using their application. However, logging into both of the cards does not appear to work with the auth.c program nor the quick-n-dirties I put together myself.

I know this isn't exactly a support forum, but my knowledge of smart cards and the whole stack is limited, and I'm sort of stumped here for how to debug this. Am I tripping up on something common and known, or should this be working?

auth.c comes from the current master branch (63e203).

Edit: the Gemalto cards are read using the IDBridge CT30 (legacy name: PC USB TR and PC TWIN) reader. The readers are attached to a Linux system (Fedora 27). pcsc-lite-ccid is version 1.4.29-1 (no modifications from Fedora), but the ChangeLog lists the last commit being 70379da by Ludovic Rousseau.

**Comment by mtrojnar** [comment]
This may help: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by asmjmisc** [comment]
Thanks for the snide reply, but you're missing the point.

I don't know whether this is a bug, my personal ignorance of the subject or an expected incompatibility, hence I've given you the pieces of information that I do have and if you require more, feel free to ask - no need to be a pretentious prick about it.

**Comment by nased0** [comment]
That's how I log in to the card using OpenSSL PKCS#11 engine.
SetPin("1234");
SendPinToEngine("pkcs11");
[code]
#include <openssl/engine.h>
#include <openssl/err.h>
#include <openssl/conf.h>

#define MAXPINLENGTH 127
#define OPENSSL_ENGINE_STARTUP_WAIT 100

static char 	pchPIN[MAXPINLENGTH + 1];

void SetPIN(const char *szPIN)
{
	memset(pchPIN, 0, sizeof(pchPIN));
	strncpy(pchPIN, szPIN, MAXPINLENGTH);
}

BOOL SendPinToEngine(char const* _engine)
{
	BOOL ret = FALSE;
	ENGINE *pEngine = ENGINE_by_id(_engine);
	if (pEngine != NULL)
	{
		ret = ENGINE_ctrl_cmd(pEngine, "PIN", 0, pchPIN, 0, 0);
		if(!ret) return FALSE;
		ENGINE_free(pEngine);
	} else return FALSE;
	Sleep(OPENSSL_ENGINE_STARTUP_WAIT);
	return ret;
}
[/code]
The rest of my communications application uses curl library to communicate using OpenSSL PKCS#11 crypto engine.
If your application has nothing to do with OpenSSL and/or curl, I suggest to read PKCS#11 whitepaper.
https://www.cryptsoft.com/pkcs11doc/v220/pkcs11__all_8h.html
I managed to write a nice module that lists card's private keys, certificates, their labels and expiry dates by using only above documentation.

**Comment by asmjmisc** [comment]
@nased0 Thanks for that!

I understand that this reply is slightly delayed, but I managed to resolve my login issue - it turned out that the custom written software was deceiving the user (me, in this case) and manipulated the PIN before delivering it to the token, hence why my application, when sending the (presumably correct) PIN to the card, was unable to log in correctly.

I'll close the issue, as it's not really a fault in libp11 that was causing the confusion.
