### ISSUE TITLE
clean deletes .export files

### ISSUE THREAD

**Issue by bveldhoen** [OpenSC/libp11#240]
Using tag 0.4.8.
After running nmake /f Makefile.mak clean, the .export files are gone. This causes subsequent build failure(s), i.e. U1073.

**Comment by mtrojnar** [comment]
Interesting.  It shouldn't do that.  Could you include the output of "nmake /f Makefile.mak clean" from your machine?

**Comment by mouse07410** [comment]
I think I've experienced a similar problem on MacOS. Can't recall whether it was "make clean" or "make distclean".

**Comment by mtrojnar** [comment]
I reviewed both Windows and Unix makefiles, and tested Unix makefiles.  I could not find any makefile code that might remove the files.
Just to make sure: by ".export files" you mean `src/pkcs11.exports` and `src/libp11.exports`, right?

**Comment by bveldhoen** [comment]
It's nice to see your quick responses and dedication. Thank you!

Below the output of the command I ran:

```bat
C:\...\libp11-libp11-0.4.8\libp11-libp11-0.4.8>dir /S *.exports
 Volume in drive C is OSDisk
 Volume Serial Number is <deleted>

 Directory of C:\...\libp11-libp11-0.4.8\libp11-libp11-0.4.8\src

05-08-2018  11:53             1.019 libp11.exports
05-08-2018  11:53                20 pkcs11.exports
               2 File(s)          1.039 bytes

     Total Files Listed:
               2 File(s)          1.039 bytes
               0 Dir(s)  286.800.764.928 bytes free

C:\...\libp11-libp11-0.4.8\libp11-libp11-0.4.8>nmake /P /f Makefile.mak clean

Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.


MACROS:

<environment variables deleted>

INFERENCE RULES:

.asm.obj::
        commands:       $(AS) $(AFLAGS) /c $<

.asm.exe:
        commands:       $(AS) $(AFLAGS) $<

.c.obj::
        commands:       $(CC) $(CFLAGS) /c $<

.c.exe:
        commands:       $(CC) $(CFLAGS) $<

.cc.obj::
        commands:       $(CC) $(CFLAGS) /c $<

.cc.exe:
        commands:       $(CC) $(CFLAGS) $<

.cpp.obj::
        commands:       $(CPP) $(CPPFLAGS) /c $<

.cpp.exe:
        commands:       $(CPP) $(CPPFLAGS) $<

.cxx.obj::
        commands:       $(CXX) $(CXXFLAGS) /c $<

.cxx.exe:
        commands:       $(CXX) $(CXXFLAGS) $<

.rc.res:
        commands:       $(RC) $(RFLAGS) /r $<

.SUFFIXES: .obj .asm .c .cc .cpp .cxx .f .f90 .for .rc

TARGETS:

install::
        flags:
        dependents:
        commands:        @for %i in ( $(SUBDIRS) ) do  @cmd /c "cd %i && $(MAKE)
 /nologo /f Makefile.mak $@"

depend::
        flags:
        dependents:
        commands:        @for %i in ( $(SUBDIRS) ) do  @cmd /c "cd %i && $(MAKE)
 /nologo /f Makefile.mak $@"

all::
        flags:
        dependents:
        commands:

        flags:
        dependents:
        commands:        @for %i in ( $(SUBDIRS) ) do  @cmd /c "cd %i && $(MAKE)
 /nologo /f Makefile.mak $@"

clean::
        flags:
        dependents:
        commands:        @for %i in ( $(SUBDIRS) ) do  @cmd /c "cd %i && $(MAKE)
 /nologo /f Makefile.mak $@"


OpenSSL >= 1.1.0 detected (dynamic library)
        del libpkcs11.obj p11_attr.obj p11_cert.obj  p11_err.obj p11_ckr.obj p11
_key.obj p11_load.obj p11_misc.obj  p11_rsa.obj p11_ec.obj p11_pkey.obj p11_slot
.obj p11_front.obj eng_front.obj eng_back.obj eng_parse.obj eng_err.obj libp11.d
ll pkcs11.dll *.lib *.exp *.def *.res

C:\...\libp11-libp11-0.4.8\libp11-libp11-0.4.8>dir /S *.export
 Volume in drive C is OSDisk
 Volume Serial Number is <deleted>
File Not Found
```

Note that this is not a blocking issue for us at the moment, as we just clean by deleting and reextracting.

**Comment by mtrojnar** [comment]
Did you mean "dir /S *.exports"?

**Comment by bveldhoen** [comment]
Yes, I did, sry! Reverified it in my console and updated the output in my previous comment.

**Comment by dengert** [comment]
Should the `src/Makefile.mak` line 20: 
  `del $(OBJECTS) $(TARGETS) *.lib *.exp *.def *.res`
be 
 `del $(OBJECTS) $(TARGETS) *.lib *.exe *.def *.res`

If not, Is this a case of some command using the dos 8.3 format?
```
 Directory of C:\tmp\test

08/23/2018  09:23 AM    <DIR>                       .
08/23/2018  09:23 AM    <DIR>                       ..
08/23/2018  09:23 AM                 9 TEST~1.EXP   test.export
               1 File(s)              9 bytes
               2 Dir(s)  1,014,715,756,544 bytes free
```

In other words, the striped down `del *.exp` is deleting based on 8.3 format?

**Comment by dengert** [comment]
C:\tmp>cd test

C:\tmp\test>dir /S
 Volume in drive C has no label.
 Volume Serial Number is 94F0-F4DE

 Directory of C:\tmp\test

08/23/2018  09:23 AM    <DIR>          .
08/23/2018  09:23 AM    <DIR>          ..
08/23/2018  09:23 AM                 9 test.export
               1 File(s)              9 bytes

     Total Files Listed:
               1 File(s)              9 bytes
               2 Dir(s)  1,013,857,607,680 bytes free

C:\tmp\test>del *.exp

C:\tmp\test>dir /S
 Volume in drive C has no label.
 Volume Serial Number is 94F0-F4DE

 Directory of C:\tmp\test

08/25/2018  06:41 AM    <DIR>          .
08/25/2018  06:41 AM    <DIR>          ..
               0 File(s)              0 bytes

     Total Files Listed:
               0 File(s)              0 bytes
               2 Dir(s)  1,013,857,480,704 bytes free

C:\tmp\test>

**Comment by mtrojnar** [comment]
I could not reproduce it.  I guess the result may depend on the version of Windows and/or the filesystem that is used.  Could you submit a PR?

**Comment by dengert** [comment]
Is the line: `del $(OBJECTS) $(TARGETS) *.lib *.exp *.def *.res` correct?
Does libp11 produce and `exp` files? I would expect the line to have `*.exe`  not `.exp`

The  command window example of  `del`  was from Windows 10 pro 64 bit 1803 on the C: drive with NTFS. 

There is also this:
https://support.microsoft.com/en-us/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions


This site: 
https://fileinfo.com/extension/exp
says Visual Studio 2017 can open `exp` files.

**Comment by mtrojnar** [comment]
> Does libp11 produce and exp files?

Visual Studio does: https://msdn.microsoft.com/en-us/library/se8y7dcs.aspx

**Comment by dengert** [comment]
Well it still looks like a 8.3 issue. 
One way to prove it would be something like: 
```
diff --git a/src/Makefile.mak b/src/Makefile.mak
index 92d762a..86c0399 100644
--- a/src/Makefile.mak
+++ b/src/Makefile.mak
@@ -17,7 +17,9 @@ TARGETS = $(LIBP11_TARGET) $(PKCS11_TARGET)
 all: $(TARGETS)
 
 clean:
+       dir /X *.exp
        del $(OBJECTS) $(TARGETS) *.lib *.exp *.def *.res
+       dir /X *.exp
 
 .rc.res:
        rc /r /fo$@ $<
```
the dir /X should show the 8.3 and full names of any files to be deleted. 
Then to correct it change the del line to include specific .exp files rather then using a wildcard. for them.

Or use https://support.microsoft.com/en-us/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions on the volume or directory to avoid  the 8.3 issues.

**Comment by mtrojnar** [comment]
Would you guys be willing to submit a PR for this?

**Comment by bveldhoen** [comment]
Hi Michal,

It may take some time, but I'll see if I can reproduce it. I don't have access anymore to the environment where it occurred (as I'm working in a different place). It's really no big issue, perhaps it was something specific to the environment. Still, I'll try to repro. I'll get back to you on it.

Cheers,
Bram

**Comment by EasySec** [comment]
I face the same problem today (Windows 7-64, VS 2015), will make a PR
