### ISSUE TITLE
Windows: Unable to load Engine

### ISSUE THREAD

**Issue by ProLoDs** [OpenSC/libp11#241]
Hi,

i build the engine with MINGW64. Afterwards i tried to load the library with M2Crypto:

```python  
from M2Crypto import Engine
Engine.load_dynamic()
e = Engine.Engine('dynamic')
e.ctrl_cmd_string("SO_PATH","C:/msys64/usr/lib/engines/pkcs11.dll")
e.ctrl_cmd_string("ID","pkcs11")
e.ctrl_cmd_string("LIST_ADD","1")
e.ctrl_cmd_string("LOAD",None)
```
Afterwards i get the Error:
```
4988:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:106:filename(C:/msys64/usr/lib/engines/pkcs11.dll)
4988:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:161:
4988:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
4988:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:106:filename(C:/msys64/usr/lib/engines/pkcs11.dll)
4988:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:161:
4988:error:260B6084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:414:
```
The path is correct, i checked it with `os.path.isfile()`.  I also tried the pkcs11.dll and to seperate the path with "\\", same result. 

In the MINGW64 environment, i'm able to load it with the path `/usr/lib/engines/pkcs11.dll`. But when i try to run it outside of the MINGW64 environment with the Windows path `C:/msys64/usr/lib/engines/pkcs11.dll` it fails... 

I appreciate your help!

**Comment by mtrojnar** [comment]
Process Monitor should solve your mystery.
https://docs.microsoft.com/pl-pl/sysinternals/downloads/procmon
My guess is that the DLL produced by MINGW64 has some unmet dependencies.

**Comment by ProLoDs** [comment]
Hi,
Process Monitor didn't help. The problem was the 32/64 Bit libs. The solution was to recompile M2Crypto and libp11 against the openssl 32 1.10 bit version. I had the problem, that i was to lazy to compile them myself on windows (always a real pain on windows). After recompiling everything it worked. 

Lesson for me, stick to one architecture...
