### ISSUE TITLE
Question: what can I used insead of PKCS11_sign method?

### ISSUE THREAD

**Issue by anton-ryabkov** [OpenSC/libp11#244]
Hello,

I have used sing in my application, based on the sample "auth.c". But now, onUbuntu 18.04 I have a warning:
`
cc -O2 -g etsign.c -Wl,-Bstatic -lp11 -Wl,-Bdynamic -lcrypto -o etsign -ldl
etsign.c: In function ‘main’:
etsign.c:195:2: warning: ‘PKCS11_sign’ is deprecated: This function will be removed in libp11 0.5.0 [-Wdeprecated-declarations]
  rc = PKCS11_sign(NID_sha1, hash, RANDOM_SIZE, signature, &siglen,
  ^~
In file included from etsign.c:17:0:
/usr/include/libp11.h:449:32: note: declared here
 P11_DEPRECATED_FUNC extern int PKCS11_sign(int type,
`

Could you help, what can I should use instead of PKCS11_sign method?

Sample:
https://github.com/OpenSC/libp11/blob/0a2df89ba517bfbeaeadb81e42fe7bc3288b1985/examples/auth.c#L200-L201

**Comment by mtrojnar** [comment]
See: https://github.com/OpenSC/libp11/issues/52#issuecomment-173301890

**Comment by anton-ryabkov** [comment]
Thanks!
