### ISSUE TITLE
Should libp11 call C_Initialize when being forked?

### ISSUE THREAD

**Issue by jschmidb** [OpenSC/libp11#245]
I have a setup with Apache, mod_ssl, libp11, and opencryptoki. I see that C_Initialize is not called when libp11 is being forked by Apache. Refer to the standard here:
http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759985

> Consider a UNIX process P which becomes a Cryptoki application by calling C_Initialize, and then uses the fork() system call to create a child process C.  Since P and C have separate address spaces (or will when one of them performs a write operation, if the operating system follows the copy-on-write paradigm), they are not part of the same application.  **Therefore, if C needs to use Cryptoki, it needs to perform its own C_Initialize call**.  Furthermore, if C needs to be logged into the token(s) that it will access via Cryptoki, it needs to log into them even if P is already logged in, since P and C are completely separate applications.

Opencryptoki cannot be used in the fork unless C_Initialize is called again in the forked process.

**Comment by jschmidb** [comment]
I understand the OASIS spec like: If the forking process did a C_Initialize **before** the fork, then the forked process needs to call C_Initialize again. And I see that this is not done. I see that after the fork, the child directly calls C_SignInit, without a C_Initialize before.

I'm using libp11 0.4.8 cloned from master branch end of July together with Apache 2.5.1.

**Comment by mtrojnar** [comment]
Thank you for the details.  I can see how the EVP_PKEY interface allows for bypassing our atfork checks.  I'll fix it.

**Comment by mtrojnar** [comment]
https://github.com/OpenSC/libp11/commit/efce4defdf31ce74d905ae4dd47c6a36df532854 should fix it.  Can you check if it works for you?

**Comment by mtrojnar** [comment]
BTW: Windows build is currently broken.  I'll fix it.

**Comment by mtrojnar** [comment]
The best way is probably to include the PID of the invoking process in your trace.

**Comment by jschmidb** [comment]
ok, here is the trace with pids:

> libp11[243244]: bind_helper 
> libp11[243244]: PKCS11_get_rsa_method 
> libp11[243244]: load_privkey 
> libp11[243244]: pkcs11_CTX_load 
> libp11[243244]: pkcs11_CTX_load: calling C_Initialize 
> libp11[243244]: check_key_fork 
> libp11[243244]: PKCS11_get_rsa_method 
> libp11[243258]: load_privkey 
> libp11[243258]: pkcs11_CTX_reload 
> libp11[243258]: pkcs11_CTX_reload: calling C_Initialize 
> libp11[243258]: check_key_fork

**Comment by mtrojnar** [comment]
It looks good.  It creates a new process (243258), and it invokes C_Initialize() for this process.  Please let me know if there is any PKCS#11 function (names begin with C_) invoked by the newly created process before C_Initialize().

**Comment by jschmidb** [comment]
Yes, the two processes are created at httpd server startup. When I then connect using a Browser, a third process is created, but not initialized. The related opencryptoki trace goes into one of the already created trace files and shows a C_SignInit, followed by a C_Sign, but **should** go into a third trace file. 
I saw that my simple trace causes problems, because I'm writing all output from different processes to the same file, so I removed this trace. And it looks like I didn't hit the right functions. 
So the bottom line still is: a third process doesn't get initialized and first calls C_SignInit.

**Comment by mtrojnar** [comment]
I can't find any code path to C_SignInit that would not hit our atfork checks.  Can you set a breakpoint at C_SignInit and collect a stack backtrace from the third process?

**Comment by mtrojnar** [comment]
BTW: Apache pre-forks a process pool, so new processes are not necessarily created for each connecting client.

**Comment by mtrojnar** [comment]
My point is: Your third process does not call C_Initialize(), because it does not call Cryptoki at all.  Please reopen this issue if you find evidence the contrary.

**Comment by jschmidb** [comment]
I will come back to this in 3 weeks from now. Hope that I can provide the info you need. Thanks for your support!
