### ISSUE TITLE
Documentation for building on OSX

### ISSUE THREAD

**Issue by parasssh** [OpenSC/libp11#247]
The INSTALL.md does not have any information on building libp11 on OSX. 

Further, even the Unix build instructions reads 

> ./configure && make && sudo make install

but there is no configure in the top level directory of libp11.
Am I missing something?

**Comment by frankmorgner** [comment]
If you don't want to `./bootstrap` the development environment, use the [latest release](https://github.com/OpenSC/libp11/releases/download/libp11-0.4.9/libp11-0.4.9.tar.gz)

**Comment by frankmorgner** [comment]
INSTALL.md refers to the release tarball, which *includes* `configure`. Your system lacks some development dependencies, simply use the link I've posted above.

**Comment by parasssh** [comment]
I see. It was not obvious to me that the INSTALL.md only applies to the source code in the release tarball and not the git repo's master or other branches. Maybe we should clarify it.

**Comment by frankmorgner** [comment]
sure, feel free to make a pull request
