### ISSUE TITLE
Store certificate doesn't work on SafeNet eToken5110

### ISSUE THREAD

**Issue by FdLSifu** [OpenSC/libp11#250]
I am trying to store a X509 certificate within a SafeNet eToken5110 but i get "Incomplete Template" error.

After investigation on PKCS11 standard, I have found out that CKA_SUBJECT is a mandatory attribute for certificate object creation:
reference: http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.pdf 
section: 4.6.3 ; table 19
extract : CKA_SUBJECT *1 => *1 MUST be specified when the object is created

I have patched p11_cert.c to add the CKA_SUBJECT attribute to the template and it does work well.

Here is an extract of the patch within pkcs11_store_certificate function:

```
X509_NAME *name;
const unsigned char* der_buf;
size_t der_buf_len = 0;

name = X509_get_subject_name(x509);
X509_NAME_get0_der(name,&der_buf,&der_buf_len);
pkcs11_addattr(attrs + n++, CKA_SUBJECT, der_buf, der_buf_len);
```

**Comment by mtrojnar** [comment]
Your solution is very nice, but it requires OpenSSL 1.1.0 or later.
Could you please check whether https://github.com/OpenSC/libp11/commit/2a7888197a1aeec0968b50ce396d04d745328877 does the job for you?

**Comment by FdLSifu** [comment]
Simple & efficient. It does the job!
Thank you
