### ISSUE TITLE
Certificate X509 mandatory attributes are not loaded

### ISSUE THREAD

**Issue by FdLSifu** [OpenSC/libp11#251]
While reading PKCS11 2.40, a certificate CKC_X_509 supports following fieldd that are X509 mandatory :
- CKA_ISSUER
- CKA_SERIAL_NUMBER
- CKA_HASH_OF_SUBJECT_PUBLIC_KEY
- CKA_HASH_OF_ISSUER_PUBLIC_KEY
- CKA_NAME_HASH_ALGORITHM

CKA_NAME_HASH_ALGORITHM is security relevant cause if a certificate have been create using SHA-256, pkcs11 set the hash algorithm to default which is SHA-1. We know that SHA-1 is deprecated and due to missing attributes handling we decrease the hash length.

Should I present some code ?

**Comment by mtrojnar** [comment]
Sure.  Please submit a PR.

**Comment by mtrojnar** [comment]
Implemented in https://github.com/OpenSC/libp11/pull/252
