### ISSUE TITLE
 can't build x86_64-pc-msys shared library unless -no-undefined is specified

### ISSUE THREAD

**Issue by deekshith565** [OpenSC/libp11#255]
I'm using MSYS2 installation procedure to install libp11 in windows, I have done following steps without any error,

To build libp11, download and install msys2-i686-*.exe from https://msys2.github.io

then start a MSYS2 MSYS console from the Start menu and use:

pacman -S git pkg-config libtool autoconf automake make gcc openssl-devel

git clone https://github.com/OpenSC/libp11.git

cd libp11

autoreconf -fi

./configure --prefix=/usr/local

After this when I run make command I get below error,

$ make
Making all in src
make[1]: Entering directory '/home/chowdar1/libp11/src'
make  all-am
make[2]: Entering directory '/home/chowdar1/libp11/src'
  CCLD     pkcs11.la
libtool:   error: can't build x86_64-pc-msys shared library unless -no-undefined is specified
make[2]: *** [Makefile:546: pkcs11.la] Error 1
make[2]: Leaving directory '/home/chowdar1/libp11/src'
make[1]: *** [Makefile:417: all] Error 2
make[1]: Leaving directory '/home/chowdar1/libp11/src'
make: *** [Makefile:465: all-recursive] Error 1

Can anyone please help me?

**Comment by mtrojnar** [comment]
Sure.  Can you share the output of your ./configure?

**Comment by mtrojnar** [comment]
@deekshith565 Please reopen this issue if my fix doesn't work for you.

**Comment by mkschreder** [comment]
What was the solution?

**Comment by mtrojnar** [comment]
https://github.com/OpenSC/libp11/commit/87a9176c817408da8baccef0c4e44ad6070f07c2
