### ISSUE TITLE
Couldn't load the shared libraries of libpkcs11

### ISSUE THREAD

**Issue by deekshith565** [OpenSC/libp11#256]
OpenSSL> engine dynamic -pre SO_PATH:C:\msys64\usr\lib\engines\libpkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\libpkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
28112:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\libpkcs11.dll)
28112:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
28112:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\Program
28112:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
28112:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:
28112:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(Z:\extlib\_openssl11_\lib\engines-1_1\Files\\OpenSC)
28112:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
28112:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
28112:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=Files\OpenSC
28112:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(Z:\extlib\_openssl11_\lib\engines-1_1\Project\OpenSC\pkcs11\\opensc-pkcs11.dll)
28112:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
28112:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
28112:error:2606A074:engine routines:ENGINE_by_id:no such engine:crypto/engine/eng_list.c:339:id=Project\OpenSC\pkcs11\opensc-pkcs11.dll
error in engine

Can anyone help me with this error?

**Comment by deekshith565** [comment]
Yes I tried it, I tried following 2 ways, I get the same error,

1)
OpenSSL> engine dynamic -pre "SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre "MODULE_PATH:C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll"
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
13280:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
13280:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
13280:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\Program Files\OpenSC Project\OpenSC\pkcs11\opensc-pkcs11.dll
13280:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
13280:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:


2)
OpenSSL> engine dynamic -pre "SO_PATH:C:\\msys64\\usr\\lib\\engines\\pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre "MODULE_PATH:C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll"
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\\msys64\\usr\\lib\\engines\\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
13280:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\\msys64\\usr\\lib\\engines\\pkcs11.dll)
13280:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
13280:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\\Program Files\\OpenSC Project\\OpenSC\\pkcs11\\opensc-pkcs11.dll
13280:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
13280:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:

**Comment by deekshith565** [comment]
@mtrojnar please any help?

**Comment by mtrojnar** [comment]
IMHO this issue is about passing file names with spaces to the OpenSSL CLI.  It is by no means specific to libp11.

**Comment by deekshith565** [comment]
@mtrojnar Yeah I already tried path without spaces, it didn't help.

**Comment by mtrojnar** [comment]
It's great that you tried it.  Please copy+paste the results here (file names without spaces, no double quotes).

**Comment by deekshith565** [comment]
OpenSSL> engine dynamic -pre "SO_PATH:C:\msys64\usr\lib\engines\libpkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre "MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll"
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\libpkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
21872:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\libpkcs11.dll)
21872:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
21872:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
21872:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
21872:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:

**Comment by mtrojnar** [comment]
Try harder.  Without double quotes this time.

**Comment by deekshith565** [comment]
OpenSSL> engine dynamic -pre SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\msys64\usr\lib\engines\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
21872:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
21872:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:161:
21872:error:260B6084:engine routines:dynamic_load:dso not found:crypto/engine/eng_dyn.c:414:
[Failure]: MODULE_PATH:C:\SoftHSM2\lib\softhsm2.dll
21872:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:85:
21872:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:263:
OpenSSL>

**Comment by deekshith565** [comment]
I really have no clue about this error...

**Comment by dengert** [comment]
```
21872:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto/dso/dso_win32.c:106:filename(C:\msys64\usr\lib\engines\pkcs11.dll)
```
would indicate in OpenSSL  crypto/dso/do_win32.c  the windows LoadLibraryA failed in line 105:
```
105     h = LoadLibraryA(filename);
106     if (h == NULL) {
107         DSOerr(DSO_F_WIN32_LOAD, DSO_R_LOAD_FAILED);
108         ERR_add_error_data(3, "filename(", filename, ")");
109         goto err;

Could be be some dependent library issue. 
Have a look at: https://stackoverflow.com/questions/1993673/what-is-the-equivalent-of-linuxs-ldd-on-windows
then use one of the tools to see what dlls are needed by C:\msys64\usr\lib\engines\pkcs11.dll

Could it be 32 bit vs 64?

**Comment by deekshith565** [comment]
@mtrojnar Actually OpenSSL or SoftHSM I have built using Visual Studio, where as libp11 using MSYS2, could this be any reason? I'm trying to build libp11 using Visual studio I get some errors there, for which I will create new issue now.

**Comment by grant100** [comment]
@elliotmtx did you ever resolve this?
