### ISSUE TITLE
Unresolved external symbols while building libp11 

### ISSUE THREAD

**Issue by deekshith565** [OpenSC/libp11#257]
I'm building libp11 dll in Windows using MSVC installation, but when I run "nmake /f Makefile.mak OPENSSL_DIR=C:\build\bin\openssl-1.1.0h-x64 BUILD_FOR=WIN64" I get errors as unresolved externals

`C:\build\src\libp11-0.4.9>nmake /f Makefile.mak OPENSSL_DIR=C:\build\bin\openssl-1.1.0h-x64 BUILD_FOR=WIN64

Microsoft (R) Program Maintenance Utility Version 14.15.26730.0
Copyright (C) Microsoft Corporation.  All rights reserved.

OpenSSL >= 1.1.0 detected (dynamic library)
        link /NOLOGO /INCREMENTAL:NO /MACHINE:X64 /MANIFEST:NO /NXCOMPAT /DYNAMICBASE  /dll /def:libp11.def /implib:libp11.lib /out:libp11.dll  libpkcs11.obj p11_attr.obj p11_cert.obj  p11_err.obj p11_ckr.obj p11_key.obj p11_load.obj p11_misc.obj  p11_rsa.obj p11_ec.obj p11_pkey.obj p11_slot.obj p11_front.obj  p11_atfork.obj "C:\build\bin\openssl-1.1.0h-x64\lib\libcrypto.lib" user32.lib advapi32.lib crypt32.lib gdi32.lib libp11.res
   Creating library libp11.lib and object libp11.exp
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_ioctlsocket referenced in function BIO_socket_ioctl
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_getsockname referenced in function BIO_sock_info
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_getsockopt referenced in function BIO_sock_error
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_getsockopt
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_ntohs referenced in function BIO_get_port
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_ntohs
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_gethostbyname referenced in function BIO_gethostbyname
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function BIO_sock_init
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_WSACleanup referenced in function bio_sock_cleanup_int
libcrypto.lib(b_sock.obj) : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function BIO_accept
libcrypto.lib(bss_sock.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
libcrypto.lib(b_addr.obj) : error LNK2019: unresolved external symbol __imp_getaddrinfo referenced in function BIO_lookup
libcrypto.lib(b_addr.obj) : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function BIO_ADDRINFO_free
libcrypto.lib(b_addr.obj) : error LNK2019: unresolved external symbol __imp_getnameinfo referenced in function addr_strings
libcrypto.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_recv referenced in function sock_read
libcrypto.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_send referenced in function sock_write
libcrypto.lib(bss_sock.obj) : error LNK2019: unresolved external symbol __imp_WSASetLastError referenced in function sock_write
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_accept referenced in function BIO_accept_ex
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_bind referenced in function BIO_listen
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function BIO_accept_ex
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_connect referenced in function BIO_connect
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_listen referenced in function BIO_listen
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_setsockopt referenced in function BIO_connect
libcrypto.lib(b_sock2.obj) : error LNK2019: unresolved external symbol __imp_socket referenced in function BIO_socket
libp11.dll : fatal error LNK1120: 21 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: 'for' : return code '0x2'
Stop.`

Any help please.

And don't we need to run any configure file before make?

**Comment by deekshith565** [comment]
Any help please.

**Comment by mouse07410** [comment]
It seems to me that the libraries that OpenSSL libs are supposed to be linked against, are not found when you're building libp11.

The only thing that comes to mind is trying to build everything with the same toolchain. Unless you're already doing that. And Manning sure all the relevant libraries (including the system libraries) are given to the libp11 build.

**Comment by mtrojnar** [comment]
Apparently linking against your libcrypto generates errors about unmet Winsock dependencies.  I don't think there is anything we can do about it in libp11.
