### ISSUE TITLE
PKCS11_get_private_key returned NULL

### ISSUE THREAD

**Issue by gaia** [OpenSC/libp11#262]
In Ubuntu 18.04.1, `openssl engine pkcs11 -t -c` properly shows

```
(pkcs11) pkcs11 engine
 [RSA, rsaEncryption, id-ecPublicKey]
     [ available ]
```

The purpose is to certify PDFs using the Safenet Token (Gemalto 5110) loaded with an [AATL](https://helpx.adobe.com/acrobat/kb/approved-trust-list2.html) chained cert in slot 0:

```
$ pkcs11-tool --module /usr/lib/libeTPkcs11.so --login -O
Using slot 0 with a present token (0x0)
Logging in to "pdfsigner".
Please enter User PIN:
Private Key Object; RSA
  label:
  ID:         hexstringblah
  Usage:      decrypt, sign, unwrap
Certificate Object; type = X.509 cert
  label:      te-123456-123456aa
  ID:         hexstringblah
Certificate Object; type = X.509 cert
  label:
Certificate Object; type = X.509 cert
  label:
Certificate Object; type = X.509 cert
  label:
Certificate Object; type = X.509 cert
  label:
```

When I try to sign with `openssl pkeyutl -sign -keyform ENGINE -engine pkcs11 -inkey "pkcs11:object=te-123456-123456aa;type=cert;pin-value=password" -in certifyme.pdf -out certifyme.pdf` I am getting

```
engine "pkcs11" set.
No private keys found.
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
139808273490368:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:876:
139808273490368:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:78:
unable to load Private Key
pkeyutl: Error initializing context
```

AFAIK the cmd should not request the PK, but only to have the token sign the request. Do I have an incorrect parameter in pkeyutl ?

**Comment by erick-orozco** [comment]
Hi, 

I'm not the developer of this repo, but I'm currently working on a project that requires it. The -inkey param specifies the private key but the pkcs11 URI is telling it to look for a cert, so it sounds reasonable that is returning an error. Try changing the type to private. 

`pkcs11:object=te-123456-123456aa;type=private;pin-value=password`

**Comment by mtrojnar** [comment]
Indeed.  Signing requires a private key, and not a certificate.

**Comment by gaia** [comment]
Thanks @mtrojnar. What would the command be to sign if I don't have access to the private key, it is locked inside the token?

**Comment by mtrojnar** [comment]
There is an example of using the private key in https://github.com/OpenSC/libp11/blob/master/README.md.
