### ISSUE TITLE
In pkcs11_CTX_new loaded PKCS11 strings are not  unloaded in pkcs11_CTX_free

### ISSUE THREAD

**Issue by lkczetenyi** [OpenSC/libp11#264]
In \src\p11_load.c line 31 

in function:  `PKCS11_CTX *pkcs11_CTX_new(void) `
31. `ERR_load_PKCS11_strings(); `
is called.

in function:  `void pkcs11_CTX_free(PKCS11_CTX *ctx)` 
maybe these loaded strings should be unloaded.

**Comment by mtrojnar** [comment]
An application may load more than one instance of the pkcs11 engine, thus initializing many PKCS11_CTX objects.  Unloading the error strings as soon as the first PKCS11_CTX object is removed does not sound like a good idea.

**Comment by lkczetenyi** [comment]
Thanks, I see. 
For us it is a problem because we have a .dll which is loaded and unloaded in case of a smartcard inserted or removed and it calls create context and free in every iteration. 
And it is leaking and after a while our application crashes.

I put ERR_unload_PKCS11_strings() to external interface and call it after freeing context and it looks OK now.

**Comment by mtrojnar** [comment]
@lkczetenyi I modified the code to only load error strings once.  Does it work for you?

**Comment by lkczetenyi** [comment]
I think it doesn't because 
in 
`ERR_load_P11_strings()` and 
`ERR_load_CKR_strings()`
there are similar solutions to avoid multiple loading of error strings but it does not work for us.

we load and unload our dll so `CKR_error_init` and `P11_error_init` does not keep its value. 
So memory leak remains on unloading dll.

**Comment by mtrojnar** [comment]
Honestly I'm not sure about the proper way to initialize OpenSSL error strings from a shared library that gets unloaded and then loaded again.

What is the stack backtrace of your crash?  Fixing OpenSSL seems to be a better idea than implementing a workaround in each library that uses OpenSSL.

**Comment by frankmorgner** [comment]
On Windows, you can use `DllMain`, which looks something like this:
https://github.com/OpenSC/OpenSC/blob/b01ca2dcc9bf4a19b13e2f623f974e455390435a/src/pkcs11/pkcs11-global.c#L220-L243

**Comment by mtrojnar** [comment]
@frankmorgner I'd prefer to identify and fix the root cause of the OpenSSL crash if possible (KISS principle).  I'll consider implementing platform-specific workarounds as a last resort.  Anyway, thank you for the idea for implementing a Windows-specific workaround.

**Comment by lkczetenyi** [comment]
My simpliest scenario is something like this:

```
while () {

-  load myDLL
-  in myDll call pkcs11_CTX_new()  - ( ERR_load_PKCS11_strings() )
-  in myDll  call pkcs11_CTX_free()
-  unload myDll

}
```

after some iteration I can see that memory usage is increasing because **pkcs11_CTX_new()** calls 
**ERR_load_PKCS11_strings()**
but 
there is no unload in **pkcs11_CTX_free()**

For my problem one solution could be if  **pkcs11_CTX_new()** would **not** be responsible for loading these error strings - it could be put into some kind of initPKCS11() funcion which should be called before making any context. 

So in this case my scenario could be something like this:
1.
```
while () {

 - load myDLL
 - in myDll call initPKCS11() - ( ERR_load_PKCS11_strings())
 - in myDll call pkcs11_CTX_new()
 - in myDll  call pkcs11_CTX_free()
 - in myDll call destroyPKCS11() - (ERR_unload_PKCS11_strings())
 - unload myDll

}
```

Or the other solution which is better for backward compatibility:

2. 

```
while () {

 - load myDLL
 - in myDll call pkcs11_CTX_new() - ( ERR_load_PKCS11_strings())
 - in myDll  call pkcs11_CTX_free()
 - in myDll  call ERR_unload_PKCS11_strings()
 - unload myDll

}
```

**Comment by dengert** [comment]
Looking at OpenSSL 1.0.2 and 1.1 `cpt_err.c` has:
```
 68  int ERR_load_CRYPTO_strings(void)
 69 {
 70 #ifndef OPENSSL_NO_ERR
 71     if (ERR_func_error_string(CRYPTO_str_functs[0].error) == NULL) {
 72         ERR_load_strings_const(CRYPTO_str_functs);
 73         ERR_load_strings_const(CRYPTO_str_reasons);
 74     }
 75 #endif
```
But  libp11 ` p11_err.c`:
```
 60 int ERR_load_P11_strings(void)
 61 {
 62     if (P11_lib_error_code == 0)
 63         P11_lib_error_code = ERR_get_next_error_library();
 64 
 65     if (P11_error_init) {
 66         P11_error_init = 0;
 67 #ifndef OPENSSL_NO_ERR
 68         ERR_load_strings(P11_lib_error_code, P11_str_functs);
 69         ERR_load_strings(P11_lib_error_code, P11_str_reasons);
 70 #endif
```
It looks like  `ERR_load_P11_strings`  and ` ERR_load_CKR_strings` should be using `ERR_func_error_string` to test if the strings are already loaded. 

The unload routines look like they could use an update too.

**Comment by mtrojnar** [comment]
@lkczetenyi Have I correctly understood that your crash is in fact an out-of-memory condition?  How often do you unload and reload the engine again?  Is re-loading the engine the only way for your application to become aware of a smartcard insertion or removal?  It shouldn't be.  I think we should be fixing the root cause instead of implementing a workaround for compatibility with your workaround.

**Comment by mtrojnar** [comment]
Please reopen the issue if you're interested in further investigation.
