### ISSUE TITLE
unable to load module

### ISSUE THREAD

**Issue by gaangshi** [OpenSC/libp11#265]
Hi.

I trying to use pkcs11 engine for connect OpenSSL and TEE.
I already have TEE CA which is convert PKCS#11 APIs to TEE Global Platform APIs. (Cryptoki module)
(of coursely TA)

I already cross-compiled OpenSSL, libp11 things, and cryptoki module(TEE CA) on TEE normal world.

when I configure Openssl engine with

$ openssl engine -t dynamic -pre SO_PATH:/usr/lib/pkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/path/path/CA.so 
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib/pkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/path/path/CA.so
Loaded: (pkcs11) pkcs11 engine
Unable to load module /path/path/CA.so
    [ Unavailable]

Is there anything that I missed?
I was trying to fix it, but I don't have any idea now.

I appreciate your help!

**Comment by dengert** [comment]
Is the directory  really `/path/path` in ` /path/path/CA.so` 
can you run `ldd /path/path/CA.so` to see what it is missing? 
You may need LD_LIBRARY_PATH= to pick up any other libs needed by `CA.so`

**Comment by mtrojnar** [comment]
There was no reply from @gaangshi for two weeks.  I'm closing this issue.
