### ISSUE TITLE
Unable to enumerate certificates

### ISSUE THREAD

**Issue by frederikbosch** [OpenSC/libp11#269]
While trying to use [osslsigncode](https://github.com/develar/osslsigncode) for code signing, I am getting this error.

```log
Unable to enumerate certificates
PKCS11_get_private_key returned NULL
Failed to load private key [my id here]4:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:

Failed
```

The first error comes from this package so I am wondering what it means. I am using the latest Ubuntu Xenial packages because osslsigncode is not OpenSSL 1.1 ready. What could the error mean?

If I run `pkcs11-tool --module /lib/libeToken.so.10  -l -O` I am able to see the objects. The `ID: ` that I see is the one that I pass to `osslsigncode`.

Now I understand you are not one responsible for `osslsigncode` but maybe you can point into the right direction what the errors mean.

**Comment by mtrojnar** [comment]
I happen to also be the maintainer of `osslsigncode`: https://github.com/mtrojnar/osslsigncode

The way I use it is:
```
$ osslsigncode sign -verbose \
    -pkcs11engine /usr/lib/engines-1.1/pkcs11.so \
    -pkcs11module /opt/proCertumSmartSign/libcrypto3PKCS.so \
    -certs certs.pem \
    -key 'pkcs11:object=12345678-1234-1234-1234-123456789012' \
    -pass xxxx -h sha256 -t http://time.certum.pl/ \
    -in input.exe -out output.exe
```
`osslsigncode` currently does not support reading certificates from engines.  Should it?

**Comment by mtrojnar** [comment]
The latest Ubuntu package supports OpenSSL 1.1: https://packages.ubuntu.com/disco/osslsigncode
You may wish to either update your Ubuntu or to find a backported package.

**Comment by frederikbosch** [comment]
@mtrojnar I was not aware of your version of osslsigncode. There are (too) many forks... I cloned it on a Ubuntu Bionic machine and then ran `osslsigncode`. Now I am getting.

```log
could not load the shared library:../crypto/dso/dso_dlfcn.c:117:filename(/usr/lib/ssl/engines/libpkcs11.so)
```

I already tried to reinstall openssl and libssl-dev (`sudo apt-get install --reinstall openssl libssl-dev`) but no success. What am I missing? Thanks for you help, much appreciated!

**Comment by mtrojnar** [comment]
The error says that you don't have our pkcs11 engine built and installed for your version of OpenSSL.

**Comment by frederikbosch** [comment]
I copied (without thinking) the URI to pkcs11engine from your example while on my system it was located at `/usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so`. Thanks, without you directing me towards your repository I would still be trying!

**Comment by mouse07410** [comment]
@mtrojnar

> 'osslsigncode' currently does not support reading certificates from engines. Should it?

I'd say yes, it would be better if it did.

**Comment by mtrojnar** [comment]
@mouse07410 I'm not sure.  PKCS#11 is not a convenient place to store certificate chains.  The UI for this would probably be even more painful than just providing a file.

**Comment by mouse07410** [comment]
@mtrojnar I'm not sure either. But from my experience with smart cards and tokens, it is convenient to be able to access everything on it (private keys, public keys, certs) with the same tool. 

But mainly I've done that with OpenSSL+libp11. Don't know how easy or hard it would be to translate that experience and use case to 'osslsigncode', and whether it would make sense.
