### ISSUE TITLE
Error "Missing CKA_ALWAYS_AUTHENTICATE attribute"

### ISSUE THREAD

**Issue by AlvaroROCHA** [OpenSC/libp11#272]
For cards with private keys witch doesn't need a re-authentication, sign process always fails with the error "Missing CKA_ALWAYS_AUTHENTICATE attribute"
There is a misundestanding with the CKA_ALWAYS_AUTHENTICATE attribute added test case.

_According to the PKCS#11 spécifications : 
The CKA_ALWAYS_AUTHENTICATE attribute **can** be used to force **re-authentication** (i.e. force the user to provide a PIN) for each use of a private key. 
“Use” in this case means a cryptographic operation such as sign or decrypt. This attribute **may** only be set to CK_TRUE when CKA_PRIVATE is also CK_TRUE._

cf. Diff : https://github.com/OpenSC/libp11/commit/58230eb4869fad540fab450b79f325ca76d2320e#diff-9e3725a6366a651da7526b72f161e585

**Comment by mtrojnar** [comment]
libp11 never returns a "Missing CKA_ALWAYS_AUTHENTICATE attribute" **error**.  This text is a debug message, which does not indicate an error condition.

**Comment by marckleinebudde** [comment]
FTR: fixed in https://github.com/OpenSC/libp11/commit/58230eb4869fad540fab450b79f325ca76d2320e

**Comment by dengert** [comment]
What the spy log shows is your PKCS11 module does not understand CKA_ALWAYS_AUTHENTICATE
```
34: C_GetAttributeValue
2018-08-22 11:04:50.838
[in] hSession = 0x801
[in] hObject = 0x8
[in] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  0000000001e89220 / 1
[out] pTemplate[1]:
    CKA_ALWAYS_AUTHENTICATE  0000000001e89220 / 18446744073709551615
Returned:  18 CKR_ATTRIBUTE_TYPE_INVALID
```
If the module had any keys that had  `CKA_ALWAYS_AUTHENTICATE=TRUE`, it should be able to respond to the  the `C_GetAttributeValue`  libp11 interprets the failure as false, and continues on.
