### ISSUE TITLE
bring the engine to openssl upstream

### ISSUE THREAD

**Issue by nmav** [OpenSC/libp11#276]
Given that there is discussion on openssl upstream about a PKCS#11 engine, shouldn't `engine_pkcs11`
 from this project move upstream? This engine has a much bigger installed base and has received much better testing than a new proposal.

https://github.com/openssl/openssl/pull/8200

**Comment by mtrojnar** [comment]
I don't think this is the right place to propose changes in OpenSSL.

**Comment by nmav** [comment]
This is actually proposing a change to engine_pkcs11, by moving from an independent project under openssl.

**Comment by mtrojnar** [comment]
I'm certainly **not** interested in migrating the project from OpenSC to OpenSSL.  Would OpenSSL be interested in hosting this project?  I don't think they do.

**Comment by nmav** [comment]
I do not believe this is a new proposal. This had started with the relicense of the libp11 project that happened few years ago by @dwmw2. The upstream openssl response was at that time:
https://www.mail-archive.com/openssl-dev@openssl.org/msg42843.html

but you can also see the input from upstream developers in the pull requested I link at.

**Comment by frankmorgner** [comment]
I think relicensing engine_pkcs11 as Apache-2.0 and moving it to OpenSSL would be ideal for both sides. The OpenSSL project would get code that's widely used and tested and you, @mtrojnar, would get way more assistance in maintenance and adding new features.

The OpenSSL project is the right place for an OpenSSL PKCS#11 engine. Since I've only contributed few pieces of code, it's not on me to decide, but if https://github.com/openssl/openssl/pull/8200 gets accepted, then engine_pkcs11 would certainly be obsolete very soon.

**Comment by frankmorgner** [comment]
See also https://github.com/openssl/openssl/pull/8200#issuecomment-467375533

**Comment by mtrojnar** [comment]
Any volunteers to take responsibility for this task?

**Comment by frankmorgner** [comment]
It's on you and the rest of us to decide about the license. The rest is communication with the OpenSSL developers.

**Comment by mtrojnar** [comment]
https://github.com/OpenSC/libp11/issues/233#issuecomment-445905208

**Comment by frankmorgner** [comment]
This concerns the example files only.

Would **you**, @mtrojnar , agree on relicensing the code under OpenSSL's library? If so, we (yes, I would write such a comment) could just go and suggest the transfer of the code.

**Comment by mtrojnar** [comment]
@frankmorgner It's a little bit more complex.
1. Do I agree to re-license **the** code.
I'm not the copyright holder of **the** code, so I can neither agree nor disagree to re-license it.  I **do** agree on re-license **my** contributions to the code to Apache License Version 2.0.
2. Do I back the project takeover up?
No, I do not.  https://github.com/OpenSC/libp11/issues/276#issuecomment-464706014
3. Am I willing to support libp11 under OpenSSL?
No, I am not.

**Comment by mtrojnar** [comment]
I guess only tests and examples were discussed in https://github.com/OpenSC/libp11/issues/233 because only tests and examples were considered problematic.  But you are right: the problem is bigger than just tests and examples.
