### ISSUE TITLE
Missing ec-no-pubkey.sh file in 0.4.10 release tarball

### ISSUE THREAD

**Issue by ansasaki** [OpenSC/libp11#281]
The file [1] is missing in 0.4.10 release tarball. This makes the test suite to fail with an error in ec-check-privkey.softhsm test.

[1] https://github.com/OpenSC/libp11/blob/master/tests/ec-no-pubkey.sh

**Comment by mtrojnar** [comment]
I re-uploaded the release tarball/zip.  Thank you for reporting this issue.  I forgot to `make distckeck` the release...
