### ISSUE TITLE
Configure error libcrypto >= 0.9.8 is required

### ISSUE THREAD

**Issue by chine369** [OpenSC/libp11#282]
Hi,

In order to use a Nitrokey HSM, I need compile a engine_pkcs11.so. Accroding to installation instruction, I excute ./configure && make && sudo make install.

During the configure process, it warns:

checking for OPENSSL... no
configure: error: libcrypto >= 0.9.8 is required

My environment is VMware/Ubuntu 18.04 LTS/Openssl 1.1.0g. The libcrypto.so version under /usr/lib/x86_64-linux-gnu is 1.1.0 too.

How can I solve this problem? Or is there any engine_pkcs11.so binary? Thanks.

**Comment by mtrojnar** [comment]
This is your first time building an application from sources, right?  Yes, you need OpenSSL to build libp11. Not just libraries. Also headers. Those are in separate "-dev" packages on Debian-based distros, such as Ubuntu.

**Comment by chine369** [comment]
> This is your first time building an application from sources, right? Yes, you need OpenSSL to build libp11. Not just libraries. Also headers. Those are in separate "-dev" packages on Debian-based distros, such as Ubuntu.

Yes I'm a beginner. Do you mean libssl-dev? I had installed it but useless.
By the way, I download openssl source code and build openssl again today,but it doesn't helpful.

**Comment by chine369** [comment]
> This is your first time building an application from sources, right? Yes, you need OpenSSL to build libp11. Not just libraries. Also headers. Those are in separate "-dev" packages on Debian-based distros, such as Ubuntu.

I have resolve the problem, thanks very much.
The reason is libp11 configure can't find libcrypto version. I make 2 changes:
1. install pkg-config
2. export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/
I think 2 is the key step.
