### ISSUE TITLE
Support for ssl_client_engine

### ISSUE THREAD

**Issue by adp162** [OpenSC/libp11#285]
Sorry if I butcher some things - still getting a hang on how the various pieces fit together.

I've been trying to get client authentication working (for a TLS mutually authenticated connection) when the client's private key and cert are stored on a PKCS11 compatible token (testing with openCryptoki's soft token).

It seems that libp11 doesn't implement functionality that openSSL expects in order to do this. In particular ENGINE_get_ssl_client_cert_function. I do see in engine.h (from libp11) a ctx_load_pubkey and ctx_load_privkey which I think is why things like:
`openssl dgst -sha256 -engine pkcs11 -keyform engine -sign "pkcs11:token=mytok;object=test_key;type=private;pin-value=1234" -out test.sig test.bin`
work while:
`openssl s_client -connect <myhost>:443 -ssl_client_engine pkcs11`
gives this error:
`PKCS#11: Initializing the engine
Found 2 slots
Error setting client auth engine
140697124869784:error:1412214B:SSL routines:SSL_CTX_set_client_cert_engine:no client cert method:ssl_sess.c:1264:`

Am I understanding this correctly? And if so, any sense on the effort required to get this working?

**Comment by mtrojnar** [comment]
Our engine does not currently support automagic selection of client certificates.
You can still select the private key manually:
```
openssl s_client \
    -connect <myhost>:443 \
    -engine pkcs11 \
    -keyform engine \
    -key "pkcs11:token=mytok;object=test_key;type=private;pin-value=1234" \
    -cert test_key.crt
```
Adding ssl_client_engine support is not trivial, but it seems feasible.  How badly do you need it?

**Comment by adp162** [comment]
Gotcha - I think as long as I have a workaround to do mutual authentication with the private key inside my token then that will work. For some more context I've been using s_client code as a reference for how to do this using libssl. I'll play around some more and see if your suggested solution will work.

I'm curious though, is mutual authentication just not a typical use case supported with a token or do people generally do it the way you mentioned?

**Comment by dengert** [comment]
Most people would use a browser like FireFox that uses the Mozilla NSS that can do mutual authentication using pkcs11.  Or on Windows a Microsoft browser and the OpenSC minidriver.  

For example: https://piv.idmanagement.gov/details/ Using OpenSC mindriver or OpenSC pkcs11 you can uses any of the OpenSC supported cards.

**Comment by adp162** [comment]
@mtrojnar Thanks - I think doing what you suggested will work fine for my use case - basically the cert will be held on the filesystem and the key will be inside the HSM. I'll leave it up to you whether to keep this open or close it. If I have some time I may play around with building that support just to understand how OpenSSL uses it.

@dengert Thanks for the link - actually quite an interesting read on how the government manages their PKI.
