### ISSUE TITLE
[Windows] libp11.dll fails to link against libcrypto.lib with unresolved symbols

### ISSUE THREAD

**Issue by chrisdoherty4** [OpenSC/libp11#289]
# Overview
Linking with a static OSL > 1.1.0 crypto library results in unresolved symbols. The symbols are network related and are all found in the ws2_32 library. 

The error is in `make.rules.mak` l44; it should include ws2_32. 

Related issue: #257 

### Link line
```
link /NOLOGO /INCREMENTAL:NO /MACHINE:X64 /MANIFEST:NO /NXCOMPAT /DYNAMICBASE  /dll /def:libp11.def /implib:libp11.lib /out:libp11.dll  libpkcs11.obj p11_attr.o
bj p11_cert.obj  p11_err.obj p11_ckr.obj p11_key.obj p11_load.obj p11_misc.obj  p11_rsa.obj p11_ec.obj p11_pkey.obj p11_slot.obj p11_front.obj  p11_atfork.obj "C:\work\
libp11\build\externals\OpenSSL1.1\lib\libcrypto.lib" user32.lib advapi32.lib crypt32.lib gdi32.lib libp11.res
```

### Unresolved symbols
```
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_getnameinfo
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_freeaddrinfo
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_htons
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_getservbyname
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_inet_ntoa
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_ntohs
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_getaddrinfo
libcrypto.lib(b_addr.obj) : error LNK2001: unresolved external symbol __imp_gethostbyname
libcrypto.lib(b_sock.obj) : error LNK2001: unresolved external symbol __imp_ioctlsocket
libcrypto.lib(b_sock.obj) : error LNK2001: unresolved external symbol __imp_getsockopt
libcrypto.lib(b_sock.obj) : error LNK2001: unresolved external symbol __imp_getsockname
libcrypto.lib(b_sock.obj) : error LNK2001: unresolved external symbol __imp_WSAStartup
libcrypto.lib(b_sock.obj) : error LNK2001: unresolved external symbol __imp_WSACleanup
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_setsockopt
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_connect
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_socket
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_listen
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_closesocket
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_bind
libcrypto.lib(b_sock2.obj) : error LNK2001: unresolved external symbol __imp_accept
libcrypto.lib(bss_sock.obj) : error LNK2001: unresolved external symbol __imp_recv
libcrypto.lib(bss_sock.obj) : error LNK2001: unresolved external symbol __imp_send
libcrypto.lib(bss_sock.obj) : error LNK2001: unresolved external symbol __imp_WSASetLastError
```

**Comment by mtrojnar** [comment]
I could not reproduce this issue:
https://ci.appveyor.com/project/LudovicRousseau/libp11/build/job/bm9n6t68rxkvhnhw

**Comment by chrisdoherty4** [comment]
It came up on a Windows Server 2019 machine.

**Comment by mtrojnar** [comment]
I don't think this issue depends on a specific version of Windows.
It would be useful to know some details about your build environment.  At the bare minimum please include the version of your compiler and the commands that you used to build OpenSSL and libp11.

**Comment by frankmorgner** [comment]
OpenSSL [expects to be linked with ws2_32.lib](https://github.com/openssl/openssl/blob/master/NOTES.WIN#L128-L129)

**Comment by chrisdoherty4** [comment]
@mtrojnar I'll get the specs, sorry for the delay. I should've included it in the OP.

@frankmorgner Indeed. I see you updated the PR #290

**Comment by mtrojnar** [comment]
@frankmorgner The link you gave is about static linking.  I don't think linking libp11 statically with OpenSSL is such a good idea.

**Comment by chrisdoherty4** [comment]
@mtrojnar can you elaborate on why it shouldn't be statically linked?

We were using WDK v10.0.17134.0 with VS2017 v15.7.

**Comment by mtrojnar** [comment]
libp11 exposes PKCS#11 objects as OpenSSL objects.  When you statically link libp11 with OpenSSL, the resulting libp11 library contains a copy of the OpenSSL crypto library.  Your application using libp11 needs to link (either statically or dynamically) another copy of OpenSSL.  This not only produces an unnecessarily huge application, but more importantly each of those copies have separate global data (such as locks).  I expect problems here.

**Comment by chrisdoherty4** [comment]
Understood. In any case we were building a shared library and configuring the engine in the openssl.cnf.
