### ISSUE TITLE
engine -t  fails with Nitrokey HSM

### ISSUE THREAD

**Issue by chine369** [OpenSC/libp11#291]
Hi,
I have a Nitrokey HSM and I can generate RSA keys with pkcs11-tool( it proves opensc-pkcs11.so module is OK?). But when I try openssl engine , it fails.

### OpenSSL> engine -t
(rdrand) Intel RDRAND engine
     [ available ]
(dynamic) Dynamic engine loading support
     [ unavailable ]
(pkcs11) pkcs11 engine
     [ available ]

### OpenSSL> engine -t dynamic −pre SO_PATH:/usr/local/lib/libp11.so −pre ID:pkcs11 −pre LIST_ADD:1 −pre LOAD −pre MODULE_PATH:/usr/local/lib/opensc-pkcs11.so
(dynamic) Dynamic engine loading support
     [ unavailable ]
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so): /usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=−pre
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/SO_PATH:/usr/local/lib/libp11.so): /usr/lib/x86_64-linux-gnu/engines-1.1/SO_PATH:/usr/local/lib/libp11.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=SO_PATH:/usr/local/lib/libp11.so
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so): /usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=−pre
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/ID:pkcs11.so): /usr/lib/x86_64-linux-gnu/engines-1.1/ID:pkcs11.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=ID:pkcs11
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so): /usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=−pre
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/LIST_ADD:1.so): /usr/lib/x86_64-linux-gnu/engines-1.1/LIST_ADD:1.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=LIST_ADD:1
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so): /usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=−pre
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/LOAD.so): /usr/lib/x86_64-linux-gnu/engines-1.1/LOAD.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=LOAD
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so): /usr/lib/x86_64-linux-gnu/engines-1.1/−pre.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=−pre
139887961805248:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:../crypto/dso/dso_dlfcn.c:113:filename(/usr/lib/x86_64-linux-gnu/engines-1.1/MODULE_PATH:/usr/local/lib/opensc-pkcs11.so): /usr/lib/x86_64-linux-gnu/engines-1.1/MODULE_PATH:/usr/local/lib/opensc-pkcs11.so: cannot open shared object file: No such file or directory
139887961805248:error:25070067:DSO support routines:DSO_load:could not load the shared library:../crypto/dso/dso_lib.c:161:
139887961805248:error:260B6084:engine routines:dynamic_load:dso not found:../crypto/engine/eng_dyn.c:414:
139887961805248:error:2606A074:engine routines:ENGINE_by_id:no such engine:../crypto/engine/eng_list.c:339:id=MODULE_PATH:/usr/local/lib/opensc-pkcs11.so
error in engine

### OpenSSL> req -engine pkcs11 -new -key "id=%01" -keyform engine -out req.pem -text -x509
engine "pkcs11" set.
Unable to load module (null)
Unable to load module (null)
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140087499895232:error:81065401:libp11:pkcs11_CTX_load:Unable to load PKCS#11 module:p11_load.c:79:
140087499895232:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:78:
unable to load Private Key
error in req

**Comment by mtrojnar** [comment]
Use dash ("-") instead of Unicode minus sign ("−") in your OpenSSL command.
