### ISSUE TITLE
waiting for token insertion

### ISSUE THREAD

**Issue by dhobsong** [OpenSC/libp11#295]
Hello,

I was wondering if there is a way to wait for a card event before taking further action using libp11.
Basically I have a removable smart card and I would like to wait until it has been inserted into the reader before trying to access it (preferably without excessive polling)

I noticed that there are currently no calls to C_WaitForSlotEvent.  

Is there another commonly used way to wait until a removable card is ready to be accessed with libp11?

Thank you,

**Comment by frankmorgner** [comment]
I think currently, you would have to poll for your card. https://github.com/OpenSC/pkcs11-helper/ should have [what you're looking for](https://github.com/OpenSC/pkcs11-helper/blob/master/include/pkcs11-helper-1.0/pkcs11h-core.h#L367-L382)...

**Comment by dhobsong** [comment]
Sorry for the late response.  Thanks for the information.
