### ISSUE TITLE
The OpenSSL engine command does not work with OpenSSL 1.1.x

### ISSUE THREAD

**Issue by supreetd21** [OpenSC/libp11#298]
OS: Windows
Environment: Command Prompt Windows
OpenSSL downloaded from https://slproweb.com/products/Win32OpenSSL.html
 
### Issue 1
OpenSSL> version
OpenSSL 1.1.1c  28 May 2019

OpenSSL> engine -t dynamic -pre SO_PATH:/c/msys64/usr/lib/engines-1.1/libpkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/c/Program\ Files/OpenSC\ Project/OpenSC/pkcs11/opensc-pkcs11.dll
engine: Cannot mix flags and engine names.
engine: Use -help for summary.
error in engine

This instruction is a part of the main README.md. I have faced similar issues on MacOS as well. 
Could you help me with this issue?

### Issue 2
I want to sign a CSR using the private key in the Yubikey.
This works well on Linux based OS.

I followed the WIndows download steps to install OpenSC
https://github.com/OpenSC/OpenSC/wiki/Windows-Quick-Start - 64bit

I have followed the Msys2 based installation for libp11

I have this issue with other OpenSSL versions:
https://github.com/OpenSC/libp11/issues/298 

#### Logs
```
OpenSSL> version
OpenSSL 1.0.2s  28 May 2019
OpenSSL> engine -t dynamic -pre SO_PATH:/c/msys64/usr/lib/engines-1.1/libpkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/c/Program\ Files/OpenSC\ Project/OpenSC/pkcs11/opensc-pkcs11.dll
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/c/msys64/usr/lib/engines-1.1/libpkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Failure]: LOAD
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(/c/msys64/usr/lib/engines-1.1/libpkcs11.dll)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
[Failure]: MODULE_PATH:/c/Program\
17440:error:260AC089:engine routines:INT_CTRL_HELPER:invalid cmd name:.\crypto\engine\eng_ctrl.c:131:
17440:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:.\crypto\engine\eng_ctrl.c:311:
     [ unavailable ]
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(\usr\local\ssl\lib\engines\Files\OpenSC\\)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
17440:error:2606A074:engine routines:ENGINE_by_id:no such engine:.\crypto\engine\eng_list.c:391:id=Files/OpenSC\
17440:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(\usr\local\ssl\lib\engines\Project\OpenSC\pkcs11\opensc-pkcs11.dll)
17440:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
17440:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
17440:error:2606A074:engine routines:ENGINE_by_id:no such engine:.\crypto\engine\eng_list.c:391:id=Project/OpenSC/pkcs11/opensc-pkcs11.dll
```
Is this an issue because OpenSSL, OpenSC & libp11 have been compiled with different toolchains?

I tried compiling libp11 using MSVC as well, it resulted in the following error.
nmake /f Makefile.mak OPENSSL_DIR=c:\OpenSSL-Win64 BUILD_FOR=WIN64
```
libpkcs11.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'
````

**Comment by supreetd21** [comment]
Update:
I found a workaround by downloading 32 bit OpenSSL, OpenSC & compiling libp11 with MSVC 32-bit.

I could sign a CSR using a Yubikey with this setup. The issue is that the engine loading always fail the first time and is properly loaded at the subsequent attempt from the OpenSSL command console.

This issue is a blocker because the engine never loads from outside the openSSL command prompt.(From the terminal)

```
C:\OpenSSL-Win32\bin>openssl
OpenSSL> engine -t dynamic -pre SO_PATH:C:\Users\Espressif\Downloads\libp11-0.4.10\libp11-0.4.10\src\pkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\Users\Espressif\Desktop\opensc-pkcs11.dll
Error configuring OpenSSL
21216:error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library:.\crypto\dso\dso_win32.c:179:filename(C:\UsersEspressifDownloadslibp11-0.4.10libp11-0.4.10srcpkcs11.dll)
21216:error:25070067:DSO support routines:DSO_load:could not load the shared library:.\crypto\dso\dso_lib.c:233:
21216:error:260B6084:engine routines:DYNAMIC_LOAD:dso not found:.\crypto\engine\eng_dyn.c:467:
21216:error:260BC066:engine routines:INT_ENGINE_CONFIGURE:engine configuration error:.\crypto\engine\eng_cnf.c:191:section=pkcs11_section, name=dynamic_path, value=C:\UsersEspressifDownloadslibp11-0.4.10libp11-0.4.10srcpkcs11.dll
21216:error:0E07606D:configuration file routines:MODULE_RUN:module initialization error:.\crypto\conf\conf_mod.c:223:module=engines, value=engine_section, retcode=-1
error in engine
OpenSSL> engine -t dynamic -pre SO_PATH:C:\Users\Espressif\Downloads\libp11-0.4.10\libp11-0.4.10\src\pkcs11.dll -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:C:\Users\Espressif\Desktop\opensc-pkcs11.dll
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\Users\Espressif\Downloads\libp11-0.4.10\libp11-0.4.10\src\pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:C:\Users\Espressif\Desktop\opensc-pkcs11.dll
Loaded: (pkcs11) pkcs11 engine
     [ available ]
```

What could be the reason for such an issue?

**Comment by mtrojnar** [comment]
The error message says there is an invalid engine_section in your openssl.cnf.  Just use the default openssl.cnf.

Also, it may be easier to use 64-bit OpenSC module instead of rebuilding all other code as 32-bit.

**Comment by supreetd21** [comment]
Hi @mtrojnar,
Thanks for the response. I checked my edited engine.cnf and found the answer. 

I had set OPENSSL_CONF to a config file with the engine information as mentioned in the README.md. The \ in my module path was treated as an escape character. Adding '\\' worked.

I agree it would be better with 64bit versions.
Although, I am yet to find a way around the below issue. (P.S. I'm fairly new to the Windows ecosystem)
I tried compiling libp11 using MSVC Command prompt with x64-Debug configuration.
`nmake /f Makefile.mak OPENSSL_DIR=c:\OpenSSL-Win64 BUILD_FOR=WIN64`

``libpkcs11.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64'``

**Comment by supreetd21** [comment]
Is OpenSC incompatible with OpenSSL 1.1.1?

Got this error on trying the command in the libp11 README.md (See the Issue 1 above)
```
engine: Cannot mix flags and engine names.
```

Post that, I tried removing the ID and loaded the engine
```
OpenSSL> engine dynamic -tt -pre SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so -pre LIST_ADD:1 -pre LOAD
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so
[Success]: LIST_ADD:1
[Failure]: LOAD
4612265408:error:260B6091:engine routines:dynamic_load:version incompatibility:crypto/engine/eng_dyn.c:454:
     [ unavailable ]
```

**Comment by mtrojnar** [comment]
Your /usr/local/Cellar/engine_pkcs11/0.1.8/lib/engines/engine_pkcs11.so file appears to be built against OpenSSL older than 1.1.0.  Please make sure to build your engine against OpenSSL 1.1.1.

BTW: Are you sure you're using an engine produced by a recent version of libp11?

**Comment by supreetd21** [comment]
Hi @mtrojnar,

You're right. I checked that these packages were installed with brew.
https://formulae.brew.sh/formula/engine_pkcs11

It uses an older version of OpenSSL and also a very old release of libp11. 
Compiling them from the latest releases should work for me.
