### ISSUE TITLE
boost::mutex Assertion

### ISSUE THREAD

**Issue by qdrone** [OpenSC/libp11#30]
Hi,

When I try to write a new key I get the following error:

osc@XilinxDev:~/Documents/04_PKI_app/04_PKI_app/src$ pkcs11-tool --module=./libidprimepkcs11-2.4.0.so -l -k -d 03 -a olis_root_ca --key-type rsa:2048
Using slot 0 with a present token (0x0)
Logging in to "Card #A5**********************.".
Please enter User PIN: 
pkcs11-tool: /usr/include/boost/thread/pthread/mutex.hpp:108: boost::mutex::~mutex(): Assertion `!posix::pthread_mutex_destroy(&m)' failed.
error: PKCS11 function C_GenerateKeyPair failed: rv = CKR_FUNCTION_CANCELED (0x50)

this happens with Ubuntu 14.04 in the VM and native.

br, 
Oliver

**Comment by LudovicRousseau** [comment]
It looks like a bug in the PKCS#11 library ``libidprimepkcs11-2.4.0.so``. libp11 and OpenSC do not use boost.

Maybe you should contact the PKCS#11 lib vendor.

**Comment by qdrone** [comment]
Thank you for your input. I will contact the vendor!
