### ISSUE TITLE
Merge of PR 303 broke new tests

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#310]
MacOS 10.14.6, Xcode-11, OpenSSL-1.1.1d, current master of libp11 (~~my fork~~ *your repo fails exactly the same way*), current `develop` branch of SoftHSMv2 (equivalent of their `master`).

```
. . . . .
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: rsa-testpkcs11.softhsm
PASS: rsa-testfork.softhsm
PASS: rsa-testlistkeys.softhsm
PASS: rsa-evp-sign.softhsm
PASS: ec-evp-sign.softhsm
PASS: ec-testfork.softhsm
PASS: fork-change-slot.softhsm
PASS: rsa-pss-sign.softhsm
PASS: rsa-oaep.softhsm
PASS: case-insensitive.softhsm
PASS: ec-check-privkey.softhsm
FAIL: pkcs11-uri-without-token.softhsm
FAIL: search-all-matching-tokens.softhsm
```
[test-suite-log.txt](https://github.com/OpenSC/libp11/files/3681567/test-suite-log.txt)

**Comment by mtrojnar** [comment]
@ansasaki Please take a look. It's your PR.

**Comment by ansasaki** [comment]
I'll investigate. And probably try to add CI tests on MacOS.

**Comment by ansasaki** [comment]
I'm halfway there. Finally got a CI run on macOS:
https://travis-ci.org/ansasaki/libp11/jobs/593117511

**Comment by mouse07410** [comment]
Excellent. Since it fails for you the same way, there’s a good chance you would find and fix the problem.

**Comment by ansasaki** [comment]
@mouse07410 in #311 I added macOS runs to Travis CI.

**Comment by mouse07410** [comment]
@mtrojnar please re-open. The new tests are fixed now, but one of the old ones became broken:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: rsa-testpkcs11.softhsm
PASS: rsa-testfork.softhsm
PASS: rsa-testlistkeys.softhsm
FAIL: rsa-evp-sign.softhsm
PASS: ec-evp-sign.softhsm
PASS: ec-testfork.softhsm
PASS: fork-change-slot.softhsm
PASS: rsa-pss-sign.softhsm
PASS: rsa-oaep.softhsm
PASS: case-insensitive.softhsm
PASS: ec-check-privkey.softhsm
PASS: pkcs11-uri-without-token.softhsm
PASS: search-all-matching-tokens.softhsm
============================================================================
Testsuite summary for libp11 0.4.11_git
============================================================================
# TOTAL: 13
# PASS:  12
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
```

And the log: 
[test-suite-log.txt](https://github.com/OpenSC/libp11/files/3692536/test-suite-log.txt)

**Comment by mouse07410** [comment]
@ansasaki thanks for adding MacOS Travis CI. The old problems are fixed, but the new one is created - see my previous post.

**Comment by mouse07410** [comment]
@ansasaki and @mtrojnar, I suggest that @stanislavlevin should be involved, because this problem may be a result of interactions of #303 and #309.

**Comment by mouse07410** [comment]
I guess this can be closed now, though it would make sense to apply the above patch.
