### ISSUE TITLE
Migrate LGTM.com installation from OAuth to GitHub App

### ISSUE THREAD

**Issue by LGTM-badger** [OpenSC/libp11#313]
Hi There,

This project is still using an old implementation of LGTM's automated code review, which has now been disabled. To continue using automated code review, and receive checks on your Pull Requests, please [install the GitHub App](https://github.com/apps/lgtm-com/installations/new) on this repository.

Thanks,
The LGTM Team

**Comment by mtrojnar** [comment]
Any idea how to unsubsribe the project from LGTM?

**Comment by s0** [comment]
@mtrojnar If you don't install the GitHub App, then LGTM will automatically be disabled for you over the next couple of days. Otherwise if you want to do it now, @frankmorgner can revoke the OAuth access for this application from his account, and statuses will stop being posted on your PRs.

**Comment by mtrojnar** [comment]
@s0 Thank you. The GitHub App requests write access to the repository. This is outrageous.

**Comment by s0** [comment]
Do you mean the OAuth App? As far as I can tell, the GitHub App does not require write permissions to the repo, only write permissions to checks and PRs:

![2019-10-09-115737_5120x1440_scrot](https://user-images.githubusercontent.com/3319932/66526482-ad585580-eaad-11e9-8a1f-11de92f8cb47.png)

**Comment by mtrojnar** [comment]
@s0 I guess it's possible I misunderstood it.  Honestly, I'm not sure what "write access to checks and pull requests" actually means.

**Comment by s0** [comment]
You can find more information on what this allows access to here:

* https://developer.github.com/v3/apps/permissions/#permission-on-checks
* https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests

For what it's worth, LGTM (and Semmle) are now owned and operated by GitHub, if that influences your decision.

**Comment by frankmorgner** [comment]
I've installed the app to the libp11 repository just now. However, I wonder why LGTM has actually analyzed the incoming PRs even before that...

**Comment by mtrojnar** [comment]
Apparently, the service was shut down: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/
I removed the Webhook.
