### ISSUE TITLE
Openssl CSR Signing fails when a new key is generated from the Engine

### ISSUE THREAD

**Issue by raerne** [OpenSC/libp11#315]
I have the following problem: 
I would like to Create a new privatekey inside of my pkcs11 engine (ATECC), then generate a CSR via Openssl/libp11 engine wrapper. This works fine, but when I try to redo this same operation (generating, creating a csr) it fails with an incorrect signature. 

The key generation command is called directly in the underlying engine implementation (cryptoauthlib) and I'm assuming that the SSL/libp11 context is somehow not updated about the keychange.

```
    // setup and init engine, ...
    EVP_PKEY *pkey = ENGINE_load_private_key(e, token.c_str(), nullptr, nullptr);
    ENGINE_finish(e);

    if (!X509_REQ_sign(req, pkey, EVP_sha256())) {
        X509_REQ_free(req);
        return -1;
    }

    // ... save request, validation works OK

    if(atcab_genkey(0, nullptr) != ATCA_SUCCESS) {
        X509_REQ_free(req);
        return -1;
    }

    if (!X509_REQ_sign(req, pkey, EVP_sha256())) {
        X509_REQ_free(req);
        return -1;
    }

    // ... save request, validation fails if genkey was called
```

[The full example gist of what I'm trying to do](https://gist.github.com/raerne/1ffbd14fd51e3db2976cba6f904b659f)

What are my options of getting this to work. I searched around of regenerating a private key directly from openssl / libp11 engine but have not been successful.

Thanks for the help.
Ramon

**Comment by dengert** [comment]
`ENGINE_load_private_key` loads information about the private key including the engine to be used. 
Thus `X509_REQ_sign(req, pkey, EVP_sha256())` needs the engine.

The `ENGINE_finish(e);` should not be done until you are done with `pkey`.
Not sure why the first sign worked, could be it was not freed as expected. 

A way to see what is really going use [opensc_spy](https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC#pkcs-11-spy) which can work with any  PKCS\#11 module. Should work with your `/usr/lib/libcryptoauth.so`. 

Not clear what your `atcab_genkey` is doing. It could be overwriting the key `pkey` or generating a second key. It looks like it does not use the engine.  

In any case `pkey` would not be valid as it is still has info (public key) about the original key.  

You could free the original `pkey`, do the `atcab_genkey` then `ENGINE_load_private_key` again.
This might not work, but doing  the `atcab_genkey` in a separate process  before doing  the sign should work.

**Comment by mtrojnar** [comment]
@raerne did not respond for a month.  I presume either this issue is resolved, or @raerne is no longer interested in resolving it.
