### ISSUE TITLE
OPENCSR Failing

### ISSUE THREAD

**Issue by agilesai1294** [OpenSC/libp11#316]
why EC keys with OpenSSL 1.0.2h are not working? I am generating CSR using Microchip ATECC608A. 
Openssl Version 1.0.2h 
libp11 0.4.10
Yocto 2.1

openssl req -engine pkcs11 -key "pkcs11:token=0123EE;object=device;type=private" -keyform engine -new -out new_device.csr -subj "/CN=NEW CSR EXAMPLE"
C_Initialize
IN: pInitArgs = NULL
C_Initialize = CKR_OK
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BFD4 = 3065496424
OUT: pSlotList = (1) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BFD4 = 1
OUT: pSlotList = (1) [ SL0 ]
C_GetSlotList = CKR_OK
engine "pkcs11" set.
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BE0C = 3065490348
OUT: pSlotList = (1) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BE0C = 1
OUT: pSlotList = (1) [ SL0 ]
C_GetSlotList = CKR_OK
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BE0C = 0
OUT: pSlotList = (1) NO-VALUES
C_GetSlotList = CKR_OK
C_GetSlotList
IN: tokenPresent = CK_FALSE
IN: pulCount = 0xBEB9BE0C = 1
OUT: pSlotList = (1) [ SL0 ]
C_GetSlotList = CKR_OK
C_GetSlotInfo
IN: slotID = SL0
OUT: pInfo = {
slotDescription: "0_3_0"
manufacturerID: "Microchip Technology Inc"
flags: 5 = CKF_TOKEN_PRESENT | CKF_HW_SLOT
hardwareVersion: 0.2
firmwareVersion: 255.255
}
C_GetSlotInfo = CKR_OK
C_GetTokenInfo
IN: slotID = SL0
OUT: pInfo = {
label: "0123EE"
manufacturerID: "Microchip Technology Inc"
model: "ATECC608A"
serialNumber: "946EEF92A0E7"
flags: 1025 = CKF_RNG | CKF_TOKEN_INITIALIZED
ulMaxSessionCount: 1
ulSessionCount: 0
ulMaxRwSessionCount: 1
ulRwSessionCount: 0
ulMaxPinLen: 0
ulMinPinLen: 0
ulTotalPublicMemory: 1
ulFreePublicMemory: 1
ulTotalPrivateMemory: 1
ulFreePrivateMemory: 1
ulFreePrivateMemory: 1
hardwareVersion: 0.2
firmwareVersion: 255.255
utcTime:
}
C_GetTokenInfo = CKR_OK
Found slot without user PIN
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
3069396176:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:eng_pkey.c:124:
unable to load Private Key
C_Finalize
IN: pReserved = NULL
C_Finalize = CKR_OK

**Comment by dengert** [comment]
You may need a `-passin arg` to login to the card to use the private key.

**Comment by agilesai1294** [comment]
@dengert The same command works with openssl 1.1.1h

**Comment by dengert** [comment]
OK, then use 1.1.1 
Good luck.

**Comment by agilesai1294** [comment]
In my project, I am using Yocto 2.1 which makes openssl 1.0.2h it cant be upgraded to 1.1.x. Can you confirm that EC keys can be extracted using 1.0.2h?

**Comment by agilesai1294** [comment]
@dengert Why can't I extract EC keys with OpenSSL 1.0.2h?

**Comment by dengert** [comment]
Not sure. But  your log says:
```
C_GetTokenInfo = CKR_OK
Found slot without user PIN
```
Does the key really not need a PIN to unlock? How was the key created?

What does the PKCS11 trace look like when using 1.1 or higher?

This could mean the device supports a private key that does not require login and it has been selected, so no attempt to do a C_Login.  Try adding an `id=` parameter to the URI to point at the specific key you want to load. 

You can try debugging the program and submit a PR.  

OpenSSL has changed a lot from 1.0.2 to 1.1 and [OpenSSL Release Strategy](https://www.openssl.org/policies/releasestrat.html)  says: "Version 1.0.2 will be supported until 2019-12-31 (LTS)" 

Maybe some one else can help you with this problem. 

I do not have a device or development environment like yours so can not do any testing, or interest in  OpenSSL 1.0.2.
