### ISSUE TITLE
Please document the string formats for selecting the token and the certificate from token

### ISSUE THREAD

**Issue by capr** [OpenSC/libp11#322]
I'm trying to figure out what string formats `eng_parse.c` expects. A little documentation on the expected formats would help a lot.

For instance, is there a way to specify "any token, any certificate" via libcurl's `CURLOPT_SSLCERT` and `CURLOPT_SSLKEY` options (given openssl is set up correctly to use libp11) and have those options trickle down through openssl into libp11 so that the first found token and certificate can be selected from the HSM automatically? In my case there's only one token and one certificate on the machine so I don't necessarily need to identify them.

Thanks.

**Comment by dwmw2** [comment]
I think you're looking for RFC7512. But see also
http://www.infradead.org/openconnect/pkcs11.html which attempts to be a little more user-accessible.

**Comment by capr** [comment]
Thanks, a tutorial on how to go from p11tool's output to constructing the uri scheme is exactly what I wanted, spares me from RTFM.

**Comment by dwmw2** [comment]
Hth. Please reopen if you think anything is wrong in the libp11/engine implementation.

**Comment by dwmw2** [comment]
Hm, I note my docs use "`object-type`" a lot when that should be "`type`". It changed in an early draft of what became RFC7512. I'll fix them.
