### ISSUE TITLE
Missing null check on label in libp11/src/eng_back.c

### ISSUE THREAD

**Issue by efternavn** [OpenSC/libp11#323]
Some tokens allow keys to not have a label attribute (ie., not just the (empty) default value, but `C_GetAttributeValue` returns `CKR_ATTRIBUTE_TYPE_INVALID`).
This causes undefined behavior in `libp11/src/eng_back.c` at line 898:
https://github.com/OpenSC/libp11/blob/master/src/eng_back.c#L898
where `strcmp` is called with `k->label` being `NULL`.
The same problem seems to exist for certificate objects.

**Comment by mtrojnar** [comment]
Good catch!  Would you please provide some examples of such tokens?
Could you submit a PR?  It may be easier for you to test a fix.

**Comment by efternavn** [comment]
Sorry for the long delay.
I've only seen it in a proprietary software token, that I've been working with recently.
I've tried to make a small PR on this. I'm no Github guru, so perhaps I didn't do it right (should I somehow have linked the PR to this issue? -- sorry for not doing so. :-| )

**Comment by dwmw2** [comment]
Looks sane; thanks.

**Comment by mtrojnar** [comment]
Merged in #324.
