### ISSUE TITLE
segmenetation fault when using engine pkcs11 in cygwin env

### ISSUE THREAD

**Issue by ablam** [OpenSC/libp11#329]
Hi,
I'm unable to use pkcs11 engine build with libp11, it causes segmentation fault.
I'm using windows 10 64-bit + cygwin (I've tried different PC, cygwin 32/64 bit). OpenSSL 1.1.1d, libp11-kit are taken from cygwin repo. libp11 is build from sources, with default settings using native gcc (not mingw). I'm able to load engine, list it's capabilities, but any call using curl / openssl causes crash.
ie: OPENSSL_CONF=./openssl.cnf curl --cacert ./ca-chain.cert.pem --cert ./my.cert.pem --key 'pkcs11:token=xxx' --verbose "https://1.2.3.4:8888"
* STATE: INIT => CONNECT handle 0x80077670; line 1491 (connection #-5000)
* Added connection 0. The cache now contains 1 members
*   Trying 1.2.3.4:8888...
* TCP_NODELAY set
* STATE: CONNECT => WAITCONNECT handle 0x80077670; line 1547 (connection #0)
* Connected to 1.2.3.4 (1.2.3.4) port 8888 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x80077670; line 1667 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
PKCS#11: Initializing the engine
Segmentation fault (core dumped)

no matter whether token exists or not, it always fails, changing from p11-kit-proxy to libsofthsm2 makes no difference. So it looks like crash occurs before request is forwarded by proxy.

Regards,

Andrzej

**Comment by ablam** [comment]
stackdump of libp11-0.4.10 built with debug symbols gave me following results:
$ addr2line.exe -a B6500000 -a 6980C123 -a 69801C06 -a 69801DDD -a 69801216 -e /opt/openssl/lib/engines/pkcs11.dll
0xb6500000
??:0
0x6980c123
/temp/libp11/src/p11_front.c:47
0x69801c06
/temp/libp11/src/eng_back.c:281
0x69801ddd
/temp/libp11/src/eng_back.c:339
0x69801216
/temp/libp11/src/eng_front.c:135

**Comment by mtrojnar** [comment]
> libp11 is build from sources

Which sources exactly?  The current master branch, or a release?  Were you able to reproduce this issue with the current master branch?  What is your openssl.cnf file?

> with default settings using native gcc

By "native gcc" you mean cygwin gcc, right?

**Comment by ablam** [comment]
libp11 - sources taken from github repo, master branch, tested on latest commit and tag 0.4.10 - no difference

my openssl config, it doesn't matter whether I've used softhsm directly, via p11-kit-proxy or even remote hsm server (ssh + proper p11-kit module):
```
openssl_conf = openssl_init

[openssl_init]
engines=engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /lib/engines-1.1/pkcs11.dll
MODULE_PATH = /lib/p11-kit-proxy.so
# MODULE_PATH = /usr/local/bin/cygsofthsm2.dll
init = 0
VERBOSE = EMPTY
```
gcc: cygwin gcc 7.4.0 (I've checked also fresh install with testing version of gcc 9.x.x, but no difference). Cygwin updated to latest version available.
I thought that GnuTLS might cause problems, since it installs own version of libcrypto/libssl (1.0.x instead of 1.1.1x), but fresh install without it doesn't change anything.

recently I've also made a test using msys2 (which is cygwin based) and there are no problems.

**Comment by mtrojnar** [comment]
It seems to be crashing while loading the module in pkcs11_CTX_load().
I'm curious how this code compiles on Cygwin:
https://github.com/OpenSC/libp11/blob/9540b767f68da153c782fbdf3036967521dd841b/src/libpkcs11.c#L64-L88
AFAIR Cygwin used to define WIN32.

**Comment by efternavn** [comment]
I have just installed Cygwin and I think I can reproduce the problem. I'll try to have a look at it when I find then time (and if no-one else is already on it). I don't have any experience with Cygwin, but I can give it a shot.

GCC in Cygwin doesn't seem to set WIN32.
Actually I don't think that macro should be used -- judging from a quick search that for instance leads to this: https://stackoverflow.com/questions/2989810/which-cross-platform-preprocessor-defines-win32-or-win32-or-win32 .

**Comment by efternavn** [comment]
It seems that there's something wrong with the packing of the CK_FUNCTION_LIST struct. 
For now, my theory is that libp11 defines CRYPTOKI_FORCE_WIN32 on Cygwin and therefore uses 1-byte alignment whereas p11-kit doesn't do this.
Judging from the comments on CRYPTOKI_FORCE_WIN32, I think that it's the p11-kit Cygwin port that is doing it wrong. But this PR seems to suggest the opposite: https://github.com/OpenSC/OpenSC/pull/1645/commits/b78bba3f2036e612853c60fd2bfcb6db1670e32c ...
I'll have to leave it at this for the next week or so.

**Comment by efternavn** [comment]
I tried to remove the CRYPTOKI_FORCE_WIN32 definition in the Makefile and then it works. Perhaps you could also verify this, @ablam?
I've read through the discussion on https://github.com/OpenSC/OpenSC/issues/607 , and the conclusion there was to remove CRYPTOKI_FORCE_WIN32 on Cygwin, so I guess that's the solution here as well.
I still think it goes against PKCS#11 (which states that the structs must be 1-byte packed), but that has already been discussed in the issue mention above.
