### ISSUE TITLE
Windows: Issues in VERSIONINFO resource

### ISSUE THREAD

**Issue by pmisik** [OpenSC/libp11#339]
1.	Windows Explorer unable to display information about compiled dll.
It seems root cause of this issue is missing VarFileInfo block.
2.	FILETYPE 0x1L is dedicated to executable not to dll
see: WindowsSDK: verrsrc.h
#define VFT_APP                 0x00000001L
#define VFT_DLL                 0x00000002L
3.	String represented versions (StringFileInfo.FileVersion and StringFileInfo.ProductVersion) parts should be delimited by dot and not by comma.

![image](https://user-images.githubusercontent.com/14224662/82084979-908f9a80-96ec-11ea-840d-e1e90433600b.png)

**Comment by pmisik** [comment]
After applying PR

![image](https://user-images.githubusercontent.com/14224662/82086161-6212bf00-96ee-11ea-9660-ea9750e4d0e5.png)

**Comment by mtrojnar** [comment]
Thank you.
