### ISSUE TITLE
NOT ISSUE: verified LibreSSL 3.2.0 compat

### ISSUE THREAD

**Issue by patchMonkey156** [OpenSC/libp11#341]
Compiles cleanly. Thank you for accepting the previous compatibility patches. With them, libp11 (from the master branch) works cleanly on my LibreSSL v3.2.0 system. 

Future goal: clean up ifdep hell for no longer supported versions of LibreSSL. I will be testing compatibility of various actively-used, upstream-supported versions of LibreSSL to ascertain which "ifdep"s are no longer necessary.

Cleaner code helps us all. Thank you again for accepting patches.

**Comment by mtrojnar** [comment]
Would you kindly submit a PR removing the ifdefs that are no longer needed?

**Comment by patchMonkey156** [comment]
Apologies for the delay. A family matter is keeping me occupied. This pull request will happen when I have time to thoroughly test each declaration.

Thank you for your understanding.
