### ISSUE TITLE
Memory leak on EC_KEY ex data

### ISSUE THREAD

**Issue by jussike** [OpenSC/libp11#342]
I did a https request with openssl 1.1.1b and the latest pkcs11 engine through valgrind and it seems to leak memory.

It calls `EC_KEY_set_ex_data()` but it's never released.
https://github.com/OpenSC/libp11/blob/master/src/p11_ec.c#L317

There is TODO on the code for ex memory management
https://github.com/OpenSC/libp11/blob/master/src/p11_ec.c#L173

If I understand correctly the documentation,
https://www.openssl.org/docs/man1.1.0/man3/CRYPTO_free_ex_index.html
, `free_func()` should be set and it should call `CRYPTO_free_ex_data()` before calling `CRYPTO_free_ex_index()`. Does it make sense?

What expected?
No leaks on valgrind output.

What happened?
Valgrind shows a memory leak.

How to reproduce?
Well, I don't have very simple test code because i'm running it through python.
I think it's quite clear that there is/are missing free-call(s) on the code because there is the TODO.

```
==30985== 2,481 (16 direct, 2,465 indirect) bytes in 1 blocks are definitely lost in loss record 709 of 735
==30985==    at 0x48479CC: malloc (vg_replace_malloc.c:299)
==30985==    by 0x5D7FBD7: CRYPTO_zalloc (mem.c:230)
==30985==    by 0x5DC4AD3: sk_reserve (stack.c:180)
==30985==    by 0x5DC4C83: OPENSSL_sk_insert (stack.c:242)
==30985==    by 0x5D78813: sk_void_push (crypto.h:89)
==30985==    by 0x5D78813: CRYPTO_set_ex_data (ex_data.c:381)
==30985==    by 0x5E9376B: pkcs11_set_ex_data_ec (p11_ec.c:317)
==30985==    by 0x5E9376B: pkcs11_get_evp_key_ec (p11_ec.c:372)
==30985==    by 0x5E91E73: pkcs11_get_key (p11_key.c:328)
==30985==    by 0x5E8D173: ctx_load_key (eng_back.c:914)
==30985==    by 0x5E8E2C3: ctx_load_privkey (eng_back.c:966)
==30985==    by 0x5E8BECF: load_privkey (eng_front.c:176)
==30985==    by 0x5D5E33F: ENGINE_load_private_key (eng_pkey.c:75)
```

**Comment by mtrojnar** [comment]
Is this one-time memory leak at engine loading a real concern for you, or rather you only reported is because valgrind did?

**Comment by jussike** [comment]
Yes, it's potential problem because I have low end boxes which will have long uptime and I'm planning to use pkcs11-engine there for polling the server continuously. The leak will be cumulated and RSS of the process will be grown.
