### ISSUE TITLE
Provide Windows binaries

### ISSUE THREAD

**Issue by elipsion** [OpenSC/libp11#345]
Since there are publicly available binary releases for both OpenSC and OpenSSL it would be greatly appreciated if there also was one for libp11.
Most Windows systems are not set up for compiling the same way that *nix is, so it becomes a major hurdle for those users.

**Comment by elipsion** [comment]
There seem to be artifacts produced by [AppVeyor](https://ci.appveyor.com/project/LudovicRousseau/libp11), so I guess all that's needed is a Code Signing Certificate and MSI packaging.

**Comment by mtrojnar** [comment]
OpenSSL does not provide official Windows installers: https://wiki.openssl.org/index.php/Binaries
Would you like to sponsor building Windows windows installers for libp11 releases?

**Comment by mtrojnar** [comment]
Provided in https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.11

**Comment by ulrichb** [comment]
In the 0.4.12 release they disappeared again (see https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.12). Was this on purpose?

**Comment by mtrojnar** [comment]
I'm working on automatic Windows builds with GitHub Actions.  Please be patient.

**Comment by ulrichb** [comment]
Oh, did't know. Thanks for info!

**Comment by mtrojnar** [comment]
Please take a look at Artifacts at the bottom of https://github.com/OpenSC/libp11/actions/runs/2851862304.  What do you think?

**Comment by lollita** [comment]
Windows binary updates are still missing.

**Comment by olszomal** [comment]
1. Visit the [GitHub Actions page for libp11](https://github.com/OpenSC/libp11/actions/workflows/ci.yml?query=branch%3Amaster).
2. Select the most recent workflow run from the list.
3. Scroll to the bottom of the workflow page, where you’ll see the Artifacts section. Here, you can download the latest binary files.

I recommend closing this issue.

**Comment by mtrojnar** [comment]
I intend to also upload those artifacts with with each subsequent release.  Please remind me if I forget to do that.

**Comment by ulrichb** [comment]
(In case the 0.4.13 release doesn't happen in the near time:) Could you maybe upload the 0.4.12 Windows binaries to the [release page](https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.12)?

Previously there were at aleast available via the [AppVeyor build of the release](https://ci.appveyor.com/project/LudovicRousseau/libp11/builds/44186994/job/h064e6i07iul3uu4/artifacts). But in the meantime they have been cleanup up from there ...
