### ISSUE TITLE
PKCS11_find_key failture

### ISSUE THREAD

**Issue by panmeiliang** [OpenSC/libp11#349]
When I use NSS to obtain the USBkey private key, it is possible, but I keep failing to use this interface.

**Comment by mtrojnar** [comment]
Use NSS.

**Comment by panmeiliang** [comment]
我的意思是我不知道这是什么问题

**Comment by panmeiliang** [comment]
> Use NSS.

sorry  ，I mean I don't know what the problem is！

**Comment by mtrojnar** [comment]
> sorry ，I mean I don't know what the problem is！

I also don't know what the problem is.  Sending a detailed description of your problem might help.  Make sure to include a step-by-step instruction to reproduce it.

**Comment by panmeiliang** [comment]
> 当我使用NSS获取USBkey私钥时，可以这样做，但是我一直无法使用该接口。



> > sorry ，I mean I don't know what the problem is！
> 
> I also don't know what the problem is. Sending a detailed description of your problem might help. Make sure to include a step-by-step instruction to reproduce it.


I found out that the problem is because C_GetAttributeValue returned CKR_ATTRIBUTE_SENSITIVE
