### ISSUE TITLE
Request for installation instructions

### ISSUE THREAD

**Issue by zosocanuck** [OpenSC/libp11#35]
Since libp11-QuickStart has no content yet can you provide basic instructions on how to build and install libp11 and engine_pkcs11?  This will help new folks avoid basic environment issues.

**Comment by mtrojnar** [comment]
https://github.com/OpenSC/libp11/blob/master/examples/README may be useful.

**Comment by Fredericvo** [comment]
The windows instructions are completely wrong. It asks to edit lines that aren't in the mentioned file and the command: nmake /f makefile.mak fails with rc.exe not being able to process @ symbols in the resource script. I suspect the lack of a configuration script that replaces the @XXXX@ with some substituted values. Makes me wonder if the build steps for win32 are even tested at all before publication.

**Comment by mtrojnar** [comment]
I'm afraid there are currently no native Windows instructions available.  Instructions in the https://github.com/OpenSC/libp11/blob/master/examples/README file are for using the library on Unix-based platforms only.  The usual building procedure is supposed to be used on Unix-based platforms: `./configure && make && sudo make install`.

There are some clues on building the library on Windows in the appveyor.yml file, however a proper documentation should be written.  Any volunteers?

**Comment by Fredericvo** [comment]
I've been able to make it work but with lots of manual hacking. I tried 2 ways.
way 1:
Created an empty VS 2013 solution,dll project,empty project, and manually added all .c and .h files
I had to manually create a def file and copy/paste from the exports file and add the following lines on top:
LIBRARY libp11
EXPORTS

Manually configured the input directories (include/libs) for openssl to match my system

way 2:
Tried to make the makefile work with lots of manual tweaks.
I didn't feel much for substituting all of versioninfo.rc so I removed it entirely from the build process (maybe a licence violation though) so a solution is to distribute an already substituted version in future distros or find a way to include this step in a windows friendly way. (no Perl or other linux-centric ways  if possible)

My Makefile.mak now looks like this:
TOPDIR = ..

!INCLUDE $(TOPDIR)\Make.rules.mak

TARGET                  = libp11.dll

OBJECTS                 = libpkcs11.obj p11_attr.obj p11_cert.obj \
	p11_err.obj p11_key.obj p11_load.obj p11_misc.obj p11_rsa.obj \
	p11_ec.obj p11_slot.obj p11_ops.obj

all: $(TARGET)


.c.obj::
	cl $(COPTS) /c $<

$(TARGET): $(OBJECTS)
	@echo LIBRARY $* > $*.def
	@echo EXPORTS >> $*.def
	@type $*.exports >> $*.def
	link $(LINKFLAGS) /dll /def:$*.def /implib:$*.lib /out:$(TARGET) \
		$(OBJECTS) $(OPENSSL_LIB)
	if EXIST $*.dll.manifest mt -manifest $*.dll.manifest -outputresource:$*.dll;2

Had to tweak the makefile.rules.mak file in the root dir to match my system too (openssl include/lib)
tldl seems to be unused.

issued the following command from a VS 2013 x64 command line:
nmake BUILD_FOR=WIN64 /A /f Makefile.mak

I din't test a 32-bit build as I only built an x64 libeay32.dll too.

**Comment by mtrojnar** [comment]
Thank you.  I will follow "way 2" in the upcoming Windows build documentation.

I intend to reduce the number of build prerequisites.  Perl is probably not very hard to get, as it is also  required by OpenSSL.  Consequently, you likely already have it installed before you start building libp11.  On the other hand, the MSVC build should __not__ require Cygwin...

**Comment by Fredericvo** [comment]
Thank you. I admit I do have Perl installed :)

**Comment by mtrojnar** [comment]
Done: https://github.com/OpenSC/libp11/blob/master/INSTALL.md
I removed the ugly dependency on Cygwin.

**Comment by Fredericvo** [comment]
Cool

**Comment by mtrojnar** [comment]
I'm glad you like it.  I'm closing the issue.
