### ISSUE TITLE
OpenSSL can't load module after OpenSC upgrade

### ISSUE THREAD

**Issue by cprn** [OpenSC/libp11#353]
Hi,

I changed neither OpenSSL config file nor the command line used to generate the signature but suddenly after Ubuntu upgrade an app using token card can't read the card now. The upgrade updated versions as follows:
```
openssl                           1.0.2g-1ubuntu13.2 -> 1.1.1g-1+ubuntu20.04.1+deb.sury.org+1
opensc                            0.17.0-1           -> 0.20.0-3
opensc-pkcs11:amd64               0.17.0-1           -> 0.20.0-3
libengine-pkcs11-openssl:amd64    0.4.7-1            -> 0.4.10-1
```

Config file:
```cfg
openssl_conf = openssl_def

[openssl_def]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
dynamic_path = /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/pkcs11.so
engine_id = pkcs11
MODULE_PATH = /home/user/DIGIPASS/VdsPKCS1164.so
PIN = $ENV::SC_PIN
default_algorithms = ALL
init = 1
```

The command line used to generate signature:
```sh
OPENSSL_CONF=/home/user/openssl.digipass.cnf openssl smime -sign -engine pkcs11 -md SHA1 -binary -in ~/foo -out ~/bar -outform der -keyform engine -inkey id_b05eac... -signer ~/DIGIPASS/hi.pem
```

Before the upgrade it'd set the engine and sign the content of `~/foo` but now it says it cannot read private key from the card:
```sh
engine "pkcs11" set.
No tokens found
No tokens found
PKCS11_get_private_key returned NULL
cannot load signing key file from engine
140568145229120:error:80067065:pkcs11 engine:ctx_load_privkey:object not found:eng_back.c:858:
140568145229120:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:../crypto/engine/eng_pkey.c:77:
unable to load signing key file
```

I tried to modify the config file and there's no difference in the output even if I entirely remove the `MODULE_PATH` line so my guess is something changed in a way modules should be configured between versions - is that the case? Can anybody push me in a right direction?

Tools like `pkcs11-tool` or `p11tool` still can access the card without issues:
```sh
$ pkcs11-tool --module ~/DIGIPASS/VdsPKCS1164.so -lOy privkey -p env:SC_PIN
Using slot 0 with a present token (0x1)
Private Key Object; RSA 
  label:      
  ID:         b07fe5...
  Usage:      decrypt, sign, unwrap
  Access:     sensitive, always sensitive, never extractable, local
  Allowed mechanisms: RSA-PKCS,MD2-RSA-PKCS,MD5-RSA-PKCS,SHA1-RSA-PKCS,SHA256-RSA-PKCS,SHA384-RSA-PKCS,SHA512-RSA-PKCS,RIPEMD160-RSA-PKCS
Private Key Object; RSA 
  label:      
  ID:         b05eac...
  Usage:      decrypt, sign, unwrap
  Access:     sensitive, always sensitive, never extractable, local
  Allowed mechanisms: RSA-PKCS,MD2-RSA-PKCS,MD5-RSA-PKCS,SHA1-RSA-PKCS,SHA256-RSA-PKCS,SHA384-RSA-PKCS,SHA512-RSA-PKCS,RIPEMD160-RSA-PKCS
```
```sh
$ p11tool --provider ~/DIGIPASS/VdsPKCS1164.so --list-privkeys --login --set-pin $SC_PIN
Object 0:
        URL: pkcs11:model=IDOneCosmo7%207.0.;manufacturer=Oberthur;serial=00-587ED38-A;token=Some%20Business;id=%B0%7F%E5...;type=private
        Type: Private key (RSA-2048)
        Label: 
        Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
        ID: b0:7f:e5:...

Object 1:
        URL: pkcs11:model=IDOneCosmo7%207.0.;manufacturer=Oberthur;serial=00-476DC27-A;token=Some%20Business;id=%B0%5E%AC...;type=private
        Type: Private key (RSA-1024)
        Label: 
        Flags: CKA_WRAP/UNWRAP; CKA_PRIVATE; CKA_NEVER_EXTRACTABLE; CKA_SENSITIVE; 
        ID: b0:5e:ac:...
```

**Comment by dengert** [comment]
Looks like Openssl has its own engine and its own module. You can have your
openssl.conf
And use libp11 an opensc module.

**Comment by cprn** [comment]
I honestly don't understand what you mean. The module, i.e. `VdsPKCS1164.so`, is provided by the card's manufacturer and I was under the impression that `pkcs11.so` engine uses OpenSC under the hood?

**Comment by dengert** [comment]
Looking closer, the location of the engine has changed:

 https://packages.ubuntu.com/focal/libengine-pkcs11-openssl
https://packages.ubuntu.com/focal/amd64/libengine-pkcs11-openssl/filelist
It is:
/usr/lib/x86_64-linux-gnu/engines-1.1/pkcs11.so

This matches what I have on xubuntu 18-4 with bionic

Your conf file is pointing to /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/pkcs11.so that may be an old version. I do not have this on my system.

**Comment by cprn** [comment]
Yes! This is it! And yes, I still have the old version installed - upgrade didn't remove it (which is shame on Ubuntu package maintainer, I think, but I don't think I'll bother them with version gap that big). Thank you very much!
