### ISSUE TITLE
Update INSTALL.md

### ISSUE THREAD

**Issue by stalowyjez** [OpenSC/libp11#362]
Currently to install libp11 on Linux one need to use a few more commands (autoconf etc.) - I believe it should be mentioned in INSTALL.md

**Comment by mtrojnar** [comment]
Nope.  Installing lip11 on Linux does not require autoconf.

**Comment by stalowyjez** [comment]
Uh? For me it works only with autoconf, there is no configure in the main directory, so how you can run it?

**Comment by mtrojnar** [comment]
Which release have you downloaded?

**Comment by stalowyjez** [comment]
Just master

**Comment by dengert** [comment]
There is some  inconsistency 

From: https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.10

Also looks like
 https://github.com/OpenSC/libp11/releases/download/libp11-0.4.10/libp11-0.4.10.tar.gz
has configure but https://github.com/OpenSC/libp11/archive/libp11-0.4.10.zip does not and need to have ./bootstrap run

If you clone from Github, you need to run the ./bootstrap

 which does.  autoreconf --verbose --install --force

**Comment by mtrojnar** [comment]
INSTALL.md is for end-users.
GitHub master branch is for developers.
