### ISSUE TITLE
Is that any way i can create .p12 file?

### ISSUE THREAD

**Issue by chayakornjj** [OpenSC/libp11#368]
Hi All,

Currently i'm using

```
OPENSSL_CONF=engine.conf openssl req -engine pkcs11 -new -key "pkcs11:model=SoftHSM%20v2;manufacturer=SoftHSM%20project;serial=745a5b98b5f7b0b0;token=test-token;pin-value=1234" \
         -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
```

Everything work fine i can get req.pem which generated from pkcs11 engine
How ever i need to use .p12 file 

But i'm not able to get p12 file using this (Due seem like it require key file which i'm don't know how to require key file from PKCS11)
```
OPENSSL_CONF=engine.conf openssl pkcs12 -export -out test.p12 in req.pem                                                                                                                                                                                            
```

Is that any way that i can use p12 file with this hsm? 

You can guide me from start the correct way as well. I'm not expert in HSM.

**Comment by mtrojnar** [comment]
The main purpose of using an HSM is to __prevent__ exporting private keys.
