### ISSUE TITLE
libp11 with openssl and optee_client pkcs11 ta

### ISSUE THREAD

**Issue by Dvergatal** [OpenSC/libp11#370]
I was wondering about usage of libp11 for my project together with [https://github.com/etienne-lms/optee_os/tree/sks-to-pkcs11](https://github.com/etienne-lms/optee_os/tree/sks-to-pkcs11). Because from what i understand the libp11 is for connecting openssl with some other third party pkcs11 implementations? Please correct me if i am wrong.

**Comment by dengert** [comment]
Libp11 defines a OpenSSL engine  and a API than can be called by other applications. The engine code uses the API in libp11 which loads and calls third party PKCS\#11 module.

But [OP-TEE](https://optee.readthedocs.io/en/latest/general/about.html) appears to be some linux kernel interface. In a 10 minute search, it is not clear if they define a PKCS\#11 module or use one.

Best to ask OP-TEE  or https://github.com/etienne-lms .

**Comment by Dvergatal** [comment]
I know what is OP-TEE and yes there is a defined PKCS#11 module for OP-TEE. Etienne-lms has done it in his branch. So if i have a third party PKCS#11 module for OP-TEE it can be called by libp11 engine and then through opennssl?

**Comment by dengert** [comment]
Yes.  The pkcs\#11 module and other parameters are pased via the engine or the openssl config file
https://github.com/OpenSC/libp11/blob/master/README.md#pkcs-11-module-configuration

MODULE_PATH would be the  PKCS#11 module for OP-TEE

**Comment by Dvergatal** [comment]
Ok and does the MODULE_PATH must be the full path to the PKCS#11 module for OPT-TEE or is it being taken from /usr/lib;/lib paths?

**Comment by mtrojnar** [comment]
Please use the full path.  PKCS#11 modules are designed to be opened with dlopen(3), so they are not normally deployed on the dynamic linker path.

**Comment by Dvergatal** [comment]
Ah i see, than it ok to me, because i am compiling this op-tee module and from what i know it deploys it in dynamic linker path. But never the less it can be also a full path:] Thank you all for help i can close now this issue.

**Comment by Dvergatal** [comment]
I'm sorry for reopening this issue but i have come to the real situation when i am testing the hypothesis :] I have now working pkcs11 ttrusted application and a module for pkcs11 to use with openssl. My configuration file looks like this:

```bash
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = /usr/lib/engines-1.1/libpkcs11.so
MODULE_PATH = /usr/lib/libckteec.so
init = 0
```

and this is the command with which i wanted to generate a certificate request for a already stored key on that token:
```bash
[root@rk3399:~]# openssl req -new -x509 -days 365 -subj '/CN=my key/' -sha256 -config engine.conf -engine pkcs11 -keyform engine -key slot_0-tls -out cert.pem
```

But unfortunately it produces me an error:

```bash
547486870672:error:26078067:engine routines:engine_list_add:conflicting engine id:crypto/engine/eng_list.c:63:
547486870672:error:2606906E:engine routines:ENGINE_add:internal list error:crypto/engine/eng_list.c:223:
547486870672:error:260B6067:engine routines:dynamic_load:conflicting engine id:crypto/engine/eng_dyn.c:502:
547486870672:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=pkcs11_section, name=dynamic_path, value=/usr/lib/engines-1.1/libpkcs11.so
547486870672:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:177:module=engines, value=engine_section, retcode=-1
```

Can anybody help resolve this issue?

**Comment by Dvergatal** [comment]
Using this command:

```bash
[root@rk3399:~]# openssl
OpenSSL> engine dynamic -pre SO_PATH:/usr/lib/engines-1.1/libpkcs11.so -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -pre MODULE_PATH:/usr/lib/libckteec.so
```

works and produces an output:

```bash
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:/usr/lib/engines-1.1/libpkcs11.so
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
[Success]: MODULE_PATH:/usr/lib/libckteec.so
Loaded: (pkcs11) pkcs11 engine
```

**Comment by Dvergatal** [comment]
Ok i have went further but now i have a new issue. When i have initialized engine i try to generate signing request with this command:

```bash
openssl req -engine pkcs11 -new -key "pkcs11:object=tls;type=private;pin-value=1234567890" -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
```
and the output is:

```bash
engine "pkcs11" set.
Found uninitialized token
Login failed
Login to token failed, returning NULL...
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
548022168720:error:82074102:PKCS#11 module:pkcs11_login:User pin not initialized:p11_slot.c:240:
548022168720:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:78:
unable to load Private Key
```

but for listing of available slots i see:
```bash
[root@rk3399:~]# pkcs11-tool --module /usr/lib/libckteec.so -L
Available slots:
Slot 0 (0x0): OP-TEE PKCS11 TA - TEE UUID 94e9ab89-4c43-56ea-8b35-45dc07226830
  token label        : foo
  token manufacturer : Linaro
  token model        : OP-TEE TA
  token flags        : login required, rng, SO PIN to be changed, token initialized, PIN initialized, other flags=0x200
  hardware version   : 0.0
  firmware version   : 0.1
  serial num         : 0000000000000000
  pin min/max        : 10/128
Slot 1 (0x1): OP-TEE PKCS11 TA - TEE UUID 94e9ab89-4c43-56ea-8b35-45dc07226830
  token state:   uninitialized
Slot 2 (0x2): OP-TEE PKCS11 TA - TEE UUID 94e9ab89-4c43-56ea-8b35-45dc07226830
  token state:   uninitialized
```

Maybe i should specify on which slot i want to call that command but i dunno how. Maybe someone can point me?

**Comment by dengert** [comment]
Looks like the Found uninitialized token or pin is not initialized and C_Login failed. 

If you really want to see the PKCS11 traffic, test with OpenSC SPY as the `MODULE_PATH:` or --module 
and  env: `export PKCS11SPY=/usr/lib/libckteec.so` and maybe `export PKCS11SPY_OUTPUT=/tmp/spy.txt`
See https://github.com/OpenSC/OpenSC/wiki/Using-OpenSC.
That would show you what slots you module is returning, and what slot was selected and why C_Login failed.

**Comment by Dvergatal** [comment]
I'm sorry but i'am confused now. I should call:
```bash
export PKCS11SPY=/usr/lib/libckteec.so
export PKCS11SPY_OUTPUT=/tmp/spy.txt
```
and than:

```bash
openssl req -engine pkcs11 -key "pkcs11:object=tls;type=private" -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
```
?

**Comment by Dvergatal** [comment]
Ohhh ok i understood now. Changind my MODULE_PATH from /usr/lib/libckteec.so into /usr/lib/pkcs11-spy.so, do the exports and than call the command.

**Comment by Dvergatal** [comment]
Ok i am uploading the [spy.txt](https://github.com/OpenSC/libp11/files/5661160/spy.txt). From what i see it uses slot id 2 but i am not sure. Please if you could verify it.

**Comment by dengert** [comment]
Yes it picked slot = 2

The syntax of the "pkcs11:object=tls;type=private" id defined in https://tools.ietf.org/html/rfc7512. Right now it says look for a match in any slot. It found it in SlotID = 0x3.   You could add "slot-id=1"

**Comment by Dvergatal** [comment]
This my output:
```bash
root@rk3399:~]# openssl req -engine pkcs11 -new -key "pkcs11:object=tls;type=private;slot-id=1" -keyform engine -out req.pem -text -x509 -subj "/CN=Andreas Jellinghaus"
engine "pkcs11" set.
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
547674692752:error:80065064:pkcs11 engine:ctx_load_key:invalid id:eng_back.c:636:
547674692752:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:78:
unable to load Private Key
```

**Comment by dengert** [comment]
Sorry, it wanted to use slotID=2.  Try adding "slot-id=0;" if that is the one with a PIN.
Since you want to access a private key, it has to call C_Login before it can  call C_FindObjects for private key.

**Comment by Dvergatal** [comment]
Ok using serial did the trick :]

**Comment by Dvergatal** [comment]
There is one more thing this command should do a request, but i see that this is a certificate which is self-signed because of the -x509 parameter. If it is not, than the whole operation hangs. What i wanted to do is to sign this request with CA key and than import this new signed certificate into the token....

**Comment by Dvergatal** [comment]
Ok my wrong. The command should look different:
```bash
openssl req -new -subj '/CN=test/' -sha256 -engine pkcs11 -keyform engine -key "pkcs11:serial=0000000000000000;object=tls;type=private"
```

Btw. slot-id=0 does not work.

**Comment by Dvergatal** [comment]
BTW. i have recently verified the code of libp11 api and there isn't slot-id string only id as you can see in file ./src/eng_parse.c:266 this code:

'''c
int parse_pkcs11_uri(ENGINE_CTX *ctx,
...
        /* We are only ever invoked if the string starts with 'pkcs11:' */
        end = uri + 6;
        while (rv && end[0] && end[1]) {
                p = end + 1;
                end = strpbrk(p, ";?&");
                if (end == NULL)
                        end = p + strlen(p);

                if (!strncmp(p, "model=", 6)) {
                        p += 6;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&tok->model, NULL);
                } else if (!strncmp(p, "manufacturer=", 13)) {
                        p += 13;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&tok->manufacturer, NULL);
                } else if (!strncmp(p, "token=", 6)) {
                        p += 6;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&tok->label, NULL);
                } else if (!strncmp(p, "serial=", 7)) {
                        p += 7;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&tok->serialnr, NULL);
                } else if (!strncmp(p, "object=", 7)) {
                        p += 7;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&newlabel, NULL);
                } else if (!strncmp(p, "id=", 3)) {
                        p += 3;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&id, id_len);
                        id_set = 1;
                } else if (!strncmp(p, "pin-value=", 10)) {
                        p += 10;
                        rv = parse_uri_attr(ctx, p, end - p, (void *)&pin, pin_len);
                        pin_set = 1;
                } else if (!strncmp(p, "type=", 5) || !strncmp(p, "object-type=", 12)) {
                        p = strchr(p, '=') + 1;

                        if ((end - p == 4 && !strncmp(p, "cert", 4)) ||
                                        (end - p == 6 && !strncmp(p, "public", 6)) ||
                                        (end - p == 7 && !strncmp(p, "private", 7))) {
                                /* Actually, just ignore it */
                        } else {
                                ctx_log(ctx, 0, "Unknown object type\n");
                                rv = 0;
                        }
                } else {
                        rv = 0;
                }
        }
...
```

**Comment by dengert** [comment]
OK,. I was reading https://tools.ietf.org/html/rfc7512 which defines slot-id, and also says:
 "Slot ID is a Cryptoki-assigned number that is not guaranteed to be
   stable across PKCS #11 module initializations.  However, there are
   certain libraries and modules that provide stable slot identifiers.
   For these cases, when the slot description and manufacturer ID is not
   sufficient to uniquely identify a specific reader, the slot ID MAY be
   used to increase the precision of the token identification.  In other
   scenarios, using the slot IDs is likely to cause usability issues"

So I guess libp11 did not add it. 

It does support the older non-RFC 7512 i.e. where string does not start with "pkcs11:" in `parse_slot_id_string` 
In this case it would be "slot_xxxx" or "slot:xxxx". (very confusing.) 

If you use p11-kit it may have to remap slot-ids, so it is much less useful.

**Comment by Dvergatal** [comment]
OK, so i will stay using token. Thx again. i think i can close it.
