### ISSUE TITLE
Possibility to select reader from OpenSSL loaded module

### ISSUE THREAD

**Issue by Torxed** [OpenSC/libp11#385]
OpenSC supports listing and using specific readers.
But I haven't seen any flags for this in the shared library loaded into OpenSSL:

```
$ opensc-tool --list-readers
0 ...
1 ...
2 ...

$ openssl req -engine pkcs11 -reader 1 -new -key id_45 -keyform engine -x509 -out cert.pem -text
```

When having multiple hardware modules inserted that should sign each other's CSR's etc, it becomes important to select devices more thoroughly. How is this intended to work today?
Unless I'm missing a flag/option some where, I can't make openssl do a `ca` signing procedure because the certificate extracted with `pkcs11-tool` from the ca doesn't match the key used to sign - because there's multiple HSM inserted and I think (assume) OpenSSL with OpenSC libp11 engine selects first-come-first-serve in terms of signing.

If my assumptions are incorrect I apologize, otherwise I would greatly appreciate this feature.

**Comment by dengert** [comment]
The -key option can take a URI as defined  in  [RFC7512](https://tools.ietf.org/html/rfc7512)  and for an example: https://github.com/OpenSC/libp11/blob/master/README.md

**Comment by Torxed** [comment]
> The -key option can take a URI as defined in [RFC7512](https://tools.ietf.org/html/rfc7512) and for an example: https://github.com/OpenSC/libp11/blob/master/README.md

I'm assuming that in the URI will `pkcs11:object=` will point towards the key identifier then?
And is there a reason why this part of the OpenSC libraries are the "only one" that doesn't have the `-reader` functionality?

**Comment by dengert** [comment]
Libp11 and the engine use the PKCS11 API and PKCS11 does not define a "reader" but defines slots.
Also the pkcs11 module does not have to be the opensc-pkcs11.so either.  

Many of the OpenSC utilities are at the PKCS15 level or below and use  "-reader" is used.  

For example, three tokens, one on a contactless reader:
pkcs11-tool --list-slots
Available slots:
Slot 0 (0x0): SCM Microsystems Inc. SCR 355 [CCID Interface] 00 00
  token label        : SmartCard-HSM (UserPIN)
  token manufacturer : www.CardContact.de
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 24.13
  firmware version   : 1.2
  serial num         : DECC0100248
  pin min/max        : 6/15
Slot 1 (0x4): ACS ACR122U PICC Interface 01 00
  token label        : TEST PIV CONTENT SIGNER P384 ...
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : de0a61c93810b7ed
  pin min/max        : 4/8
Slot 2 (0x8): Yubico YubiKey OTP+FIDO+CCID 02 00
  token label        : Doug_Y8
  token manufacturer : piv_II
  token model        : PKCS#15 emulated
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 0.0
  firmware version   : 0.0
  serial num         : 00000000
  pin min/max        : 4/8

**Comment by dengert** [comment]
And pkcs11-tool -O will list all the objects. rfc7512  has the object= i.e. label and type as well as id to distinguish between.

**Comment by Torxed** [comment]
> And pkcs11-tool -O will list all the objects. rfc7512 has the object= i.e. label and type as well as id to distinguish between.

I see. You seam to have dabbled with this way more than I have, and the documentation on this subject is a bit hard to read at times. Could I trouble you by asking, in the example above you mention you have a Yubico YubiKey on slot 2.

How would you approach *(using OpenSSL and libp11)* signing a CSR *(assuming a working openssl.cnf and a already loaded key and cert on the yubikey in slot 9a)* using the YubiKey with all the others inserted as well?

Assuming I have just the yubikey inserted and I'm signing a CSR on file, this works pretty well:
```
openssl ca -config openssl.conf -engine pkcs11 -keyform engine -keyfile 0:1 -extensions usr_cert -days 1 -notext -md sha256 -in csr/test.csr.pem -out certs/test.cert.pem
```

Where `-keyfile 0:1` appears to (probably by luck) represent the slot 9a on the yubikey (here, the naming convention collides a bit it feels because pkcs11-tool defines a slot as a reader and other tools name the slot as the container on the device).
But what would be the more appropriate way, using the URI in that case to catch the correct reader?

*(I'll attach the openssl.conf just in case it helps: https://gist.github.com/Torxed/5cef033fa04525f246047cdb1ea25152)*

**Comment by Torxed** [comment]
@dengert I'd like to thank you for all the help.
The hickup appears to be `-key` does not take the expected URI format. However, `-keyfile` does.
So swapping things around to:

```
$ pkcs11-tool --list-slots   # To find the serial of the device (since it's not the hardware serial of the device, like printed on a yubikey)

$ openssl ca -config openssl.cnf -engine pkcs11 -keyform engine -keyfile "pkcs11:serial={pkcs11_serial}" -extensions usr_cert -days 1 -notext -md sha256 -in csr/test.csr.pem -out certs/test.cert.pem
```

And that seams to do the trick.
