### ISSUE TITLE
README.md queries: `x509 -engine pkcs11 -signkey` generates CSR and not for self signed certificate

### ISSUE THREAD

**Issue by kiranpradeep** [OpenSC/libp11#387]
Below is in README.md under section: Using p11tool and OpenSSL from the command line [[link](https://github.com/OpenSC/libp11/blob/master/README.md#using-p11tool-and-openssl-from-the-command-line)]

>  The second command creates a self-signed certificate for the request, the private key used to sign the certificate is the same private key used to create the request. Note that in a PKCS11 URL you can specify the PIN using the "pin-value" attribute.

As per my understanding, the second command using -signkey generates a certificate signing request(CSR) and not a self signed certificate. That command generates CSR from self signed certificate pre-created in command 1 and private key pre-created using `p11tool --generate-rsa` command. If yes, should the documentation be corrected?

Assuming yes, I was about to raise a PR for documentation correction, but noted that the last command is failing which I could not fix. Kindly find screenshot below. 

![openssl-engine-csr-failure](https://user-images.githubusercontent.com/1491933/105670472-1bc16100-5f07-11eb-86f5-326f10fe370b.png)

**Comment by dengert** [comment]
The first command generates an CSR another name for a req.   (-out req.pem)

The second command using -signkey generates a selfsigned certificate if the input is a CSR i.e. (-in req.pem)

https://www.openssl.org/docs/man1.1.1/man1/x509.html

To see the output of the commands:
openssl req -noout -text -in req.pem 
openssl x509 -noout -text -in cert.out

Both of the commands have problems.
"Found uninitialized token" probably means the command failed. 

The commands are assuming the openssl.cnf has a engine section (or defaults to one)
 
https://www.openssl.org/docs/man1.1.1/man5/config.html 

For use with libp11 see:
https://github.com/OpenSC/libp11/blob/master/README.md#using-the-engine-from-the-command-line

"MODULE_PATH: Specifies the path to the pkcs11 module shared library"
In you case it would be /usr/local/lib/softhsm/libsofthsm2.so (Same at the provider used in other commands) 

You may also want to use the URL output by the p11tool in the the two commands.

**Comment by kiranpradeep** [comment]
Thanks for the reply. Closing.
