### ISSUE TITLE
atfork handler breaks engine initialization

### ISSUE THREAD

**Issue by mtrojnar** [OpenSC/libp11#39]
Commit https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1 breaks applications that fork after engine initialization.  Unless "foreground = yes" is specified in stunnel.conf, stunnel returns the following errors:
```
[0]: error queue: 14179006: error:14179006:SSL routines:tls_construct_server_key_exchange:EVP lib
[0]: SSL_accept: 80004003: error:80004003:PKCS11 library:PKCS11_open_session:Invalid slot ID
[1]: error queue: 14179006: error:14179006:SSL routines:tls_construct_server_key_exchange:EVP lib
[1]: error queue: 800280B3: error:800280B3:PKCS11 library:PKCS11_get_attribute:Session handle invalid
[1]: SSL_accept: 800060B3: error:800060B3:PKCS11 library:PKCS11_enum_keys:Session handle invalid
[2]: error queue: 14179006: error:14179006:SSL routines:tls_construct_server_key_exchange:EVP lib
[2]: SSL_accept: 800280B3: error:800280B3:PKCS11 library:PKCS11_get_attribute:Session handle invalid
[3]: error queue: 14179006: error:14179006:SSL routines:tls_construct_server_key_exchange:EVP lib
[3]: SSL_accept: 800280B3: error:800280B3:PKCS11 library:PKCS11_get_attribute:Session handle invalid
...
```
Commenting out the attempted context reloading in the PKCS11_CTX_reload() function fixes the problem.

**Comment by nmav** [comment]
Actually without that patch applications fail. Applications that fork must reinitialize PKCS#11. Could it be that you are using a module that cannot cope with reinitialization?

**Comment by mtrojnar** [comment]
I tested it with with the OpenSC library with SmartCard-HSM and ePass2003 hardware.
@nmav: Which software/hardware did you test?  Which applications failed without this https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1?

**Comment by nmav** [comment]
opensc was buggy when handling fork. Could it be that you are seeing the issue solved in: https://github.com/OpenSC/OpenSC/pull/494 ?

About changing to explicit fork handling it doesn't work. No application was using it because that's an oddball PKCS#11 requirement no-one knows about. The pkcs11 library should handle it.

**Comment by mtrojnar** [comment]
@nmav: The bug does not seem to be caused by OpenSC.  I'm testing it on the latest git OpenSC and libp11.  `pkcs11-tool --test-fork --login --test` also works flawlessly.

**Comment by mtrojnar** [comment]
@nmav: I improved the coverage of your `fork-test` application, so it also tests other resilience to fork() in other places: https://github.com/OpenSC/libp11/pull/40

**Comment by mtrojnar** [comment]
The error message is:
```
~/libp11/tests$ ./fork-test /usr/local/lib/opensc-pkcs11.so 1234
Slot manufacturer......: OpenSC (www.opensc-project.org)
Slot description.......: Feitian ePass2003 01 00
Slot token label.......: mtrojnar (User PIN)
Slot token manufacturer: EnterSafe
Slot token model.......: PKCS#15
Slot token serialnr....: 1F714E6300030020
fatal: pkcs11_sign failed
140704066696848:error:25066067:DSO support routines:func(102):reason(103):dso_dlfcn.c:187:filename(libgost.so): libgost.so: cannot open shared object file: No such file or directory
140704066696848:error:25070067:DSO support routines:func(112):reason(103):dso_lib.c:232:
140704066696848:error:260B6084:engine routines:func(182):reason(132):eng_dyn.c:465:
140704066696848:error:80004003:PKCS11 library:PKCS11_open_session:Invalid slot ID:p11_slot.c:131:
authentication failed.
```

**Comment by nmav** [comment]
What is the output of "pkcs11-tool --test-fork"?

**Comment by mtrojnar** [comment]
```
*** Calling C_Initialize in forked child process ***
Using slot 1 with a present token (0x1)
```

**Comment by mtrojnar** [comment]
I noticed that the output of fork-test suggests that pkcs11_sign returns a bunch of errors.  Apparently, it is a deficiency of the fork-test application.  I fixed it in https://github.com/OpenSC/libp11/pull/41.  Only the last of those errors (`Invalid slot ID`) is caused by `PKCS11_login`.

I guess PKCS11 functions should clear the error queue before successful completion.  I will submit a fix for it (hopefully tomorrow).

**Comment by mtrojnar** [comment]
I submitted the fix as https://github.com/OpenSC/libp11/pull/42.

**Comment by mtrojnar** [comment]
@nmav: I submitted a fix for issue https://github.com/OpenSC/libp11/issues/39 in pull request https://github.com/OpenSC/libp11/pull/43.

**Comment by mtrojnar** [comment]
After https://github.com/OpenSC/libp11/pull/43 it successfully completes `PKCS11_login` and then fails on `PKCS11_enumerate_certs`:
```
$ tests/fork-test /usr/local/lib/opensc-pkcs11.so 1234
Slot manufacturer......: OpenSC (www.opensc-project.org)
Slot description.......: Feitian ePass2003 00 00
Slot token label.......: mtrojnar (User PIN)
Slot token manufacturer: EnterSafe
Slot token model.......: PKCS#15
Slot token serialnr....: 1F714E6300030020
PKCS11_enumerate_certs failed
140194241341072:error:800280B3:PKCS11 library:PKCS11_get_attribute:Session handle invalid:p11_attr.c:52:
authentication failed.
```
`C_Initialize` (quite obviously) also invalidates session handles...

@nmav: Implicitly calling `C_Initialize` on `fork` (which completely resets the internal state of the PKCS#11 library) breaks lots of things...  The PKCS#11 interface is definitely **not** stateless. I'm not sure whether fixing all of the bugs introduced by https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1 is feasible (at least without a complete rewrite of the libp11 library).  I would opt for reverting https://github.com/OpenSC/libp11/commit/ecb83dad73ae39afb24b3cea294d44b7f3e3a6f1 completely.

**Comment by mtrojnar** [comment]
I have updated pull request https://github.com/OpenSC/libp11/pull/43, so it passes fork-test with `opensc-pkcs11`:
```
$ ./fork-test /usr/local/lib/opensc-pkcs11.so 1234
Slot manufacturer......: OpenSC (www.opensc-project.org)
Slot description.......: Feitian ePass2003 01 00
Slot token label.......: mtrojnar (User PIN)
Slot token manufacturer: EnterSafe
Slot token model.......: PKCS#15
Slot token serialnr....: 1F714E6300030020
authentication successfull.
```
The atfork functionality is still not thread-safe, but this is a separate issue.  I will issue another pull request to address it.
