### ISSUE TITLE
I need add the  PKCS#11 module of hardware vendors provide if I want to use pkcs11, right?

### ISSUE THREAD

**Issue by haohaole1230** [OpenSC/libp11#391]
I' m a new user of pkcs11, if I want to use pkcs11,  I must add the  PKCS#11 module (like OpenSC) of hardware vendors provide , right?

**Comment by haohaole1230** [comment]
And is libpkcs11.so a common interface to support other PKCS#11 module besides OpenSC? Thank you.

**Comment by mtrojnar** [comment]
Right. Right. Yes.
