### ISSUE TITLE
thread locking issue crashes bind9/named

### ISSUE THREAD

**Issue by hcoin** [OpenSC/libp11#393]
Multiple threads accessing private keys and adding/deleting pins needs more locking to prevent the crashes and core dumps detailed here:
https://bugzilla.redhat.com/show_bug.cgi?id=1940659

**Comment by fabled** [comment]
There is various issues in this regard, and I am currently working on a fairly large refactoring PR to make libp11 more thread friendly. Auditing this concurrency issue is part of work. I hope to have a PR in few weeks time. The bug can be assigned to me by a admin if wanted.

**Comment by hcoin** [comment]
I'm heavily rewriting eng_back.c, hopefully I'll have a version for you to look at that at least allows named to run without crashing in the context of several threads worth of dnssec updates/ongoing activity.

**Comment by fabled** [comment]
I have now completed first good rounds of the refactoring: see https://github.com/OpenSC/libp11/pull/396

It adds various fixes to the thread safety, and also puts in rudimentary locking that should probably fix the issue you are having.

**Comment by hcoin** [comment]
Take a look at these changes to eng_back.c  It consolidates much repeated code, adds two layers of locking, fixes a LibreSSL logic bug, passes all the tests, and -- named does not die under conditions of heavy load.

[eng_back.c.gz](https://github.com/OpenSC/libp11/files/6194122/eng_back.c.gz)

**Comment by fabled** [comment]
There is definitely some good stuff in it. But as you also note, there's several things in one change: repeated code refactoring, locking changes, logic changes and the PIN allocation change. It would be helpful to have them as individual commits to help review.

I did modify the locking quite drastically in the referenced PR. However, you do additional locking in places I have not yet looked. So this probably fixes additional issues. I am also contemplating which is faster: enumerate all keys + O(n) lookup from the enumeration results; or just doing a PKCS#11 Find Object call with proper attributes for each URI. Considering the enumerate all keys currently refreshes the cache on every call, I think it would be faster to just do proper Find Objects with given attributes and drop the cache which is not really used. Or at least make it partial cache which contains only the items specifically searched for (not the full key data from the HSM which could be hundreds of keys in certain cases).

Please look at also the work I did. Perhaps doing this on top of the that branch? But at least I would hope to see PR with this split into 3-4 individual commits.

**Comment by hcoin** [comment]
One structural issue to think about:  If a person logs in via the ui, then another thread uses a certificate with pkcs11: parsing which specifies a token, the old code would leave the first thread logged in  under the parsed token.     I took one approach to retaining and retrying a UI login pin, but that needs thinking through.  It wasn't obvious to me logging in under the ui pin after the parsed token was not needed for that particular task was always the correct thing to do.   Whatever the answer it will have to be sensitive to the slot as well.

There were just too many changes all dependent upon one another to allow individual commits to pass the test suite.  Treating the pin as a lock protected atomic structure (length, cleansing after use, protection against overlong pins, etc.)  even now the code in one case retains the past author's use of the length element to indicate both a maximum and a string length.

It happens I knew nothing of this project 6 days ago, and this is the first 'c' code I've written in 10 years.  I had to fix this under conditions of time pressure because a structurally critical dns resolver crashed because of it, in the context of dnssec operations ongoing by many threads using named with -E pkcs11, even oddly re-entrantly owing to the p11 proxy, In order to support a project that uses this as a sub-sub-sub-sub-sub component.  Having invested sufficiently to climb the project learning curve I'm willing to work on this further and look at your work a layer up as well, but that would take a business discussion to allocate the time.  If that's of interest to anyone kindly contact me privately.

**Comment by hcoin** [comment]
While we're at it, the only way I could cause the 'verbose' debugging to occur was to default the value to 1, at least on the fedora rawhide version at least I couldn't get it to pay attention to 'verbose' keywords in [pkcs11_section]

**Comment by hcoin** [comment]
Our efforts appear to be in related but different areas.  Hopefully folks interested in all this can navigate a way to make use of them all.  I posted a build log on the redhat bug thread showing it passed all the tests, and an rpm.  At the moment the same VM that crashed within an hour after a dozen tries under dnssec/named/multithreaded p11 load has run without issue for 18 hours.

**Comment by hcoin** [comment]
Proof of full test suite compliance with the correct eng_back.c is available here:  https://bugzilla.redhat.com/show_bug.cgi?id=1940659
Notice ISC's named with -E PCKS11 no longer segfaults with this fix.   Opendnssec pushes several threads through eng_back.c at the same time.  Also note the fix cures some security holes.   An open question:   When a PKCS11 URI's login password has completed the calls related ... should that be thought of as the 'user' 'removing' the 'smart card',  or 'logging out' or sure the credential 'persist' for the next user of that 'slot'?   One person's feature is another's security hole.

**Comment by mtrojnar** [comment]
Can you confirm that PR #396 fixes this issue?

**Comment by fabled** [comment]
I can try to analyze and make proper commits out from the changes from @hcoin. It does add some additional locking that might be needed. There's also good simplifications (merging common code) that would help in readability. I hope to have a PR of that later this week.

**Comment by fabled** [comment]
I suspect commit aaccad6e116acf0109a9a3f473704379070dad53 from PR #396 should fix the crashes seen, and probably it fixes some additional things not fixed in the changes posted in this issue.

The changes I see in the given file are:
 1. struct st_pin and using it throught the code base
 1. additional login_lock
 1. new helpers (find_label_and_id_in_slot and find_matching_slots_with_tokens), used in 1) ctx_load_cert and 2) ctx_load_key

I am not sure if the first change is needed. It would first make sense to try to document how the login model should work. The problem is that PKCS#11 user model is basically non-existent, and the complication that different sessions share the login state. Essentially the key PIN is the token PIN. The exception is "always authenticate keys" where a separate per-usage specific login is done, can specify a key-specific PIN. So currently the code base more or less assumes that the key PIN = token PIN. And I don't think it's good idea to change that until the plan is formalized better.

For the second point, the commit I did fixes the issues by doing locking on the upper level. It is required because the libp11 functions used are not thread safe. Thus, the login_lock is not useful as-is.

Finally the new helpers, and duplicate code clean up would probably be good to go, but it's quite strongly coupled with the other changes. It might make sense to write this separately -- though, I'm leaning into instead creating a pkcs11 template from the uri, and always using the FindFirstObject APIs. I think that might be faster approach than the current "enumerate all and match manually", especially if the token has large amount of keys.

**Comment by hcoin** [comment]
I added thread safety I added to the pin allocation code, so that should another thread do a check for the existence of
ctx->pin after this in eng_back.c
		ctx->pin = OPENSSL_malloc(MAX_PIN_LENGTH+1);
but before the next line: ctx->pin after this in eng_back.c, for example,
		ctx->pin_length = MAX_PIN_LENGTH;
the system would not crash as it does. 
What you added did not preserve that, and unless I missed something didn't preserve the coalesing of all that redundant logic between keys and certificates.  Perhaps what you added removed the need for that?  Please explain.

**Comment by fabled** [comment]
>  Perhaps what you added removed the need for that?

Commit aaccad6e116acf0109a9a3f473704379070dad53 adds mutex locking to all callers of `ctx_load_key` and `ctx_load_cert`. This basically does mutex locking on upper lever, and guarantees the PIN field is not written concurrently to.

The higher level mutex is needed because those functions also call `PKCS11_enumerate_certs`, `PKCS11_enumerate_keys`, and `PKCS11_enumerate_public_keys` which are NOT thread safe. I believe there might be still a window of crash if this not done. However, BIND9 seems to do key reload quite rarely so this is fairly small window - but still exists.

**Comment by hcoin** [comment]
I suggest you reconsider keeping the code that treats a ctx token as a threadsafe atomic entity: allocated in exactly one place and freed and cleaned in exactly one place -- in a way that can be proven for all possible calls and use cases.  This over against hoped for expected pathways.

**Comment by fabled** [comment]
Could you elaborate what exactly you mean? I assume you refer to some additional changes you also did not address in your changes, perhaps refactoring the interaction of `eng_front.c` and `eng_back.c`?

**Comment by mtrojnar** [comment]
Can you still reproduce https://bugzilla.redhat.com/show_bug.cgi?id=1940659 agains the current master branch of libp11?  If so, please submit a stack bactrace.

**Comment by hcoin** [comment]
The latest freeipa dnssec upgrade using the current code exhibits the problem.  It replaced the version I patched above, and the database was corrupted within 30 minutes.

**Comment by hcoin** [comment]
A short look at most of the public functions in the current eng_back.c shows most (not all) of the functions would fail if a second or further thread were to enter them before a prior one finished.  For example ctx->pin and ctx->pin_length are not created or updated or destroyed atomically, mostly they appear unprotected by a mutex as well.  There is a UI call of undetermined length where ctx->pin is an argument to be updated during which other functions referencing it might be called.   Whether those secondary threads and calls are errors and ought not occur because of higher level code is more of an aspirational question, good defensive programming practice would make such questions moot.   While I'm not an expert in this, I sense there is a bit of an architectural tension that leads to less default concern and testing about multithreading here.  My hunch is most using and supporting this code think contexts and pins and slots change reasonably slowly, on time scales akin to inserting and removing smart-cards and so on.  Such are not likely to manifest multithreading issues, and if done on 'recent fast enough hardware' a user card insert/and/remove thread is unlikely to overlap one other machine speed thread. However, these routines are used very heavily by opendnssec and through that bind9/named with key pairs in the many dozens supported by softhsm2 -- with contexts and pin settings/removals that change concurrently and at machine speeds with potentially dozens of not just threads but concurrently running threads.

**Comment by mtrojnar** [comment]
I merged a major rewrite of the threading code.  Can you check if this issue still affects the current master?

**Comment by mtrojnar** [comment]
Apparently not.  I'm closing this issue.
