### ISSUE TITLE
One process multiple workloads issue

### ISSUE THREAD

**Issue by Eliot-Roxbergh** [OpenSC/libp11#407]
I have one process which may have multiple workloads at the same time interacting with libp11 (e.g. Erlang VM running multiple workloads, which to the OS looks like one process).
However, I run into problems with both libp11 C API and libp11_engine (two unrelated issues).

**Without engine;**
The single process is calling libp11, however, it has multiple workloads active at the same time - and needs to call PKCS11_enumerate_slots for each.
So there are multiple PKCS11_CTX present for the single process, each needs to be freed at some point and their sessions released by calling PKCS11_release_all_slots.
This creates a problem, when the first workload does this and exits, the other's sessions are invalidated. (at the same time, release_all_slots needs to be called for each workload to free their memory.)
_"C_CloseAllSessions closes all sessions an application has with a token"_

As far as I can see, this would be resolved if pkcs11_release_slot only issues C_CloseSession for its own active sessions (as set in PKCS11_CTX), and not as currently done with C_CloseAllSessions.

**With engine;**
When using the engine, I instead get another problem because it only reads the slot information once.
For instance, if a key is written to the HSM after the engine has already been is initialized, this key will not be found. Either the process needs to restart, or the application manually call RE_ENUMERATE.

1) start (long-lived) Erlang process
2) generate keys for workload A
3) start workload A
    p11-engine asks for all slots and gets A's key
4) generate keys for workload B
5) start workload B
6) error -> p11-engine, slots are already loaded but B's key cannot be found

**Comment by dengert** [comment]
What versions of libp11,  engine, OpenSSL are you using?
What pkcs11 module(s) are you using? 

PKCS11 is designed for only one instance of the lib per application (process). So having "multiple PKCS11_CTX present for the single process" may not appropriate. pkcs11_release_slot applies to all sessions for that slot. 

Maybe your workloads need to share a single PKCS11_CTX per slot and  pkcs11_release_slot only gets called when the application is done with the slot. Note the login state is per slot also. 

Most PKCS11 modules supports threads. Does the Erlang VM support threads? 

These may also related:
https://github.com/OpenSC/libp11/issues/365
https://github.com/OpenSC/libp11/pull/396

**Comment by Eliot-Roxbergh** [comment]
libp11 (& engine) = 779350e92f47f1d262f6b7e4c5e86c7b1553918a
OpenSSL = 1.1.1g
SoftHSMv2 = 2.6.1+

Okay, in that case we could use the engine and as you mention re-enumerate (#365->#398), which could yield something like the following;

```
EVP_PKEY *pkey = ENGINE_load_private_key(engine, "<uri>", NULL, NULL)
if (!pkey) {
    ENGINE_ctrl_cmd_string(engine, "RE_ENUMERATE", NULL, 0);
    pkey = ENGINE_load_private_key(engine, "<uri>", NULL, NULL)
}
return pkey;
```

However, it seems like re-enumerate would leak memory, according to #403

Once again the steps would be something like this;
1. start (long-lived) Erlang process
2. generate keys for workload A
3. start workload A
    p11-engine asks for all slots and gets A's key
4. generate keys for workload B
5. start workload B
    -> re-enumerate (leak in libp11_engine as per #403)

**Comment by dengert** [comment]
A lot of these issues arise from PKCS11 specs  and loading a module. C_LoadModule
mod->handle = dlopen(mspec, RTLD_LAZY | RTLD_LOCAL);
dlsym(mod->handle, "C_GetFunctionList");

The handle returned may be the same for each time it is loaded. In effect the module will then have no way to 
differentiate that is is being called by a different  `PKCS11_CTX *ctx`. 

In fact if `C_Initialize` is called more then once, it will return `CKR_CRYPTOKI_ALREADY_INITIALIZED` in other words, only one PKCS11 instance per process. 

The memory leak should be trivial to fix See https://github.com/OpenSC/libp11/issues/403#issuecomment-848039420

**Comment by dengert** [comment]
@Eliot-Roxbergh  in https://github.com/OpenSC/libp11/issues/403#issuecomment-849494888 @ebenwar says he has a solution your "Without engine" problem, but is not allowed to publish the fix. What he outlined sounds reasonable if you want to try and implement it.

**Comment by Eliot-Roxbergh** [comment]
So the current status of this issue is the following,

**Without engine**, answer: you should not have more than one libp11 instance per process.
But it is possible to have multiple threads to the same libp11 instance, although this would require the mentioned proposed [fix (#403)](https://github.com/OpenSC/libp11/issues/403#issuecomment-849494888) to avoid closing all sessions across threads on exit --> (PR needed).

**With engine**, answer: Yes, you must manually re-enumerate to get up-to-date objects.
However, this leaks memory according to #403 --> (not solved yet).

I'm not able to implement this PR right now, but I will try to come back to this.

**Comment by mtrojnar** [comment]
Is this issue still reproducible against the current master?

**Comment by ebenwar** [comment]
Due to the problem we have seen we decided to implement our own engine using PKCS#11 api direct.
