### ISSUE TITLE
Slot/key/certificate design issues

### ISSUE THREAD

**Issue by fabled** [OpenSC/libp11#410]
As noted in comment https://github.com/OpenSC/libp11/issues/403#issuecomment-851285128, the current way of caching slot/key/certificate data is not thread safe, and makes the libp11 API somewhat unusable or at least tricky to use for multi threaded applications. Since the openssl engine module uses these APIs internally, it also affects the openssl engine multi thread safety (though this is less of a problem due to openssl engine locking).

Current API and implementation comments:
 - PKCS11_enumerate_slot() always updates by reallocating per-caller given `PKCS11_SLOT` array. 
   - No information from slots is cached over calls, all `PKCS11_SLOT*` pointers.
   - Application can and must maintain a separate array for each thread, or do locking if it wants to use them safely.
 - `PKCS11_enumerate_public_keys()` and `PKCS11_enumerate_private_keys()` return library allocated and cached array of `PKCS11_KEY` objects.
   - If objects have not changed, the pointers do not change.
   - On new objects, the whole `PKCS11_KEY` array gets reallocated, and all object pointers might change (if this happens an object specific `update_ex_data` callback updates the moved data structure)
   - Objects deleted from token between enumeration are not detected, and are kept in cache (they become stale).
   - Algorithms to access cache are slow O(n) ones (to search), and O(n^2) to refresh cache.
 - `PKCS11_enumerate_certificates()` is basically a copy-paste version of the one for private/public keys, but just with the different `PKCS11_CERT` object type

The openssl engine internal `ctx_load_*` functions internally enumerate all objects of requested type, and do manual matching against the cached objects causing to cache everything with the O(n^2) algorithm and then using O(n) algorithms to find the requested object.

Given the above it might make sense to redesign this API, and I am creating this ticket to discuss potential new API and/or changes to the way the object URIs are searched.

Ideally, I would like to have APIs with the following design criteria:
 - One `PKCS11_enumerate_objects()` function that can search any type of objects. Design the arguments so that it's multithread safe (either it returns object pointers to caller allocated memory, or has counter pair to release the library allocated memory)
 - Provide `PKCS11_load_object_by_uri()` exported, which is the function also used by the engine to lookup URIs to objects. Ideally this will internally construct appropriate PKCS#11 attribute template, and always search exactly once for exact objects from the token. It would not enumerate all tokens. This minimizes PKCS#11 calls, as only matching objects are queried from the PKCS#11 module.
 - Consider dropping the whole object cache. It seems to slow down things with slow algorithms, and in all cases the whole object tree is enumerated to refresh the cache. In most cases it seems to essentially only slow down things. Most PKCS#11 libraries likely cache things if they access slow or remote hardware anyway, making it only a double-cache using memory.

Does the above make sense? What would be the approach to take on this? Should I make a PR to suggest new API? Or should this be first discussed more? Any better ideas, or other comments and ideas regarding this matter?

**Comment by fabled** [comment]
Slightly related to PR #409 which is starting the path to merge cert/key handling. Similar merging can be done in many more places.

**Comment by ebenwar** [comment]
I like this idea.
This was our approach when we found and started to investigate if we could use libp11's engine.
This solution would make our application's integration with PKCS#11 very simple, only a handful lines of openssl ENGINE api code.
At least for keys, a pity that openssl ENGINE api doesn't support loading certificates, even though it can be handled by a ENGINE ctrl command as currently done in pkcs11_engine.

**Comment by fabled** [comment]
@mtrojnar Ping. Any thoughts or comments on on this ticket? I'm wondering if I should spend time on making PR on the suggested things or not.

**Comment by mtrojnar** [comment]
My comments sorted by priority:
 - Thread safety issues may be critical in some applications, although I expect most multithreaded applications to only perform key lookup at startup, before spawning additional threads.  Is it possible to make the code thread safe without changing the public API?
 - I fully support removing copy-pasted implementation wherever possible as long as it does not change the public API.
 - While I agree that O(n^2) code looks ugly, I don't expect many PKCS#11 tokens to have n>1000 keys, where this could become an actual performance issue.  This should only be addressed  if the solution does not make the code even less readable.
 - Lookup, on the other hand, is an actual performance issue on physical devices.  Retrieving the list of keys takes ~100ms on many PKCS#11 tokens even for n<10.  I wouldn't be so eager to drop the cache, but I already thought about making the cache optional (disabled by default).

**Comment by fabled** [comment]
> My comments sorted by priority:
> 
>     * Thread safety issues may be critical in some applications, although I expect most multithreaded applications to only perform key lookup at startup, before spawning additional threads.  Is it possible to make the code thread safe without changing the public API?

Depends. Generally this is true for short term / command line style programs. Daemon style programs often reload keys occasionally due to rekeying.

>     * I fully support removing copy-pasted implementation wherever possible as long as it does not change the public API.

The problem is that the public API has contract that does not fit the multi threaded program usage. I suppose the approach is then to do proper internal functions, and implement the current public API as a shim using those. Potentially exposing some of the new things as part of the public API as well.

>     * While I agree that O(n^2) code looks ugly, I don't expect many PKCS#11 tokens to have n>1000 keys, where this could become an actual performance issue.  This should only be addressed  if the solution does not make the code even less readable.

PKCS#11 is generic crypto API. Normally the small tokens have limited amount of keys. The appliance style high-performance devices on the other hand can have huge amount of keys. Disabling cache by default, as suggested in the next point, is probably a good compromise here. Alternative is to make the cache a hash or similar. The other problem with cache is, if some other process uses the same device, a PKCS#11 is still needed to refresh the cache. Again, normally not a problem on small tokens, but on big network appliances it can be...

>     * Lookup, on the other hand, is an actual performance issue on physical devices.  Retrieving the list of keys takes ~100ms on many PKCS#11 tokens even for n<10.  I wouldn't be so eager to drop the cache, but I already thought about making the cache optional (disabled by default).

Right.

I'll try to work on something and do one or two incremental PRs on this topic. We can continue discussion based on the PR then.

**Comment by fabled** [comment]
>     * Is it possible to make the code thread safe without changing the public API?

Making the public API itself thread safe is problematic on many levels. Making the OpenSSL plugin thread-safe while keeping the public API compatible, is likely doable but slightly cumbersome.

The root problem is that the internal caches (of slots and keys/certs) are arrays of relevant structs. These array item pointers are used then as the main object "handles". When the enumeration API is called, it will can invalidate all old pointers or "handles" which makes the whole thing break. See also https://github.com/OpenSC/libp11/commit/0ccf3dbcc03df6da8332de2319b1b2826cb970cb#commitcomment-52744359.

Having analyzed the options a bit more, I can amend the original comment with the following observations and recommendations.

1. `PKCS11_SLOT` and `PKCS11_TOKEN` API. `PKCS11_enumerate_slots` always rediscovers everything, `PKCS11_release_all_slots` frees them. `PKCS11_TOKEN` is never allocated/released directly, it happens indirectly via `pkcs11_check_token` on selected API calls.
    - Simplest is likely to keep internal master cache of slots in the `PKCS11_CTX`. At least for the `PKCS11_SLOT_private` structs.
    - Amend the `_private` struct with the fields from `PKCS11_token` which are needed for library internals.
    - Use internal only the `_private` struct and keep the `PKCS11_TOKEN` as public API handle struct only.
    - On enumerate, can just fill the data for the user with copies. Allow multiple PKCS11_TOKEN structs to refer to the same internal `PKCS11_TOKEN_private`.
2. `PKCS11_KEY` and `PKCS11_CERT`. `PKCS11_enumerate_{keys,public_keys,certs}` also return array of relevant struct. Also being able to realloc/move the internal cache. It keeps the master copy of these object arrays in `PKCS11_TOKEN_private`. User cannot free it. If another thread re-enumerates, the old pointers go stale.
    - Same concept make the public structs handle structs which contain only copies / shared pointers to the data. Main copy of the data would be moved to the `_private` structs.
    - Possibly makes sense using a `PKCS11_OBJECT` type for both the _KEY and _CERT. Would allow sharing more of the code in type safe manner.
3. I would likely unmarry the OpenSSL code completely from the public libp11 API and not have it use them at all.
4. Not use any of the full enumeration code for openssl code. Just discover individual objects and cache them.
5. One more observation is that the OpenSSL objects and libp11 objects are not linked.
    - Currently enumeration of objects does not remove stale entries so things sort of work (but blow up when the slots are enumerated or refereshed)
    - This likely needs additional work to synchronize things so that the libp11 cached object does not get deleted until the OpenSSL objects connected it are removed (meaning adding reference counting for the `PKCS11_OBJECT` type).
    - In pure OpenSSL plugin this would be easier solved by caching the OpenSSL objects and just associate the needed pkcs#11 data with it directly. The current model of having libp11 structs be the main structs, make this difficult.
    - Likely not huge problem in OpenSSL engine only usage. More problematic when libp11 api user converts PKCS11_KEY to OpenSSL PKEY object.

The above changes are quite intrusive. And would still not make the public API safe, but would allow implementing safe OpenSSL plugin. Given the complexities, and the original design, it'll probably make sense currently to use directly PKCS#11 in multi threaded applications instead of the simple libp11 API. And at this point it might be difficult to suggest thread safe libp11 api. There's lot of complexity on how to do it, and highly depend on what kind of object caching model would be used.

I will try to work on a PR to implement some of the above to get closer to fixing the OpenSSL engine thread safety.

**Comment by fabled** [comment]
Most of the important things are now implemented in #414. However, the implications from the public API design and trying to keep API compatibility are quite limiting. It seems it would be simpler to rewrite the OpenSSL engine directly to use PKCS#11 than to fix things with the libp11 api. If someone wants to sponsor a clean openssl-to-pkcs11 engine, you can contact me privately. Otherwise the latest PR reflects things that should get things in fairly good condition.

**Comment by dengert** [comment]
OpenSSL-3.0. is headed to deprecating engines, in favor of providers.  
https://wiki.openssl.org/index.php/OpenSSL_3.0 Section 1.7 says:
"Authors and maintainers of external engines are strongly encouraged to refactor their code transforming engines into providers using the new Provider API and avoiding deprecated methods."

I would like to this as the goal of future changes in libp11 or some other package.
