### ISSUE TITLE
libp11 fails to build with VS2010

### ISSUE THREAD

**Issue by mxraw** [OpenSC/libp11#420]
In src/p11_rsa.c line 403 ff we find:

`static int pkcs11_rsa_free_method(RSA *rsa)
{
	RSA_set_ex_data(rsa, rsa_ex_index, NULL);
	int (*orig_rsa_free_method)(RSA *rsa) =
		RSA_meth_get_finish(RSA_get_default_method());
	if (orig_rsa_free_method) {
		return orig_rsa_free_method(rsa);
	}
	return 1;
}`

This is wrong. Correct would be

`static int pkcs11_rsa_free_method(RSA *rsa)
{
	int (*orig_rsa_free_method)(RSA *rsa) =
		RSA_meth_get_finish(RSA_get_default_method());
	RSA_set_ex_data(rsa, rsa_ex_index, NULL);
	if (orig_rsa_free_method) {
		return orig_rsa_free_method(rsa);
	}
	return 1;
}`

VS2010 does not allow initialising variables after the first function call in a block.

**Comment by mtrojnar** [comment]
Please submit suggested changes as pull requests.
