### ISSUE TITLE
How to chosse slot to sign with libengine and openssl?

### ISSUE THREAD

**Issue by UsuarioADSIB** [OpenSC/libp11#422]
Hello,
I need to sign from c++ with ePass2003 tokens.
I'm using engine from openssl and it works good, but I need to use many tokens connected at the same time and I don't know how to select the slot.
Can you help me?
Tanks,

**Comment by dengert** [comment]
OpenSSL engine support can use the libp11 engine, that supports the use of PKCS11 URI https://datatracker.ietf.org/doc/html/rfc7512

**Comment by dengert** [comment]
Sorry, hit wrong key.

OpenSSL engine support can use the libp11 engine, that supports the use of PKCS11 URI https://datatracker.ietf.org/doc/html/rfc7512

An example is https://p11-glue.github.io/p11-glue/pkcs11-uris.html

**Comment by UsuarioADSIB** [comment]
Amazing, it was really helpful.
But I'm still having troubles.
When I use
`ENGINE_load_private_key(pkcs11, "pkcs11:id=%37%32%36%32%35%35%32%37%38%33%38%39;type=private;pin-value=12345678", 0, 0);`
it works fine, but when I use slot-id=1
`ENGINE_load_private_key(pkcs11, "pkcs11:id=%37%32%36%32%35%35%32%37%38%33%38%39;type=private;pin-value=12345678;slot-id=1", 0, 0);`
It doesn't work returning:
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
PKCS11_get_private_key returned NULL
I'm not sure to understand why, can you help me?

**Comment by dengert** [comment]
https://github.com/OpenSC/libp11/blob/master/src/eng_parse.c#L332-L381 actually only parses a subset or RFC 7512. "slot-id" is not one of them. CK_SLOT_ID can vary and is assigned by the PKCS11 library. So it is not a good parameter to set in a URI as the slot-id may be different the next time you use the token. See PKCs\#11 "C_GetSlotList"

```
   +----------------------+---------------------+----------------------+
   | slot-id              | Cryptoki-assigned   | decimal number of    |
   |                      | value that          | "CK_SLOT_ID" type.   |
   |                      | identifies a slot   |                      |
   +----------------------+---------------------+----------------------+
```
 It also looks like you could  replace: `id=%37%32%36%32%35%35%32%37%38%33%38%39;`
with `id=726255278389;` as these are decimal digits. 
You could differentiate between tokens using `serial=` or `token=`

**Comment by UsuarioADSIB** [comment]
Thanks dengert, it's working now.
I really appreciate your help.

**Comment by mouse07410** [comment]
I suggest you identify and point at the keys rather than their slots. 

List the keys via `p11tool`.
