### ISSUE TITLE
C_Decrypt called with wrong mechanism

### ISSUE THREAD

**Issue by minderdl** [OpenSC/libp11#426]
In the log file of our pkcs#11 library we see that C_DecryptInit is first called with mechanism 0, which fails of course, then with mechanism 1, which succeeds. Mechanism 0 is CKM_RSA_PKCS_KEY_PAIR_GEN and does not make sense for C_Decrypt*. Mechanism 1 is CKM_RSA_PKCS, which we want to have.

Looking into the code, I find pkcs11_pkey_rsa_decrypt calling first pkcs11_try_pkey_rsa_decrypt and then probably pkcs11_private_decrypt, which explains the two different calls.

In pkcs11_try_pkey_rsa_decrypt, mechanism is initialized to 0, but in the CKM_RSA_PKCS case of the padding switch mechanism.mechanism is not set to CKM_RSA_PKCS similar to the RSA_PKCS1_OAEP_PADDING case.
Moreover, it's also wrong that CKM_RSA_PKCS is used in the case statement since CKM_RSA_PKCS is not a valid value for the openssl padding. In fact, it must be RSA_PKCS1_PADDING. Just by accident both values are the same.

**Comment by mtrojnar** [comment]
Thank you for your analysis.
