### ISSUE TITLE
Support ed25519 on p11 engine

### ISSUE THREAD

**Issue by annerajb** [OpenSC/libp11#427]
Right now p11 engine does not support ed25519. This was added on OpenSSL 1.1.1 using a separate type ev_pkey and you cannot reuse the ec_pvkey data type. 

I have a pull request that got it implemented but only on OpenSSL 3.0. 

I can clean it up it had a few threading issues on openssl 1.1.1 but it was before master got all the commits regarding threading that make it seem promising would help.

**Comment by mtrojnar** [comment]
BTW: Which PKCS#11 modules support ed25519?

**Comment by mtrojnar** [comment]
It doesn't look like anyone is interested in adding this feature.  Please reopen if I'm wrong about it.
