### ISSUE TITLE
Release date for libp11-0.4.12

### ISSUE THREAD

**Issue by franzhollerer** [OpenSC/libp11#441]
Do you have a date for which the next upcoming release is planned? The last one is dated Oct 11, 2020 and it seems that releases where done more frequently in the past.

The reason why I ask is that I see SEGFAULTS on exit, and with pkcs11_store_certificate(). The problems seem to be related to
- https://github.com/OpenSC/libp11/issues/411
- https://github.com/OpenSC/libp11/pull/369

Both problems seem to be fixed in the meantime. At least, they do not occur with the current code from the master branch.
But I hesitate to deploy code which is not officially released.

**Comment by ffontaine** [comment]
A new release would be great to also fix build failure with libressl thanks to 4968cfc64dbaa39bb479a24d9578d75099e2f337 and 8cba1dfe22f3b3a3c64df64b227a7bf71da32604 (which doesn't apply cleanly on top of 0.4.11).

**Comment by gilweis** [comment]
+1

**Comment by mtrojnar** [comment]
Released.
