### ISSUE TITLE
Comment about purpose of the library is unclear

### ISSUE THREAD

**Issue by franzhollerer** [OpenSC/libp11#442]
I found the following comment at the beginning of the libp11.h header file:

```
/*
 * The purpose of this library is to provide a simple PKCS11
 * interface to OpenSSL application that wish to use a previously
 * initialized card (as opposed to initializing it, etc).
 *
 * I am therefore making some simplifying assumptions:
 *
 *  -	no support for any operations that alter the card,
 *  	i.e. readonly-login
 */
```
It is unclear to me what this comment exactly means, our if it is just outdated. Obviously there are functions like PKCS11_init_token(), PKCS11_store_private_key(), PKCS11_store_certificate() and others which alter the card. Can you please clarify what is meant.

**Comment by mtrojnar** [comment]
@franzhollerer I agree.  Please submit a pull request.
