### ISSUE TITLE
Should `store_key` and `get_private_key` be able to round-trip and have the same data?

### ISSUE THREAD

**Issue by myerspliers** [OpenSC/libp11#443]
Question:
If I have a private key generated externally by OpenSSL (RSA, 4096 bit), and I add that key to a security token (SoftHSM2 for now) using `PKCS11_store_private_key` and later I call `PKCS11_get_private_key` to extract the private key from the token, can I expect the  extracted EVP_PKEY to contain the same data that the original key had? 
It seems like it should have the same data, but if I dump the original key and the extracted key to PEM files, they are not the same, and the extracted key is not recognized as a valid key by OpenSSL.

Current environment:
HSM token: SoftHSMv2 (2.6.1)
[libp11-0.4.11](https://github.com/OpenSC/libp11/releases/tag/libp11-0.4.11)
Openssl 1.1.1k

**Comment by mtrojnar** [comment]
> I call `PKCS11_get_private_key` to extract the private key from the token

`PKCS11_get_private_key` returns a EVP_PKEY object for the private key.  It does **not** extract the key itself.
