### ISSUE TITLE
Current master fails to properly clean up - crashes

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#448]
MacOS 12.3.1, Xcode-13.3.1, OpenSSL-3.0.2.

Here's what the stack looks like:
![Screen Shot 2022-04-27 at 17 08 22 ](https://user-images.githubusercontent.com/5923577/165631392-85c61600-9cdf-49af-957e-9b4658e9bddc.png)

It happens at the very end of the program execution.
![Screen Shot 2022-04-27 at 17 09 14 ](https://user-images.githubusercontent.com/5923577/165631494-8a923ece-e81d-48d0-9324-fedd6ad014d6.png)

**Comment by mtrojnar** [comment]
It this issue fixed now?

**Comment by mouse07410** [comment]
Interesting - now it appears fixed, I don't observe this problem anymore. Can't tell which commit took care of it.

Thanks!
