### ISSUE TITLE
libp11 mistreats public keys, and doesn't allow access to them without login PIN

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#45]
`PKCS11_enumerate_keys()` returns anything only if private keys are available to it *at the time of call*. This breaks the use case when one wants to retrieve the public key from the token and perform "verify" or "encrypt" without having to unlock the token by entering the PIN.

There are work-arounds for this, but the correct solution should be either enumerating all the keys instead of just private keys, or better yet - adding `PKCS11_enumerate_pubkeys()` function.

It also does not allow direct access to the public keys from OpenSSL (using engine_pkcs11), currently forcing the user to extract the public key first using other tools (like `pkcs11-tool` or `pkcs15-tool` from OpenSC) and then run OpenSSL command using the extracted copy of the key rather than the key on the token.

**Comment by mtrojnar** [comment]
I have reviewed the code.  Internally, `PKCS11_enumerate_keys()` also enumerates public keys, but there seems to be no documented way to access them (the public API only returns the number of enumerated private keys, and not the total number of enumerated keys).  Consequently, it should be safe to move enumerating public keys into a separate function without breaking the existing API.  Please correct me if I'm wrong about it.

@mouse07410 I need a few days to implement this feature.

**Comment by dengert** [comment]
p11_rsa.c has:
 64                 for(ki = token->nprkeys; ki < token->nkeys; ki++) {
 65                         PKCS11_KEY* pubkey = token->keys + ki;
 66 
 67                         if(key_getattr_bn(pubkey, CKA_MODULUS, &pubmod)) {
 68                                 continue;

So it is using the fact that the pub keys follow the private key in the array. 
And this also shows how to get access to the pubkeys.

**Comment by mtrojnar** [comment]
@dengert I'm fully aware that the current representation is used **internally**.  My comments were about the **external** API only, as I've redesigned the internal data structures for private/public keys.  There will be two separate lists of keys instead of one combined list.  I'm sure you will like the code.

**Comment by mtrojnar** [comment]
@mouse07410 Please try https://github.com/OpenSC/libp11/tree/PKCS11_enumerate_public_keys

**Comment by mouse07410** [comment]
> mouse07410 Please try https://github.com/OpenSC/libp11/tree/PKCS11_enumerate_public_keys

It still has problems:
```
pkcs11-ecdsa-demo2 stamp-h1
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
read EC key
openssl dgst -engine pkcs11 -keyform engine -sha384 -sign "pkcs11:object=SIGN%20key;object-type=private" -out /tmp/stamp-h1.sig stamp-h1
engine "pkcs11" set.
PKCS#11 token PIN:
Signature for stamp-h1 is stored in /tmp/stamp-h1.sig

pkcs11-tool -r -y pubkey -d 02 -o /tmp/derive.77557.02
Using slot 1 with a present token (0x1)
openssl dgst -verify /tmp/derive.77557.02 -keyform DER -sha384 -signature /tmp/stamp-h1.sig < stamp-h1
Verified OK

openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:object=SIGN%20pubkey;object-type=public" -signature /tmp/stamp-h1.sig stamp-h1
engine "pkcs11" set.
Out of memory
140735231131728:error:10098043:elliptic curve routines:o2i_ECPublicKey:passed a null parameter:ec_asn1.c:1271:
```

I think it would be best if you could merge my patch (as it addresses all of the above problems), and use it as a base for your re-write.

> I have reviewed the code. Internally, PKCS11_enumerate_keys() also enumerates public
> keys, but there seems to be no documented way to access them (the public API only returns
> the number of enumerated private keys, and not the total number of enumerated keys).

If that was the only problem, then the fix would've been quite trivial:
```
@@ -63,10 +65,30 @@ PKCS11_enumerate_keys(PKCS11_TOKEN * token, PKCS11_KEY ** keyp, unsigned int *co
                }
        }
        *keyp = priv->keys;
-       *countp = priv->nprkeys;
+       *countp = priv->nkeys;
        return 0;
 }
```
Unfortunately, it isn't nearly enough. It is a part of my patch. :-)

> Consequently, it should be safe to move enumerating public keys into
> PKCS11_enumerate_pubkeys() without breaking the existing public API. 

Absolutely. That's what I've done. ;-)

**Comment by mtrojnar** [comment]
Are you sure you have tested it against PKCS11_enumerate_public_keys branch?  The pkcs11_token_private structure no longer have nprkeys and nkeys members.
https://github.com/OpenSC/libp11/blob/PKCS11_enumerate_public_keys/src/libp11-int.h#L83

**Comment by mtrojnar** [comment]
I also fail to grasp the relationship between the `140735231131728:error:10098043:elliptic curve routines:o2i_ECPublicKey:passed a null parameter:ec_asn1.c:1271:` error and the topic of this issue ("PKCS11_enumerate_keys() returns only private keys").

**Comment by mouse07410** [comment]
> Are you sure you have tested it against PKCS11_enumerate_public_keys branch?

I am 100% positive. And that's the only branch that would be able to link with `engine_pkcs11` that wants to call `PKCS11_enumerate_public_keys()`.

> The pkcs11_token_private structure no longer has nprkeys and nkeys members.

So? I (or rather, engine_pkcs11) am **not** trying to access private structures of libp11.

> I also fail to grasp the relationship between the `.......ec_asn1.c:1271: error` and the topic of
> this issue ("PKCS11_enumerate_keys() returns only private keys").

My fault. The original topic of this issue was too narrow, as `PKCS11_enumerate_keys()` not telling its caller that it actually did enumerate all the keys was only a minor part of the overall problem. But that was the first indication of a problem that I stumbled upon - which is why I named this issue so. I've renamed it now.

Before providing a long explanation I must start that I care for libp11 at all only because engine_pkcs11 depends on it. That's my only intersection with it.

So here's the long story.

1. My goals are to (a) be able to access public keys without having to provide a PIN, and (b) be able to access private **and public** keys directly from the token rather than having to extract the public key first (e.g., using OpenSC CLI tools). More so, I wanted these capabilities to work for both RSA and ECC tokens. Examples of the commands I want to run successfully are:
```
openssl dgst -engine pkcs11 -keyform engine -sha384 -sign "pkcs11:object=SIGN%20key;object-type=private" -out filename.ext.sig filename.ext
```
and
```
openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:object=SIGN%20pubkey;object-type=public" -signature filename.ext.sig filename.ext
```

2. As you must be aware, the above did not work with the stock engine_pkcs11 and the stock libp11. Tracking this problem through engine_pkcs11.c, I got to a call to `PKCS11_enumerate_keys()` that threw me into libp11.

3. In the process, I found that libp11 does not implement public keys retrieval properly, and funnels all the access through the private keys retrieval. That might work, but required PIN-based access. So, using the private key access code as a model, I've added the necessary body to the routines that provided public keys for both RSA and ECC.

4. As a result, I've modified `engine_pkcs11` to properly use private and public keys (without having to ask for PIN to access the latter), and `libp11` as it was not possible to solve this problem by engine_pkcs11 changes alone (since unfortunately depends on libp11 and uses its services).

You asked for developing test mechanisms. Sorry, that's not my cup of tea. I must leave it to somebody more proficient in QA. All I can say is - here are the commands that succeed if key enumeration works properly, and fail otherwise. Unfortunately, they also depend on other capabilities, like correct formatting of the retrieved ECC public keys.

**Comment by mtrojnar** [comment]
Thank you.  I still think it would be convenient to open three separate issues:
1. Not returning public keys (no PKCS11_enumerate_public_keys()).
2. Missing pkcs11_get_ec_public() implementation.
3. Requiring PIN for accessing public keys.

I'm reviewing https://github.com/mouse07410/libp11/commit/9fbace48487bd38386e5a8f8e793336893b12082 and somehow I cannot find which lines address (3) even though it is explicitly listed in the commit description.
@mouse07410 Can you help me?

**Comment by mtrojnar** [comment]
@mouse07410 With regards to pkcs11_get_ec_public: I ended up half-manually comparing your copy-pasted code against the original one to identify meaningful changes.  Here is the result:
```diff
--- /tmp/1	2015-12-31 08:17:05.365506679 +0100
+++ /tmp/2	2015-12-31 08:30:33.376766288 +0100
@@ -1,4 +1,4 @@
-static int pkcs11_get_ec_private(PKCS11_KEY * key, EVP_PKEY * pk)
+static int pkcs11_get_ec_public(PKCS11_KEY * key, EVP_PKEY * pk)
 {
     CK_BBOOL sensitive, extractable;
     EC_KEY * ec = NULL;
@@ -11,13 +11,10 @@
     PKCS11_KEY * pubkey;
     ASN1_OCTET_STRING *os=NULL;
 
-    if (key->isPrivate) {  /* Are we being called for the prive or pub key */
-        prkey = key;
-        pubkey = PKCS11_find_key_from_key(key);
-    } else {
-        pubkey = key;
-        prkey = PKCS11_find_key_from_key(key);
-    }
+    if (key->isPrivate)
+        return pkcs11_get_ec_private(key, pk);
+
+    pubkey = key;
 
     if (pk->type == EVP_PKEY_EC) {
         ec = EVP_PKEY_get1_EC_KEY(pk);
@@ -27,9 +24,8 @@
     }
     /* After above ec has ref count incremented. */
 
-    if (prkey) {
-        if (key_getattr(prkey, CKA_SENSITIVE, &sensitive, sizeof(sensitive))
-                || key_getattr(prkey, CKA_EXTRACTABLE, &extractable, sizeof(extractable))) {
+        if (key_getattr(pubkey, CKA_SENSITIVE, &sensitive, sizeof(sensitive))
+                || key_getattr(pubkey, CKA_EXTRACTABLE, &extractable, sizeof(extractable))) {
             EC_KEY_free(ec);
             return -1;
         }
@@ -40,25 +36,23 @@
          * need this if the pkcs11 or card can figure this out.
          */
 
-        if (key_getattr_var(prkey, CKA_EC_PARAMS, NULL, &ec_paramslen) == CKR_OK &&
+        if (key_getattr_var(pubkey, CKA_EC_PARAMS, NULL, &ec_paramslen) == CKR_OK &&
                 ec_paramslen > 0) {
             ec_params = OPENSSL_malloc(ec_paramslen);
             if (ec_params) {
-                ckrv = key_getattr_var(prkey, CKA_EC_PARAMS, ec_params, &ec_paramslen);
+                ckrv = key_getattr_var(pubkey, CKA_EC_PARAMS, ec_params, &ec_paramslen);
                 if (ckrv == CKR_OK) {
                     const unsigned char * a = ec_params;
                     /* convert to OpenSSL parmas */
                     d2i_ECParameters(&ec, &a, ec_paramslen);
                 }
-            }
         }
     }
 
     /* Now get the ec_point */
 
-    if (pubkey) {
-        if (key_getattr_var(pubkey, CKA_EC_POINT, NULL, &ec_pointlen) == CKR_OK &&
-                    ec_pointlen > 0) {
+    ckrv = key_getattr_var(pubkey, CKA_EC_POINT, NULL, &ec_pointlen);
+        if (ckrv == CKR_OK && ec_pointlen > 0) {
             ec_point = OPENSSL_malloc(ec_pointlen);
             if (ec_point) {
                 ckrv = key_getattr_var(pubkey, CKA_EC_POINT, ec_point, &ec_pointlen);
```

**Comment by mtrojnar** [comment]
I guess the main idea is that while the private key also needs the corresponding public key, the public key doesn't really need the corresponding private key, so the code should be:
```c
    if (key->isPrivate) {  /* Are we being called for the prive or pub key */
        prkey = key;
        pubkey = PKCS11_find_key_from_key(key);
    } else {
        pubkey = key;
        prkey = NULL;
    }
```
The other changes boil down to extracting parameters from the public key instead of the private key, which makes sense anyway.

**Comment by mtrojnar** [comment]
My solution is https://github.com/OpenSC/libp11/commit/1fc85b718defae296d278225e2f26d6c91e5aa4c.  It also shortens and simplifies the code.

@mouse07410 Can you confirm that this issue can now be closed?

**Comment by mouse07410** [comment]
> My solution is 1fc85b7. It also shortens and simplifies the code.

Yes it does. :-)

> @mouse07410 Can you confirm that this issue can now be closed?

Yes I confirm: it appears to work with all of my test-cases. Thank you! I think it's time to merge your `PKCS11_enumerate_public_keys` branch with the master. And this issue can be closed, thanks!
Screenshots:
```
$ git branch
* PKCS11_enumerate_public_keys
  master
$ pkcs11-ecdsa-demo2 NEWS
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
read EC key
openssl dgst -engine pkcs11 -keyform engine -sha384 -sign "pkcs11:object=SIGN%20key;object-type=private" -out /tmp/NEWS.sig NEWS
engine "pkcs11" set.
PKCS#11 token PIN:
Signature for NEWS is stored in /tmp/NEWS.sig

pkcs11-tool -r -y pubkey -d 02 -o /tmp/derive.84099.02
Using slot 1 with a present token (0x1)
openssl dgst -verify /tmp/derive.84099.02 -keyform DER -sha384 -signature /tmp/NEWS.sig NEWS
Verified OK

openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:object=SIGN%20pubkey;object-type=public" -signature /tmp/NEWS.sig NEWS
engine "pkcs11" set.
Verified OK

$ pkcs11-ec-derive-demo
Extracting public key from the token...
pkcs15-tool --read-public-key 03 -o /tmp/derive.84140.token.pub.pem
Using reader with a card: Yubico Yubikey 4 OTP+U2F+CCID
read EC key

Generating ephemeral ECC key pair on secp384r1...
openssl ecparam -name secp384r1 -genkey -out /tmp/derive.84140.priv.pem
openssl ec -in /tmp/derive.84140.priv.pem -pubout -outform DER -out /tmp/derive.84140.pub.der
read EC key
writing EC key

Generating random 250 bytes of Base64-encoded data...
openssl rand -base64 -out /tmp/derive.84140.text 250

Deriving shared key from ephemeral private and token public keys...
openssl pkeyutl -derive -inkey /tmp/derive.84140.priv.pem -peerkey /tmp/derive.84140.token.pub.pem -out /tmp/derive.84140.shared1

Encrypting data file with derived symmetric key in /tmp/derive.84140.shared1 and AES-CFB...
openssl enc -aes-256-cfb -e -a -kfile /tmp/derive.84140.shared1 -in /tmp/derive.84140.text -out /tmp/derive.84140.text.enc

Deriving shared symmetric key on the token, using ephemeral public key...
pkcs11-tool --slot 1 --module /Library/OpenSC/lib/opensc-pkcs11.so -l --derive -m ECDH1-COFACTOR-DERIVE -d 03 -i /tmp/derive.84140.pub.der -o /tmp/derive.84140.shared2
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using derive algorithm 0x00001051 ECDH1-COFACTOR-DERIVE

Decrypting data file with derived symmetric key in /tmp/derive.84140.shared2 and AES-CFB...
openssl enc -aes-256-cfb -d -a -kfile /tmp/derive.84140.shared2 -in /tmp/derive.84140.text.enc -out /tmp/derive.84140.text.dec

Derived keys matched.
Decrypted file matches the original plaintext.

$ pkcs11-rsa-pss-sign-demo NEWS
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:object=SIGN%20key;object-type=private;pin-value=123456" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out NEWS.sig NEWS
engine "pkcs11" set.
PKCS#11 token PIN:
Signature for NEWS is stored in NEWS.sig

pkcs11-tool -r -y pubkey -d 02 -o /tmp/derive.84401.pubkey.02
Using slot 1 with a present token (0x1)
openssl dgst -verify /tmp/derive.84401.pubkey.02 -keyform DER -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature NEWS.sig < NEWS
Verified OK

openssl dgst -engine pkcs11 -keyform engine -sha384 -verify id_02 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature NEWS.sig  NEWS
engine "pkcs11" set.
Verified OK

$ pkcs11-rsa-encr-demo NEWS
Found NEWS
openssl enc -a -e -salt -in NEWS -out NEWS.enc -kfile /tmp/derive.84515.pass.plain
pkcs15-tool --read-certificate 03 -o /tmp/derive.84515.enc.cert
Using reader with a card: Yubico Yubikey NEO OTP+U2F+CCID
openssl rsautl -encrypt -in /tmp/derive.84515.pass.plain -out /tmp/derive.84515.pass.enc 	-inkey /tmp/derive.84515.enc.cert -keyform PEM -certin
pkcs11-tool --slot 1 --module /Library/OpenSC/lib/opensc-pkcs11.so --decrypt -m RSA-PKCS --id 03 -i /tmp/derive.84515.pass.enc -o /tmp/derive.84515.pass.dec
Logging in to "PIV_II (PIV Card Holder pin)".
Please enter User PIN:
Using decrypt algorithm RSA-PKCS
openssl enc -a -d -salt -in NEWS.enc -out NEWS.dec -kfile /tmp/derive.84515.pass.dec
Original and decrypted keys  match
Original and decrypted files match
$
```

**Comment by mouse07410** [comment]
@mtrojnar when do you think you'd be able to merge this into the master? So we could test engine_pkcs11 PR against it?
