### ISSUE TITLE
Integrating SoftHSM with OpenSSL using opensc pkcs11 test failed

### ISSUE THREAD

**Issue by bh4rtp** [OpenSC/libp11#451]
I do the test using this tutorial:
[Integrating SoftHSM with OpenSSL using Opensc PKCS11](https://dearzubi.medium.com/integrating-softhsm-with-openssl-using-opensc-pkcs11-184c3f92e397)
```
[allen@localhost ~]$ openssl engine pkcs11 -t
(pkcs11) pkcs11 engine
     [ available ]
```
All the steps are tested successfully except the last step 8. Here is the output message from step 8.
```
[allen@localhost ~]$ openssl req -x509 -days 365 -new -nodes -out cert.crt -engine  pkcs11 -keyform engine -key 1001
engine "pkcs11" set.
Unable to load module (null)
Unable to load module (null)
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
140583702873920:error:81065401:libp11:pkcs11_CTX_load:Unable to load PKCS#11 module:p11_load.c:79:
140583702873920:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:78:
unable to load Private Key
```

**Comment by bh4rtp** [comment]
I installed the environments as following:
1) install openssl-1.1.1k in /usr/local/ssl
2) install softhsm2-2.6.1
3) install libp11-0.4.11
4) cp pkcs11.so from libp11-0.4.11 to /usr/loca/ssl/lib/engines-1.1/
```
[allen@localhost ~]$ ls /usr/local/ssl/lib/engines-1.1/
capi.so  padlock.so  pkcs11.so
```

**Comment by mtrojnar** [comment]
'Unable to load PKCS#11 module' suggests that libp11 could not guess which PKCS#11 module you want it to use.  Is it SoftHSM?

**Comment by mtrojnar** [comment]
Apparently, the tutorial assumes that a preinstalled p11-kit package will automatically detect a PKCS#11 module for you.  Ask the author to fix the tutorial, so that it also works without p11-kit.

**Comment by dwmw2** [comment]
Nah, fix your distro so that things are installed properly.

**Comment by mtrojnar** [comment]
@dwmw2 Yeah, an alternative approach is to assume that everyone uses a popular modern GNU/Linux or *BSD distro with all software installed from binary packages.  If you read https://github.com/OpenSC/libp11/issues/451#issuecomment-1129691848 above, this is not the case for @bh4rtp.

**Comment by dwmw2** [comment]
I appreciated I'm inferring a lot from a prompt that happens to look like bash, but I'd guest @bh4rtp *was* using a relatively modern distro and could have just installed the binary packages instead of building stuff for themselves.

And it doesn't *require* binary packages either; it should work just fine when installing from source. SoftHSM itself should automatically install its own p11-kit module file as part of its 'make install', libp11 should use `p11-kit-proxy.so` by default if it's available, and everything ought to Just Work even from source.

**Comment by bh4rtp** [comment]
I solved this issue. An openssl.cnf should be prepared.
