### ISSUE TITLE
Failed to initialize PKCS #11 security token library.

### ISSUE THREAD

**Issue by xmwa** [OpenSC/libp11#452]
I’m running 1.25.9 version of veracrypt on macOS 12.2.1,  for a long time I’m experiencing the problem of unable to load the libp11 library with the following error:
dlopen(/opt/homebrew/Cellar/libp11/0.4.11/lib/libp11.a, 0x0006): tried: '/opt/homebrew/Cellar/libp11/0.4.11/lib/libp11.a' (not a mach-o file), '/usr/lib/libp11.a' (no such file)
Failed to initialize PKCS #11 security token library.
I’ve installed the libp11 library using brew and installed on the specific path listed above, but dlopen recognized it not as a mach-o file, any ideas on what I need to do to deal with the problem? Thank you.

**Comment by mtrojnar** [comment]
Are you trying to dynamically (with `dlopen()`) load a static library (`libp11.a`)?  `libp11.a` is quite obviously an `ar` archive, thus not a Mach-O file.

Also, libp11 is **not** a PKCS#11 module (I guess this is what veracrypt means by "token library").  You need something like OpenSC: https://github.com/OpenSC/OpenSC/
