### ISSUE TITLE
Missing signature for 0.4.12

### ISSUE THREAD

**Issue by mtorromeo** [OpenSC/libp11#454]
Hi,
the release assets for version 0.4.12 are missing the usual `.asc` gpg signatures.

Thanks!

**Comment by panlinux** [comment]
Indeed, a detached signature is expected by the debian/ubuntu packaging:

```
$ uscan 
uscan: Newest version of libp11 on remote site is 0.4.12, local version is 0.4.11
uscan:  => Newer package available from:
        => https://github.com/OpenSC/libp11/releases/download/libp11-0.4.12/libp11-0.4.12.tar.gz
uscan warn: In directory ., downloading
  https://github.com/OpenSC/libp11/releases/download/libp11-0.4.12/libp11-0.4.12.tar.gz.asc failed: 404 Not Found
uscan die: FAIL Checking OpenPGP signature (no signature file downloaded).
```

**Comment by mtorromeo** [comment]
@mtrojnar can you take a look at this please?

**Comment by mtrojnar** [comment]
I uploaded the missing signature (only for the distribution tarball, and not for the repository snapshots automatically added by GitHub).  I'm sorry for the delay.
