### ISSUE TITLE
segfault when using together with mysqlclient

### ISSUE THREAD

**Issue by Eric8658905** [OpenSC/libp11#461]
Hi Team,
Greetings from Brazil.

I'm merging two softwares I wrote, one that uses libp11 and the other that uses mysql.
The issue is that it started to segfault. see below.

from strace...
![image](https://user-images.githubusercontent.com/110784770/183308749-a1b48cf7-68d3-4825-94a8-72cff356e963.png)

from dmesg... (libaetpkss is my card driver)
![image](https://user-images.githubusercontent.com/110784770/183308791-9d5371e9-efa4-440c-9346-541537ea4bde.png)

some from gdb...
![image](https://user-images.githubusercontent.com/110784770/183308846-f8c01577-4071-4114-92f7-eed3fe344001.png)

The code to reproduce is the following.

`#include <stdio.h>
#include <libp11.h>
#include <mysql/mysql.h>

int main(int argc, char *argv[])
{
     PKCS11_CTX *ctx=NULL;
     int rc = 0;

     ctx = PKCS11_CTX_new();

     rc = PKCS11_CTX_load(ctx, "/usr/lib/libaetpkss.so");
     sleep(10);

     MYSQL *conn;
     conn = mysql_init(NULL);
}`

i'm compiling with ...
`gcc  -g -Wall -O2 -o listkeys listkeys.c /usr/local/lib/libp11.a -lcrypto -ldl -lpthread -lmysqlclient`
or -llibp11

The interesting part is, just the presence of the "mysql_init" causes it to segfault, it doesn't need to get called.... as you can see I have it at the end on the above example.
I have tried a few versions of libp11/mysqlclient including the master, shared/static with the same results. 

If I use an other card driver that doesn't happen, i.e. not segfault, but I need to use this one.
If I remove the mysql part, all my libp11 software and all libp11 samples works flawless.
pkcs11-tool and p11-kit all works well with the card driver, the issue appears only when combining mysqlclient.

any hope ?

Thank you

**Comment by mtrojnar** [comment]
Why exactly do you think that a crash in your `/usr/lib/libaetpkss.so` module from  is caused by libp11?  Their code crashes every early (while loading the module), so there is no apparent opportunity for libp11 to be a culprit.

**Comment by dengert** [comment]
What version of OS?
Where did you get libaetpkss.so? 

Sounds like an issue between libaetpkss.so and mysqlclient. They may have duplicate routines 

Try: `gdb --args listkeys`
type `run` and when it segfaults, type `where` 

Google for: libaetpkss.so
You will see many problems with this module.

**Comment by Eric8658905** [comment]
hi,
i don't think anything, just asking for help. probably there is a bug in
card driver that show up at these conditions.
maybe a way to get around ?
i asked it here first because its related to smartcard.
not saying its a libp11 problem or something.

**Comment by mtrojnar** [comment]
Please contact the technical support of your PKCS#11 driver vendor: https://www.aeteurope.com/contact/

**Comment by Eric8658905** [comment]
Thank you for the tip, they were friendly and sent me an updated module. The one I had were extracted from public versions of their token manager, pretty old. 3.5 vs 3.8

It's working now. I have an other issue and will open an other thread.

@dengert thanx for the "warm dev welcome". i'm a bit rusty on gdb, will catch up. cheers.

thanx team.
