### ISSUE TITLE
Missing error handling in pkcs11_object_from_template

### ISSUE THREAD

**Issue by ulrichb** [OpenSC/libp11#464]
I'm talking about the following two lines:

https://github.com/OpenSC/libp11/blob/bb8b8389f39e61ee6508db86c1341495c06f9c9a/src/p11_key.c#L161-L162

Here a potential `CK_INVALID_HANDLE` from [`pkcs11_handle_from_template()`](https://github.com/OpenSC/libp11/blob/bb8b8389f39e61ee6508db86c1341495c06f9c9a/src/p11_key.c#L41) is not handled.

=> We enter the following `pkcs11_object_from_handle()` with `CK_INVALID_HANDLE`.

**Comment by mtrojnar** [comment]
> Hi, can I work on this as my first contribution to open source?

Sure.  Please submit a PR.
