### ISSUE TITLE
Documentations && Windows needs

### ISSUE THREAD

**Issue by GomezJulie** [OpenSC/libp11#476]
Hi,
First, thanks for your work.

**What is my environment and needs:**
I work on Windows 10, 64 bits.
I add package with pacman linux command on my mingw32 terminal (msys64 version of [2022/09/04](https://github.com/msys2/msys2-installer/releases/tag/2022-09-04)).
I work on a Qt Creator editor and I have a .pro file to configure my Qt project.
I want to develop a C++ module for my application which use libp11 to get the Yubikey bin number and decrypt file.
Why I use a mingw32 terminal and not the mingw64, because, for the moment, the project is always in develop in QT 4.8.

**What I do:**
I read the [README](https://github.com/OpenSC/libp11/blob/master/README.md) file and follow the installation step of the [INSTALL](https://github.com/OpenSC/libp11/blob/master/INSTALL.md) file (first I follow the [MinGW / MSYS](https://github.com/OpenSC/libp11/blob/master/INSTALL.md#mingw--msys) chapter, then I follow the [MSYS2](https://github.com/OpenSC/libp11/blob/master/INSTALL.md#msys2) chapter.)
I do much more, but I don't remember every thing and I go in many wrong ways.

**My problems and questions**
Considering this previous information:
- I have many difficulties to install the necessary environment before using libp11. Did you update the process recently ?
- I find that there is not enough documentation (Doxygen or wiki) to use function when we work on Windows environment. Can you help me with it ?

**For example :**
It seems the function PKCS11_CTX_load(...) can take in second argument `/usr/lib/opensc-pkcs11.so` like I can see [on cpp.hotexamples.com](https://cpp.hotexamples.com/fr/examples/-/-/PKCS11_CTX_load/cpp-pkcs11_ctx_load-function-examples.html).
But in C++ .so are not compatible. So I try with a pkcs11.dll or libpkcs11.dll finding in `C:\msys64\mingw32\lib\engines-1_1`.
It doesn't work well, the function PKCS11_CTX_load(...) always return `-1`.

Thank you in advance for your help.

**Comment by jmdesp** [comment]
Hi, the documentation is indeed severly lacking in many ways, however it's not very clear what you've suceeded until now and what you're try to do precisely, Julie.

For what's it's worth, note however that I found in the following blog entry a *lot* of information that is either missing or not clear at all here on the official site. It may be that it will help you too :
https://colinpaice.blog/2021/03/08/using-openssl-with-an-hsm-keystore-and-opensc-pkcs11-engines/

**Comment by mtrojnar** [comment]
The exact steps to reproduce this issue and the exact error messages returned would help.  Please read https://www.chiark.greenend.org.uk/~sgtatham/bugs.html and update the description of this issue.
