### ISSUE TITLE
Issue connecting to libffi7

### ISSUE THREAD

**Issue by corygoates** [OpenSC/libp11#490]
When trying to use Paraview through the Python terminal interface, I get the following error:

```
ImportError: /lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```

I've reinstalled libffi7 multiple times. I'm running Linux Mint 20.2 Cinnamon 64-bit.

**Comment by Jakuje** [comment]
That sounds like an issue of the https://github.com/p11-glue/p11-kit/ and not libp11. This is different project.
