### ISSUE TITLE
how do I find the compatibility of libp11 version and openssl version

### ISSUE THREAD

**Issue by fengjiang-v** [OpenSC/libp11#491]
might be a noob question but how do I know which openssl version is compatible to different libp11 release. it's not clearly spelled out in the release note

**Comment by Jakuje** [comment]
the libp11 is compatible with OpenSSL 0.9.8 and newer according to the configure check:

https://github.com/OpenSC/libp11/blob/master/configure.ac#L205

But it is worth noting that the engines API is deprecated in favor of the provides API in OpenSSL 3.0. So the libp11 will work there only if the deprecated API is used and enabled in the OpenSSL build you are using.

For OpenSSL 3.0, I can recommend https://github.com/latchset/pkcs11-provider
