### ISSUE TITLE
Ci fails on continuous-integration/appveyor/pr 

### ISSUE THREAD

**Issue by bharsaklemukesh975** [OpenSC/libp11#493]
Error:

Build started
git clone -q https://github.com/OpenSC/libp11.git C:\projects\libp11
git fetch -q origin +refs/pull/492/merge:
git checkout -qf FETCH_HEAD
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

**Comment by mtrojnar** [comment]
@frankmorgner On 15 Sep 2022 you sent me an email confirmation that the legacy AppVeyor webhook is removed.  Apparently, it's still there.  Could you take a look?  Is it possible that someone else has reverted your change?
As I wrote before, I have insufficient privileges to configure https://github.com/OpenSC/libp11/settings/hooks by myself.

**Comment by frankmorgner** [comment]
I'm confused... in commit b4896cd5d7f39ec6a1f868f4283ae2432dc45ddf AppVeyor builds were explicitly disabled, that's why AppVeyor don't know how to build the project even (though it would have the authorization to do so, I think)

**Comment by mtrojnar** [comment]
@frankmorgner There are fundamentally two alternative ways of integrating GitHub with 3rd party services:
1. By placing a GitHub Actions yml configuration in the `.github/workflows/` directory of the repository.  These yml files are part of the repository data, and they can be changed with a commit.  See https://docs.github.com/en/actions/using-workflows for details.
2. By registering a webhook in the repository settings.  Note that you cannot change repository settings with a commit, as opposed to repository data.  See https://docs.github.com/en/webhooks-and-events/webhooks/about-webhooks for details.

https://github.com/OpenSC/libp11/commit/b4896cd5d7f39ec6a1f868f4283ae2432dc45ddf only removes the `appveyor.yml` AppVeyor configuration file placed in the root of the repository tree.  Coincidentally, both GitHub Actions and and AppVeyor use slightly similar yml as their configuration file format.  I guess this is what got you confused.  In fact, `appveyor.yml` is not placed in `.github/workflows/`, and it is completely oblivious to Google Actions.

I hope my explanation is better this time.

**Comment by frankmorgner** [comment]
For some reason, I thought that your complaint was AppVeyor not working *correctly*, but you actually wanted to be working *not at all*. I reviewed everything and hopefully got it right this time:
- libp11 webhook for AppVeyor is removed
- AppVeyor Github App is installed (only possible on organizationel level), but limited to https://github.com/OpenSC/OpenSC
- @mtrojnar added as *Admin* to libp11

**Comment by mtrojnar** [comment]
@frankmorgner Thank you very much for your help.  It works fine now.
