### ISSUE TITLE
PIN requested when it is not required

### ISSUE THREAD

**Issue by Nowa-Ammerlaan** [OpenSC/libp11#506]
When using gnupg to sign a bunch of files the PIN of my Nitrokey is asked once, and then it will remain unlocked for some time (I think 10 minutes or something). This is convenient when signing things in bulk.

When using pkcs11 URI's for signing via e.g. `sbsign` or the kernels `scripts/sign-file` the PIN is asked every time, even though after the first time the card is already unlocked. Consecutive requests for the PIN can be passed by simply pressing enter, so even though the PIN is requested it is not required. This is super inconvenient, and makes signing files in bulk a pain.

I've looked through some manuals for a config option that will maybe make this do what I want but I couldn't find anything. Is it somehow possible to prevent opensc/libp11 from asking for the PIN if the card is already in an unlocked state?

**Comment by olszomal** [comment]
To avoid repeated PIN prompts when using PKCS#11 URIs for signing, you can include the pin-value parameter directly in the URI. This will allow the PIN to be automatically supplied each time, as long as the card remains unlocked, simplifying bulk signing.

The URI would look something like this:
```
pkcs11:token=YourTokenName;object=YourKeyObject;pin-value=YourPin
```
This approach prevents additional prompts, making bulk signing more convenient. However, please be aware that including the PIN in the URI may have security implications if the command history or environment is not secured.

I recommend using [osslsigncode ](https://github.com/mtrojnar/osslsigncode)for file signing. It integrates seamlessly with PKCS#11 tokens and supports passing additional control commands (engine controls), offering greater flexibility in configuring the signing process.

I suggest closing this issue.

**Comment by Nowa-Ammerlaan** [comment]
> To avoid repeated PIN prompts when using PKCS#11 URIs for signing, you can include the pin-value parameter directly in the URI. This will allow the PIN to be automatically supplied each time, as long as the card remains unlocked, simplifying bulk signing.

That's not the point, I know this is possible. The point is that libp11 is requesting a PIN even when the card is still in the unlocked state and does not require the PIN.

**Comment by mtrojnar** [comment]
Are you sure the PIN is not required for private key operations?
Include your `pkcs11-spy` logs with this issue.

**Comment by Nowa-Ammerlaan** [comment]
> Are you sure the PIN is not required for private key operations?
> Include your `pkcs11-spy` logs with this issue.

I am sure it is not required because entering an incorrect or empty PIN results in a valid signature within this 10 minute window. If the PIN would be required, it would have to be correct.

I'll get the log later when I have time again.

**Comment by dengert** [comment]
Spy would show the C_GetToken_Info  flags:  CKF_LOGIN_REQUIRED, CKF_USER_PIN_INITIALIZED, CKF_PROTECTED_AUTHENTICATION_PATH. and if libp11 is making a good choice.

Did you set the  libp11 FORCE_LOGIN?

**Comment by dengert** [comment]
You also said: the "PIN is asked every time"  Does the private key have the CKA_ALWAYS_AUTHENTICATE? Thsi would force the user to enter the pin every time.

**Comment by mtrojnar** [comment]
I reopened this issue because it appears we are using the cached PIN for `CKA_ALWAYS_AUTHENTICATE` instead of the newly entered PIN. This undermines the intended purpose of `CKA_ALWAYS_AUTHENTICATE`, turning it into a security problem rather than a mere inconvenience.

**Comment by mtrojnar** [comment]
On second thought, `sbsign` only loads the engine to sign an UEFI executable once.  Consequently, each signing is performed with a separate instance of our PKCS#11 engine, so it cannot be our libp11 caching the PIN.  Does my reasoning make sense?

Is it possible that the Nitrokey software uses some kind of background service that caches the PIN, while still requesting a PIN with `CKF_LOGIN_REQUIRED` or `CKA_ALWAYS_AUTHENTICATE` and ignoring the returned value?  I guess we would know from `pkcs11-spy` logs.

**Comment by Nowa-Ammerlaan** [comment]
> Consecutive requests for the PIN can be passed by simply pressing enter, so even though the PIN is requested it is not required. 

So this was some time ago, and I just tried again. But is seems something has changed in the meantime and I cannot reproduce my original problem. The PIN is still always requested, but I can no longer enter an incorrect or empty PIN for signing within the window that the token is unlocked. Instead I get "login failed" which makes more sense.

One could argue that there still is some problem in the form of the PIN being requested at all if the token is already unlocked. To make the problem a bit more clear, when using this Nitrokey to (gpg) sign git commits I have to unlock it once with the PIN and then it will stay unlocked for 10 minutes meaning I do not have to enter the PIN again when making consecutive commits within this window. If instead I am (openssl) signing kernel modules with the same Nitrokey, then I have to enter the PIN again and again.

> On second thought, `sbsign` only loads the engine to sign an UEFI executable once. Consequently, each signing is performed with a separate instance of our PKCS#11 engine, so it cannot be our libp11 caching the PIN. Does my reasoning make sense?

Yes, I'm no expert but I don't think this was about caching. I think it was about checking if the token is in the unlocked state or not, and only requesting the PIN if it is not. It is my understanding that the card itself is "unlocked" and therefore does not require the PIN to access regardless of what software is used to access it. I might be completely wrong here though.
 
> Is it possible that the Nitrokey software uses some kind of background service that caches the PIN, while still requesting a PIN with `CKF_LOGIN_REQUIRED` or `CKA_ALWAYS_AUTHENTICATE` and ignoring the returned value? I guess we would know from `pkcs11-spy` logs.

According to `p11tool` these flags are not set for these keys. I am going to need some help with `pkcs11-spy` though, it is not clear to me how I can use that through openssl/sbsign. I tried this `PKCS11SPY="/usr/lib64/engines-3/pkcs11.so" sbsign --engine /usr/lib64/pkcs11-spy.so` but the resulting error indicates that this is not the correct way.

**Comment by mtrojnar** [comment]
I guess there could be a PKCS#11 flag or attribute that Nitrokey uses to let PKCS#11 API clients, such as libp11, know that it's "unlocked" and it doesn't need a PIN.  Maybe this is something we could use.

**Comment by dengert** [comment]
This is how I used to run "openssl -> lib11engine -> OpenSC pkcs11 module", But changing the 0 to 1 in first line so it is "openssl -> lib11engine -> SPY -> OpenSC pkcs11 module" Spy can work with any pkcs11 module. 
```
105 # To be able to use pkcs11-spy.so for debugging
106 if [ 0 -eq 0 ] ; then
107         MODULE=$OPENSC_LIB/opensc-pkcs11.so
108 else
109         MODULE=$OPENSC_LIB/pkcs11-spy.so
110         PKCS11SPY=$OPENSC_LIB/opensc-pkcs11.so
111         export PKCS11SPY 
112         PKCS11SPY_OUTPUT=/tmp/pkcs11.spy.log
113         export PKCS11SPY_OUTPUT
114 fi
115 
116 # openssl.conf has prompt = no, no need for extra blank line at end...
117 cat >/tmp/genreq.openssl.input << EOT
118 engine dynamic -vvvv -pre SO_PATH:$OPENSC_ENGINE/engines/engine_pkcs11.so -pre ID:pkcs11 -pre NO_VCHECK:1 -pre LIST_ADD:1 -pre LOAD  -pre MODULE_PATH:$MODULE
119 req $SSLEAY_CONFIG -engine pkcs11 -keyform engine -sha256 -new -key slot_1-id_$ID -out cards/$1.myreq.$KEYID.pem  -text
120 EOT
```

**Comment by dengert** [comment]
PKCS11 3.0 (and older versions):

"The CKA_ALWAYS_AUTHENTICATE attribute can be used to force re-authentication (i.e. force the user to provide a PIN) for each use of a private key. “Use” in this case means a cryptographic operation such as sign or decrypt. This attribute may only be set to CK_TRUE when CKA_PRIVATE is also CK_TRUE. 

Re-authentication occurs by calling C_Login with userType set to CKU_CONTEXT_SPECIFIC"

Note pin maybe different, depending on device.

**Comment by mtrojnar** [comment]
Please reopen the issue when `pkcs11-spy` log is available.
