### ISSUE TITLE
keyid longer than MAX_VALUE_LEN

### ISSUE THREAD

**Issue by jorgehwang** [OpenSC/libp11#513]
I'm trying `google kmsp11` pkcs#11 module.  I noticed that `parse_pkcs11_uri()` fails because of long keyid. e.g. `projects/some_project/locations/some_location/keyRings/some_keyring/cryptoKeys/some_ck/cryptoKeyVersions/1`
It's working OK with `pkcs11:object=keyid` but, I'm trying to use full keyid.

When I change `MAX_VALUE_LEN` to 200, it looks working. but, I wonder if I'm missing something.

Thanks,

**Comment by dwmw2** [comment]
I don't think you're missing anything. AFAICT PKCS#11 doesn't actually specify a maximum size of CKA_LABEL, or CKA_ID or indeed any other attributes.

**Comment by jorgehwang** [comment]
Thank you for your comment, @dwmw2   Does that mean that "libpkcs + google cloud hsm" is not a usual usecase? Is it?

**Comment by dengert** [comment]
> MAX_VALUE_LEN is 200, so I guess it's not the value you used.

But  MAX_VALUE_LEN is only used one only place and divides by 2: https://github.com/OpenSC/libp11/blob/master/src/eng_back.c#L381
and divides by 2.

If there is no limit, it should be allocated. Or at least go with the 2600 limit and drop the divide by 2.

**Comment by mtrojnar** [comment]
Yeah, this code is really old.
