### ISSUE TITLE
Generate keys on the token

### ISSUE THREAD

**Issue by mtrojnar** [OpenSC/libp11#53]
libp11 currently generates keys in software and then stores them on the PKCS#11 hardware.
This is potentially less secure than generating the keys directly on the device.

**Comment by AeroBuffalo** [comment]
I am looking for a library that is capable of performing this operation. Do you know how much work it would be to get this feature implemented? I would be willing to assist the development, if that helps.

**Comment by mtrojnar** [comment]
What exactly do you mean by "assisting the development"?  You can submit a PR.

**Comment by AeroBuffalo** [comment]
I meant that I would be willing to help write the code to implement the feature. I haven't yet actually done any work yet, but if you point me in the right direction, I would be happy to start.

**Comment by mouse07410** [comment]
@mtrojnar @dengert is there a PKCS#11 command, some `C_XXX` to tell the token to generate a key pair?

**Comment by mtrojnar** [comment]
@mouse07410 The function you need is `C_GenerateKeyPair`.  Consider reading http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.html

**Comment by mtrojnar** [comment]
@n3wtron I guess you may be interested in implementing this feature.

**Comment by n3wtron** [comment]
@mtrojnar I'll try.

**Comment by mtrojnar** [comment]
Implemented by #188.
