### ISSUE TITLE
How to generate ECC keypair by p11?

### ISSUE THREAD

**Issue by Shudonga** [OpenSC/libp11#538]
Hi all,
    Thanks you so much in advance!
    We meet some diffcults when we generate ecc key pair by PKCS11_generate_key API.
    We didn't find the param to specify the ecc curves information, and this api is deprecated. Is there any other new api for generate ecc key?

**Comment by dengert** [comment]
Looks like  `PKCS11_generate_key` is deprecated: https://github.com/OpenSC/libp11/blob/master/src/p11_front.c#L402-L412
and `pkcs11-generate_key`  never supported ECC https://github.com/OpenSC/libp11/blob/master/src/p11_key.c#L266-L325

So you have several options:
- Call PKCS11 directly but loading a PKCS11 module
- Submit a Pull Request to support what you need is libp11
- Use some other program to call PKCS11 for example: `OpenSC` `pkcs11-tool` 
- Use `p11-kit` `p11tool`
-  Use the card vendor tools to generate an ECC key
- Look at https://github.com/latchset/pkcs11-provider

pkcs11-provider  is newer and designed to works with OpenSSL "providers" where as libp11 was designed to supports OpenSSL "engines",  AFAIK there is no one working on supporting "providers" from libp11.  
OpenSSL 3.0 and above may still support engines, but they are deprecated.

Note: that not all cards may support generating a key by calling PKCS11.  
(You did not say what PKCS11 module(s) you are using or what card you are using.)

**Comment by Shudonga** [comment]
@dengert I am sorry for late reply and thanks for your reply.
As follow your direction, we call PKCS11 directly by loading PKCS module, and it can works, tks for your guidence!
As submit a pull to provide this function. Do you will accept this pull? :)

**Comment by dengert** [comment]
I am not  sure what you did to get it to work. A pull request would a chenge to code or documentation to the source code.
So a pull request  may not be needed.
 
@mtrojnar any comment?

**Comment by Shudonga** [comment]
@dengert We use libckteec as our pkcs#11 module. Now we call libckteec.so to generate ecc keypair directly, it can works.
If libpkcs11.so decrapte all keypair generate functions, how to use openssl to generate keypair with pkcs#11 ?

**Comment by Shudonga** [comment]
In other word, if we want to gnerate key or keypair by openssl with libp11.so as engine, how can we do this? If libp11.so will not support this function, if there any other library alternative

**Comment by mtrojnar** [comment]
I'm confused.  Is this feature request about a libp11 API function to generate EC keys, or about the pkcs11 engine functionality (engine control command?) to generate EC keys?  Do you know any other OpenSSL engine that supports EC key generation?  I'll be glad to use the same or similar interfaces.  As far as I understand, the OpenSSL engine interface was designed for using existing keys and not for creating new keys.

**Comment by Shudonga** [comment]
@mtrojnar thanks for your quick reply. I want to use openssl with libp11 engine to generate ecc keypair. 
I am not familiar with openssl engine, so i am not sure whether other OpenSSL engine support EC key generation. But as your said, I guess the answer is not.

Back to the question, if we want to generate key pair by pkcs#11. Is the best way to call module directly?

**Comment by mtrojnar** [comment]
> Back to the question, if we want to generate key pair by pkcs#11. Is the best way to call module directly?

I'm not sure how you define "best" here.  The easiest one is probably with `pkcs11-tool`: https://linux.die.net/man/1/pkcs11-tool

**Comment by dengert** [comment]
Did we miss something? 
libp11 needs to load a pkcs11 module, for example your libckteec.so 
see 
https://github.com/OpenSC/libp11
look for the MODULE_PATH which should be your module

**Comment by mtrojnar** [comment]
> I want to use openssl with libp11 engine to generate ecc keypair. 

Why OpenSSL and libp11?  The keypair is going to be generated on your PKCS#11 device, so you don't need a cryptographic library for that.

**Comment by Shudonga** [comment]
Because our customer is more familar with OpenSSL 😢

**Comment by mtrojnar** [comment]
> Because our customer is more familar with OpenSSL 😢

There is no way I know to forward the OpenSSL key generation API to libp11 or our PKCS#11 engine, so I don't see how familiarity with OpenSSL could possibly be relevant here.

**Comment by socketpair** [comment]
Does anyone know if it is ever possible with OpenSSL PKCS11 provider ?

@Shudonga @mtrojnar  @dengert

**Comment by dengert** [comment]
> Does anyone know if it is ever possible with OpenSSL PKCS11 provider ?

Google for openssl generate key using provider

Says for RSA: openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private_key.pem

for EC: openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out ec_key.pem

If libp11 does not work look at https://github.com/openssl-projects/pkcs11-provider which is from RedHat

**Comment by dengert** [comment]
Since the main point in using PKCS11 with a token, is the private key stays on the token. So the `-out private_key.pem` will not have the private key, just the public key. (PKCS11 treats private and public keys as separate objects. OpenSSL treats them as one object.) 

Google for openssl generate key using pkcs11-provider

**Comment by dengert** [comment]
@socketpair I see you are asking the same question on multiple list, but not saying what token are you using. 

When generating key(s) on a token, the idea is to get the key generated on the token so it can be use at a later time. So  using the  token or card manufacture or applet tools is the most straight forward way to do it. After creation you can use an OpenSSL provider to use the key to sign, encrypt or derive on the token.  It is also possible to use Windows `certutil` as most token or card vendors provide windows drivers. 

Some common applets include OpenPGP, PIV,  TPM2 or PKCS15 tokens and cards. OpenSC supports many different cards and applets via PKCS11. Is your token one of these? 

If you are going to use PKCS11 either via an OpenSSL provider, or via a PKCS11 tool such as OpenSC's `pkcs11-tool` you will need to know how specify the  PKCS11 parameters or use a URL that contains the parameters. See: [RFC 7512](https://datatracker.ietf.org/doc/html/rfc7512) as most tools these days will accept a PKCS11 URI.

**Comment by socketpair** [comment]
@dengert okay, I actually use Rutoken USB tokens. Well, I can easily generate keys using either Windows certutil or Linux pkcs11 tools. Works. But I want to use them in own application that involves keys creation. I don't want to call pkcs11 API directly. Creating key (e.g. non-exportable ones) through some OpenSSL calls would be good simplification for me. Googling says that no standard ways to create keys in this scenario. I'm confusing. Possibly there was no way before (with engines), and possible today there is a way through providers.

**Comment by dengert** [comment]
Google for:  openssl generate key using pkcs11-provider

Says:

To generate a key pair directly on a hardware security module (HSM) or smart card using the OpenSSL 3.0 pkcs11-provider, use the openssl genpkey command with a PKCS#11 URI. 

```
openssl genpkey -propquery "provider=pkcs11" \
    -algorithm RSA \
    -pkeyopt "pkcs11_uri:pkcs11:object=${P11_LABEL}?pin-value=${P11_PIN}"
```

So look at the OpenSSL version 3  `apps/genpkey.c`  to see how it uses a provider and add to you OpenSSL application.

 looks like it calls app_keygen in `./lib/apps.c`
