### ISSUE TITLE
Build a static pkcs11 engine library

### ISSUE THREAD

**Issue by maroueneboubakri** [OpenSC/libp11#551]
Hello,

Has anyone succeeded to build a static pkcs11 library ? Despite that engine are designed to be dynamically loaded, but programmatically we still can set and register an engine in my application which would be statically linked against OpenSSL library and PKCS11 engine and would be great if the build system supports it, or maybe it is supported, but how to generate it.

Best
Maro

**Comment by maroueneboubakri** [comment]
@mtrojnar FYI

**Comment by maroueneboubakri** [comment]
With `--disable-shared  --enable-static ` pkcs11 library is not generate for Linux host, while for MinGW it is generating a static pkcs11.a library.

**Comment by mtrojnar** [comment]
How do you intend to use a static OpenSSL engine?

**Comment by maroueneboubakri** [comment]
> How do you intend to use a static OpenSSL engine?

Using `ENGINE_add()` to add a new engine to OpenSSL's internal list. The engine front has `bind_helper()` that can be exported an used to create the engine.

Best
Maro

**Comment by mtrojnar** [comment]
I admit I have zero experience with using static engines with OpenSSL.  Feel free to submit a PR to add support for that.
