### ISSUE TITLE
Problems loading pkcs11 engine

### ISSUE THREAD

**Issue by fpierrat** [OpenSC/libp11#569]
Hi
I built openssl 3.4.0 and libp11 0.4.12 on windows (MSVC) for x64.

I can load the engine from cmd prompt:
`openssl engine dynamic -pre SO_PATH:"C:\Program Files\OpenSSL\lib\engines-3\engine_pkcs11.dll" -pre ID:pkcs11 -pre LIST_ADD:1 -pre LOAD -post MODULE_PATH:"C:\Program Files\OpenSSL\lib\pkcs11-modules\libp11.dll" -t`
results in:
```
(dynamic) Dynamic engine loading support
[Success]: SO_PATH:C:\Program Files\OpenSSL\lib\engines-3\engine_pkcs11.dll
[Success]: ID:pkcs11
[Success]: LIST_ADD:1
[Success]: LOAD
Loaded: (pkcs11) pkcs11 engine
     [ available ]
[Success]: MODULE_PATH:C:\Program Files\OpenSSL\lib\pkcs11-modules\libp11.dll
```

So far everything perfect.
Now I'm trying to load it from `openssl.cnf` file.
I finally reduced the whole conf file to following:
```
openssl_conf = openssl_init

[openssl_init]
engines=engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = C:\\Users\\FP\Documents\\Appmobile\\Projets\\Certification_Authority\\OVH_KMS\\tests_aeff\\pkcs11engine\\engine_pkcs11.dll
MODULE_PATH = C:\\Users\\FP\Documents\\Appmobile\\Projets\\Certification_Authority\\OVH_KMS\\tests_aeff\\pkcs11engine\\libp11.dll
init = 0
```
Nota: I put the DLLs in a user folder to avoid any problem with the stupid space in windows' "program files" folder name, they initially where in `lib\engines-3` subfolder of openssl install path.

This conf seems to be ignored and the engine NOT loaded: `openssl engine -t pkcs11`
```
14080000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\Program Files\OpenSSL\lib\engines-3\pkcs11.dll)
14080000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:147:
14080000:error:13000084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:438:
14080000:error:13000074:engine routines:ENGINE_by_id:no such engine:crypto\engine\eng_list.c:475:id=pkcs11
```
I finally read about the `config_diagnostics = 1` option and added it in my `openssl.cnf` file.
Now even a simple `openssl version` triggers following:
```
FATAL: Startup failure (dev note: apps_startup()) for openssl
04210000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\Users\FPDocuments\Appmobile\Projets\Certification_Authority\OVH_KMS\tests_aeff\pkcs11engine\engine_pkcs11.dll)
04210000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:147:
04210000:error:13000084:engine routines:dynamic_load:dso not found:crypto\engine\eng_dyn.c:438:
04210000:error:13000066:engine routines:int_engine_configure:engine configuration error:crypto\engine\eng_cnf.c:139:section=pkcs11_section, name=dynamic_path, value=C:\Users\FPDocuments\Appmobile\Projets\Certification_Authority\OVH_KMS\tests_aeff\pkcs11engine\engine_pkcs11.dll
04210000:error:0700006D:configuration file routines:module_run:module initialization error:crypto\conf\conf_mod.c:288:module=engines, value=engine_section retcode=-1
```
Good news: it proves my `openssl.cnf` is actually used, I was even doubting that!

What apears strange to me is this part: `win32_load:could not load the shared library:crypto\dso\dso_win32`.
Openssl was built for x64, why should it try to load a win32-whatever?
Is this the problem (and how can I solve it?), or do you see something else in the above?
Thanks in advance for any help, it's been so many hours now lost on this :'-(

**Comment by mtrojnar** [comment]
"Win32" is often used as the name of the Windows API regardless of whether the application or library is compiled for 32-bit or 64-bit platform.
