### ISSUE TITLE
Libp11 needs a boostrap file

### ISSUE THREAD

**Issue by dengert** [OpenSC/libp11#59]
Recent changes in git master required an 
autoreconf --verbose --install --force
to be run. 
Can the OpenSC bootstrap by copied?

**Comment by mtrojnar** [comment]
What's the advantage of `bootstrap` over `autoreconf -fvi`?

**Comment by mtrojnar** [comment]
While searching the Internet I learned that `bootstrap` was useful many hears ago, when `autoreconf` was not available or buggy.  Is it still the case nowadays?

**Comment by dengert** [comment]
The existance of a bootstrap script make it obvious that something has to be done after a checkout
or when working with a development version of the code. And It may have more then just an autoreconf command.   What I am asking for is bootstrap script:

 \#!/bin/sh
 autoreconf --verbose --install --force

The above is what OpenSC has. OpenSC also has a bootstrap.ci

**Comment by mtrojnar** [comment]
I re-added the bootstrap file in https://github.com/OpenSC/libp11/commit/cedea953b22697d6d0fe897be4e4cf7392b2602d.
