### ISSUE TITLE
openssl-1.1 changed the naming convention

### ISSUE THREAD

**Issue by mouse07410** [OpenSC/libp11#68]
From now on, openssl-1.1 is looking not for **`libpkcs11.so`**  but for **`pkcs11.so`**. Notice that it dropped the `lib` prefix from the name. This has been discussed in https://github.com/openssl/openssl/issues/727

The current work-around is to symlink `libpkcs11.so` to `pkcs11.so` after successful installation.

It would be nice, however, if the configuration script could figure what version of OpenSSL it is dealing with, and prepared the install accordingly.

**Comment by mtrojnar** [comment]
I've located the OpenSSL commit: https://github.com/openssl/openssl/commit/9ee0ed3de66678a15db126d10b3e4226e835b8f5.
I'll take care of it.

**Comment by mouse07410** [comment]
Thank you!  

P.S. You're aware that the current `libp11` works with both RSA and ECC tokens, with both OpenSSL-1.0.2f+ and 1.1, right? ;)

**Comment by mtrojnar** [comment]
According to my tests ECDSA works with OpenSSL 1.0.0 and later.  ECDH key derivation seems to require a recent version of OpenSSL 1.0.2.

I spent most of the February cleaning up and improving the ECDSA/ECDH code written by @dengert (thank you, @dengert!), so you can safely assume I am aware of its features:
https://github.com/OpenSC/libp11/blob/master/NEWS
https://github.com/OpenSC/libp11/blame/master/src/p11_ec.c

**Comment by mouse07410** [comment]
> ...you can safely assume I am aware of its features...

;-)  No offense meant.

I think that ECDH support starts with OpenSSL-1.0.2f. That's where the patches went in first.

On a semi-related subject: in your opinion is it feasible to enable switching in the engine between the old (pre-ECDH fix) and the new/current behavior in `p11_ec.c`, based on a flag or an openssl CLI switch?

**Comment by mtrojnar** [comment]
> ;-) No offense meant.

None taken.

> switching in the engine between the old (pre-ECDH fix) and the new/current behavior in p11_ec.c, based on a flag or an openssl CLI switch

I'm not sure why anyone would want the old behavior.  Could you explain?

**Comment by mouse07410** [comment]
> I'm not sure why anyone would want the old behavior. Could you explain?

Certainly.

The main (openssl cli) usage of `ECDH-DERIVE` is this (having peer's ephemeral public key, and my private key on a hardware token):

```
$ openssl pkeyutl -engine pkcs11 -keyform engine -derive -inkey  "pkcs11:object=KEY%20MAN%20key;object-type=private" -peerform DER -peerkey /tmp/derive.62672.pub.der -hexdump
engine "pkcs11" set.
PKCS#11 token PIN: 
0000 - b3 41 58 6a 3e c5 68 23-2f fd ee 16 cb df 31 cf   .AXj>.h#/.....1.
0010 - 0c 0d a4 64 6c e6 33 c3-ed 6b 99 6f d3 c9 98 47   ...dl.3..k.o...G
0020 - a9 0a 45 93 c2 f1 10 32-ba 08 23 5a e1 f9 38 95   ..E....2..#Z..8.
```

As shown above, it works fine. Great!

A less practical usage is when an ephemeral private key is in a file, and the derivation is done with the *public* key residing on the token. As Doug pointed out, this is a contorted case, because in practice you aren't likely to have somebody else's token in your card reader or USB port. I agree. But still, this (which fails now)
```
openssl pkeyutl -engine pkcs11 -peerform engine -derive -inkey /tmp/derive.60770.priv.pem -peerkey "pkcs11:object=KEY%20MAN%20pubkey;object-type=public" -out /tmp/derive.60770.shared1
engine "pkcs11" set.
Public Key operation error
```
used to work before:
```
$ apps/openssl pkeyutl -engine pkcs11 -keyform PEM -peerform engine -derive -inkey /tmp/derive.1017.priv.pem -peerkey "pkcs11:object=KEY%20MAN%20pubkey;object-type=public" -hexdump
engine "pkcs11" set.
0000 - 74 68 17 49 f2 4a d0 0f-73 4e ed c8 81 68 58 87   th.I.J..sN...hX.
0010 - 19 61 ba 11 d9 e8 05 d5-d7 fd cf e4 62 52 52 35   .a..........bRR5
```
All my test scripts (RSA sign & verify, ECDSA sign & verify, RSA encrypt & decrypt, ECDH derive) exercise both situations - (1) private key on the token, and (2) public key on the token. So if it is doable, I'd like to be able to restore that old behavior *for the case when the requested operation uses public key on the token* (for which it of course extracts the key and processes it in software, as no token actually performs operations with public keys, only with private keys - which is why the second example fails). Of course if there is no way to have both, I'd rather have what is working now (derivation with private key on the token).

I'm afraid my explanation is verbose and convoluted. The "what* part is described (adequately, I hope) in https://github.com/OpenSC/libp11/issues/49#issuecomment-178853706 . I tried to do a decent job describing the "why", not sure how clear my explanation was...

**Comment by mtrojnar** [comment]
As usual, you should have opened a new issue for this defect to help me track it.
I have started looking for a solution.

**Comment by mouse07410** [comment]
> As usual, you should have opened a new issue for this defect to help me track it.

Certainly. We can move this conversation here: https://github.com/OpenSC/libp11/issues/69

> I have started looking for a solution.

Great, thank you!

**Comment by mouse07410** [comment]
Thank you!
