### ISSUE TITLE
p11_ec does not compile for OpenSSL 1.0.2 - fix proposed

### ISSUE THREAD

**Issue by DDvO** [OpenSC/libp11#77]
Nice to see that EC support has been added meanwhile. Trying it out, I found and fixed three issues with p11_ec.c.

Here's the first one: it does not compile with OpenSSL 1.0.2 (to be more precise: 1.0.2d) because the declaration for `struct ecdsa_method` is not visible. This can be corrected easily as given in the attached diff/patch file.

[p11_ec_OpenSSL-1.0.2d_ecdsa_method.patch.txt](https://github.com/OpenSC/libp11/files/224194/p11_ec_OpenSSL-1.0.2d_ecdsa_method.patch.txt)

**Comment by mtrojnar** [comment]
Please use pull requests to submit changes.

**Comment by mouse07410** [comment]
I'm a little surprised because I use `libp11` mainly with OpenSSL-1.0.2, and only testing with 1.1.0. ECC seemed to compile and work OK here on Mac OS X.

**Comment by mtrojnar** [comment]
Which exact OpenSSL 1.0.2 release did you use for testing it?

**Comment by DDvO** [comment]
I'm using OpenSSL 1.0.2d; maybe `include/ec.h` has been corrected since then to include` struct ecdsa_method`. In this case, the version numbers given in my fix need to be refined.

**Comment by dengert** [comment]
It compiles with openssl-1.0.2f  The EC code has undergone a lot of changes and parts needed for ECDSA was only added in 1.0.2  
See:
https://mta.openssl.org/pipermail/openssl-dev/2014-December/000192.html

**Comment by mtrojnar** [comment]
I could not reproduce this issue.  The functions to allocate and set fields of ECDSA_METHOD were added in https://github.com/openssl/openssl/commit/7c23127fde8fe94af914961eb7702caa7f256a05 and released with OpenSSL 1.0.2.  `struct ecdsa_method` is never used in libp11 when compiled with OpenSSL 1.0.2 and later.

**Comment by DDvO** [comment]
Oh, you are right. Thanks for your comments. We can close this issue as invalid.

`struct ecdsa_method` is not directly used by libp11 for OpenSSL versions below 1.1, though functions like `int ECDSA_set_method(EC_KEY *eckey, const ECDSA_METHOD *meth)` and `ECDSA_METHOD *PKCS11_get_ecdsa_method(void)` are called in `p11_ec.c` and deal with pointers to type `ECDSA_METHOD`, which is declared as `typedef struct ecdsa_method ECDSA_METHOD`. 
I was mislead by a colleague who thought she needs to directly access that structure in order to set the do_sign pointer, but it's much better to use the public `ECDSA_METHOD_set_sign()` function, like libp11 does.
