### ISSUE TITLE
multithreading support in libp11

### ISSUE THREAD

**Issue by esmeagol** [OpenSC/libp11#82]
I am using libp11 and engine_pkcs11 code with openssl to access RSA private key operations with SafeNet HSMs. In multithreaded environment, running into CKR_OPERATION_ACTIVE error with C_SignInit call from pkcs11_private_decrypt.

I see that the CRYPTOKI_call is protected by the CRYPTO_THREAD_write_lock call, but the slot->rwlock member is 0.  I see that rwlock is created via CRYPTO_THREAD_lock_new() call which is defined in libp11 code. Why does libp11 define it's own  CRYPTO_THREAD_lock_new() instead of using openssl's implementation?

**Comment by mtrojnar** [comment]
Are you sure your application has properly registered the dynamic callbacks as described at the bottom of the https://github.com/OpenSC/libp11 page?

**Comment by esmeagol** [comment]
Ooh sorry, the application did not have the dynamic callbacks registered, I'll fix that. Thank you for maintaining this library, this has been really helpful!
