### ISSUE TITLE
Loading multiple keys invalidates previous key references

### ISSUE THREAD

**Issue by matthauck** [OpenSC/libp11#89]
I am able to reproduce this extremely consistently. I am loading pkcs11.so dynamically in my application and registering as an OpenSSL engine, then using the openssl engine interface to load the keys and sign stuff with it. Everything works splendidly until I load a key twice.

1. Generate an EC key inside HSM (testing with SoftHSMv2, with secp112r1 EC key)
2. Initialize pkcs11 as OpenSSL engine
3. Load the key: `EVP_PKEY* key1 = ENGINE_load_private_key(...)`
4. Load the key again: `EVP_PKEY* key2 = ENGINE_load_private_key(...)`
5. Start thread1 which uses key1 to sign something
6. Start thread2 which uses key2 to sign something

thread1 seems to consistently setgfault inside pkcs11.so when exercised in this pattern. If threads are taken out of the equation and the above steps are run synchronously, the behavior is (strangely) less predictable but still mostly fails -- sometimes a segfault, sometimes an OpenSSL error, sometimes it works fine. The segfault is always on the `KEY2SLOT(key)` call inside [pkcs11_ecdsa_sign](https://github.com/OpenSC/libp11/blob/21a2d03/src/p11_ec.c#L197), due to the `key->_private` member being invalid. 

The failure appears to be due to the pkcs11_login call inside [pkcs11_load_key](https://github.com/OpenSC/libp11/blob/21a2d03/src/eng_back.c#L738), which [results in](https://github.com/OpenSC/libp11/blob/master/src/p11_slot.c#L195-L198) the reset of some global state, including destroying keys libp11 knows about for that slot. 

It looks like the loading of key2 in between the loading and the use of key1 has caused libp11 to forgot about key1 in that the internal data that was stored on the EVP_PKEY was deleted or something. This is where my understanding of the problem comes short. 

I have tested modifying  pkcs11_load_key to only login if not already logged in (using `PKCS11_is_logged_in`). Avoid the unneeded login fixes the above use case for me. I can post that as a PR if it is something you would like to take upstream. But I wonder if that doesn't really solve the heart of the issue. My fear is that there may be other places where some global state gets reset and other key references become invalidated.

If that is indeed the case, then I would not have confidence that any key reference I have is still valid and hasn't been invalidated by some other thread.

Questions:
* Is the above usage pattern expected to be supported by libp11? 
* Is the above concern about global state being reset in some other way a valid fear?
* Are long-standing key references not a good idea based on the internal design of libp11?

**Comment by matthauck** [comment]
Doh. I think I may have read the comment here too quickly: https://github.com/OpenSC/libp11#thread-safety-in-libp11

I had setup the regular crypto lock callbacks for openssl, but not the dynamic ones. :cry:

**Comment by matthauck** [comment]
Hmm. Interesting, however, that the `ENGINE_init` [callback](https://github.com/OpenSC/libp11/blob/21a2d03/src/eng_back.c#L253-L255) requires that these dynamic lock callbacks have not yet been initialized. Worked around that issue (although not ideal), and was able to reproduce the same segfault, though after running it lots of times, I did notice a few times that actually succeeded... Anyway, looks like it is still the above login issue and not simply solved by adding locking.

**Comment by mouse07410** [comment]
I suspect you are wrong here. 

`SIGN key` must be used immediately after successful PIN verification. You must not succeed performing two signing operations in the row without verifying the PIN *again* just before the second attempt to sign.

Now for `KEY MAN key` the above is (usually) not correct, and you should be able to perform repeated decryptions without having to re-authenticate.

@mtrojnar, I'd like to hear @dengert 's opinion on this issue.

**Comment by matthauck** [comment]
Certainly possible I am doing something wrong. Good to know what only one sign operation is intended per loading of the private key. Is this recommended/dictated by the PKCS11 standard, or is this part of the libp11 library's expectation only? Does this mean I should call `ENGINE_load_private_key` again, or is this something that libp11 handles internally if the PIN is set via an engine ctrl command?

Note, however, that I am seeing the above failure on the _first_ signature performed. The distinction is that another key has been loaded in between the loading of the key and the use of the key. Load key1, Load key2, Sign with key1, Fail.

**Comment by matthauck** [comment]
Hmm. It just occurred to me that you meant that my change in PR #90 is actually incorrect as the re-login is on purpose.

**Comment by mtrojnar** [comment]
Yes, `PKCS11_login` indeed destroys any previously retrieved keys.

**Comment by mouse07410** [comment]
> Good to know what only one sign operation is intended per loading of the private key. 

Not "per loading", but "per request to sign".  It is about the need to re-authenticate - not the need to re-load the key.
 
> Is this recommended/dictated by the PKCS11 standard, or is this part of the libp11 library's expectation only?

Re-auth is the standard. Re-loading - @mtrojnar is the one who can answer.

> It just occurred to me that you meant that my change in PR #90 is actually incorrect as the re-login is on purpose.

Yes I did. As the re-login is indeed on purpose. It is required because of `CKA_ALWAYS_AUTHENTICATE` attribute of the signing key.

@mtrojnar I figure you considered this before deciding to merge #90?  Since I don't write/have any app whose threads are racing with each other for access to the signing key, I cannot test this myself, so can't tell whether this PR actually broke the correct behavior or not.

**Comment by mtrojnar** [comment]
The ligh-level libp11 API is very different from the low-level PKCS#11 API.  For libp11, the PKCS11_login operation is only used initially, before retrieving the list of private keys from the device.  Internally, libp11 also invokes the PKCS#11 C_Login operation (if needed) before private key operations.

**Comment by mouse07410** [comment]
OK, thank you!
