### ISSUE TITLE
Compile fails when the number of jobs is large

### ISSUE THREAD

**Issue by derekstraka** [OpenSC/libp11#94]
`make -j 22` at the top-level on a machine with a large number of cores

Associated compilation output:
```
cd .libs && ln -s -f pkcs11.so libpkcs11.so
/bin/bash: line 0: cd: .libs: No such file or directory
make[2]: *** [all-local] Error 1
make[2]: *** Waiting for unfinished jobs....
```
(Full log: http://errors.yoctoproject.org/Errors/Details/75462/)

It appears that the target `all-local` does not have the required dependencies defined explicitly

I added `all-local: $(LTLIBRARIES)` as a quick work around.  I can create a PR if that is a valid long term fix

**Comment by mtrojnar** [comment]
Please do.

**Comment by mtrojnar** [comment]
Thank you!
